/*
 * This file is generated by jOOQ.
 */
package io.cattle.platform.core.model.tables.records;


import io.cattle.platform.core.model.AuthToken;
import io.cattle.platform.core.model.tables.AuthTokenTable;
import io.cattle.platform.db.jooq.utils.TableRecordJaxb;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import java.util.Date;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Entity
@Table(
    name = "auth_token",
    schema = "cattle",
    uniqueConstraints = {
        @UniqueConstraint(name = "KEY_auth_token_idx_auth_token_key", columnNames = { "key" }),
        @UniqueConstraint(name = "KEY_auth_token_key", columnNames = { "key" })
    },
    indexes = {
        @Index(name = "idx_auth_token_expires", columnList = "expires ASC")
    }
)
public class AuthTokenRecord extends UpdatableRecordImpl<AuthTokenRecord> implements TableRecordJaxb, AuthToken {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>cattle.auth_token.id</code>.
     */
    @Override
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>cattle.auth_token.id</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>cattle.auth_token.account_id</code>.
     */
    @Override
    public void setAccountId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>cattle.auth_token.account_id</code>.
     */
    @Column(name = "account_id", nullable = false)
    @Override
    public Long getAccountId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>cattle.auth_token.created</code>.
     */
    @Override
    public void setCreated(Date value) {
        set(2, value);
    }

    /**
     * Getter for <code>cattle.auth_token.created</code>.
     */
    @Column(name = "created", nullable = false)
    @Override
    public Date getCreated() {
        return (Date) get(2);
    }

    /**
     * Setter for <code>cattle.auth_token.expires</code>.
     */
    @Override
    public void setExpires(Date value) {
        set(3, value);
    }

    /**
     * Getter for <code>cattle.auth_token.expires</code>.
     */
    @Column(name = "expires", nullable = false)
    @Override
    public Date getExpires() {
        return (Date) get(3);
    }

    /**
     * Setter for <code>cattle.auth_token.key</code>.
     */
    @Override
    public void setKey(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>cattle.auth_token.key</code>.
     */
    @Column(name = "key", nullable = false, length = 40)
    @Override
    public String getKey() {
        return (String) get(4);
    }

    /**
     * Setter for <code>cattle.auth_token.value</code>.
     */
    @Override
    public void setValue(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>cattle.auth_token.value</code>.
     */
    @Column(name = "value", nullable = false, length = 16777215)
    @Override
    public String getValue() {
        return (String) get(5);
    }

    /**
     * Setter for <code>cattle.auth_token.version</code>.
     */
    @Override
    public void setVersion(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>cattle.auth_token.version</code>.
     */
    @Column(name = "version", nullable = false, length = 255)
    @Override
    public String getVersion() {
        return (String) get(6);
    }

    /**
     * Setter for <code>cattle.auth_token.provider</code>.
     */
    @Override
    public void setProvider(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>cattle.auth_token.provider</code>.
     */
    @Column(name = "provider", nullable = false, length = 255)
    @Override
    public String getProvider() {
        return (String) get(7);
    }

    /**
     * Setter for <code>cattle.auth_token.authenticated_as_account_id</code>.
     */
    @Override
    public void setAuthenticatedAsAccountId(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>cattle.auth_token.authenticated_as_account_id</code>.
     */
    @Column(name = "authenticated_as_account_id")
    @Override
    public Long getAuthenticatedAsAccountId() {
        return (Long) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return super.key().into(AuthTokenTable.AUTH_TOKEN.ID);
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(AuthToken from) {
        setId(from.getId());
        setAccountId(from.getAccountId());
        setCreated(from.getCreated());
        setExpires(from.getExpires());
        setKey(from.getKey());
        setValue(from.getValue());
        setVersion(from.getVersion());
        setProvider(from.getProvider());
        setAuthenticatedAsAccountId(from.getAuthenticatedAsAccountId());
        resetTouchedOnNotNull();
    }

    @Override
    public <E extends AuthToken> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AuthTokenRecord
     */
    public AuthTokenRecord() {
        super(AuthTokenTable.AUTH_TOKEN);
    }

    /**
     * Create a detached, initialised AuthTokenRecord
     */
    public AuthTokenRecord(Long id, Long accountId, Date created, Date expires, String key, String value, String version, String provider, Long authenticatedAsAccountId) {
        super(AuthTokenTable.AUTH_TOKEN);

        setId(id);
        setAccountId(accountId);
        setCreated(created);
        setExpires(expires);
        setKey(key);
        setValue(value);
        setVersion(version);
        setProvider(provider);
        setAuthenticatedAsAccountId(authenticatedAsAccountId);
        resetTouchedOnNotNull();
    }
}
