/*
 * This file is generated by jOOQ.
 */
package io.cattle.platform.core.model.tables.records;


import io.cattle.platform.core.model.ConfigItem;
import io.cattle.platform.core.model.tables.ConfigItemTable;
import io.cattle.platform.db.jooq.utils.TableRecordJaxb;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Entity
@Table(
    name = "config_item",
    schema = "cattle",
    uniqueConstraints = {
        @UniqueConstraint(name = "KEY_config_item_idx_config_item__name", columnNames = { "name" })
    }
)
public class ConfigItemRecord extends UpdatableRecordImpl<ConfigItemRecord> implements TableRecordJaxb, ConfigItem {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>cattle.config_item.id</code>.
     */
    @Override
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>cattle.config_item.id</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>cattle.config_item.name</code>.
     */
    @Override
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>cattle.config_item.name</code>.
     */
    @Column(name = "name", nullable = false, length = 255)
    @Override
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>cattle.config_item.source_version</code>.
     */
    @Override
    public void setSourceVersion(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>cattle.config_item.source_version</code>.
     */
    @Column(name = "source_version", nullable = false, length = 1024)
    @Override
    public String getSourceVersion() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return super.key().into(ConfigItemTable.CONFIG_ITEM.ID);
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(ConfigItem from) {
        setId(from.getId());
        setName(from.getName());
        setSourceVersion(from.getSourceVersion());
        resetTouchedOnNotNull();
    }

    @Override
    public <E extends ConfigItem> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ConfigItemRecord
     */
    public ConfigItemRecord() {
        super(ConfigItemTable.CONFIG_ITEM);
    }

    /**
     * Create a detached, initialised ConfigItemRecord
     */
    public ConfigItemRecord(Long id, String name, String sourceVersion) {
        super(ConfigItemTable.CONFIG_ITEM);

        setId(id);
        setName(name);
        setSourceVersion(sourceVersion);
        resetTouchedOnNotNull();
    }
}
