/*
 * This file is generated by jOOQ.
 */
package io.cattle.platform.core.model.tables.records;


import io.cattle.platform.core.model.ExternalEvent;
import io.cattle.platform.core.model.tables.ExternalEventTable;
import io.cattle.platform.db.jooq.utils.TableRecordJaxb;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import java.util.Date;
import java.util.Map;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Entity
@Table(
    name = "external_event",
    schema = "cattle",
    uniqueConstraints = {
        @UniqueConstraint(name = "KEY_external_event_idx_external_event_uuid", columnNames = { "uuid" })
    },
    indexes = {
        @Index(name = "idx_external_event_state", columnList = "state ASC")
    }
)
public class ExternalEventRecord extends UpdatableRecordImpl<ExternalEventRecord> implements TableRecordJaxb, ExternalEvent {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>cattle.external_event.id</code>.
     */
    @Override
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>cattle.external_event.id</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>cattle.external_event.account_id</code>.
     */
    @Override
    public void setAccountId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>cattle.external_event.account_id</code>.
     */
    @Column(name = "account_id")
    @Override
    public Long getAccountId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>cattle.external_event.kind</code>.
     */
    @Override
    public void setKind(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>cattle.external_event.kind</code>.
     */
    @Column(name = "kind", nullable = false, length = 255)
    @Override
    public String getKind() {
        return (String) get(2);
    }

    /**
     * Setter for <code>cattle.external_event.uuid</code>.
     */
    @Override
    public void setUuid(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>cattle.external_event.uuid</code>.
     */
    @Column(name = "uuid", nullable = false, length = 128)
    @Override
    public String getUuid() {
        return (String) get(3);
    }

    /**
     * Setter for <code>cattle.external_event.state</code>.
     */
    @Override
    public void setState(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>cattle.external_event.state</code>.
     */
    @Column(name = "state", nullable = false, length = 128)
    @Override
    public String getState() {
        return (String) get(4);
    }

    /**
     * Setter for <code>cattle.external_event.created</code>.
     */
    @Override
    public void setCreated(Date value) {
        set(5, value);
    }

    /**
     * Getter for <code>cattle.external_event.created</code>.
     */
    @Column(name = "created")
    @Override
    public Date getCreated() {
        return (Date) get(5);
    }

    /**
     * Setter for <code>cattle.external_event.data</code>.
     */
    @Override
    public void setData(Map<String,Object> value) {
        set(6, value);
    }

    /**
     * Getter for <code>cattle.external_event.data</code>.
     */
    @Column(name = "data", length = 65535)
    @Override
    public Map<String,Object> getData() {
        return get(ExternalEventTable.EXTERNAL_EVENT.DATA);
    }

    /**
     * Setter for <code>cattle.external_event.external_id</code>.
     */
    @Override
    public void setExternalId(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>cattle.external_event.external_id</code>.
     */
    @Column(name = "external_id", length = 255)
    @Override
    public String getExternalId() {
        return (String) get(7);
    }

    /**
     * Setter for <code>cattle.external_event.event_type</code>.
     */
    @Override
    public void setEventType(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>cattle.external_event.event_type</code>.
     */
    @Column(name = "event_type", length = 255)
    @Override
    public String getEventType() {
        return (String) get(8);
    }

    /**
     * Setter for <code>cattle.external_event.reported_account_id</code>.
     */
    @Override
    public void setReportedAccountId(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>cattle.external_event.reported_account_id</code>.
     */
    @Column(name = "reported_account_id")
    @Override
    public Long getReportedAccountId() {
        return (Long) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return super.key().into(ExternalEventTable.EXTERNAL_EVENT.ID);
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(ExternalEvent from) {
        setId(from.getId());
        setAccountId(from.getAccountId());
        setKind(from.getKind());
        setUuid(from.getUuid());
        setState(from.getState());
        setCreated(from.getCreated());
        setData(from.getData());
        setExternalId(from.getExternalId());
        setEventType(from.getEventType());
        setReportedAccountId(from.getReportedAccountId());
        resetTouchedOnNotNull();
    }

    @Override
    public <E extends ExternalEvent> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ExternalEventRecord
     */
    public ExternalEventRecord() {
        super(ExternalEventTable.EXTERNAL_EVENT);
    }

    /**
     * Create a detached, initialised ExternalEventRecord
     */
    public ExternalEventRecord(Long id, Long accountId, String kind, String uuid, String state, Date created, Map<String,Object> data, String externalId, String eventType, Long reportedAccountId) {
        super(ExternalEventTable.EXTERNAL_EVENT);

        setId(id);
        setAccountId(accountId);
        setKind(kind);
        setUuid(uuid);
        setState(state);
        setCreated(created);
        setData(data);
        setExternalId(externalId);
        setEventType(eventType);
        setReportedAccountId(reportedAccountId);
        resetTouchedOnNotNull();
    }
}
