/*
 * This file is generated by jOOQ.
 */
package io.cattle.platform.core.model.tables.records;


import io.cattle.platform.core.model.MachineDriver;
import io.cattle.platform.core.model.tables.MachineDriverTable;
import io.cattle.platform.db.jooq.utils.TableRecordJaxb;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import java.util.Date;
import java.util.Map;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Entity
@Table(
    name = "machine_driver",
    schema = "cattle",
    uniqueConstraints = {
        @UniqueConstraint(name = "KEY_machine_driver_idx_machine_driver_uuid", columnNames = { "uuid" })
    },
    indexes = {
        @Index(name = "idx_machine_driver_name", columnList = "name ASC"),
        @Index(name = "idx_machine_driver_remove_time", columnList = "remove_time ASC"),
        @Index(name = "idx_machine_driver_removed", columnList = "removed ASC"),
        @Index(name = "idx_machine_driver_state", columnList = "state ASC")
    }
)
public class MachineDriverRecord extends UpdatableRecordImpl<MachineDriverRecord> implements TableRecordJaxb, MachineDriver {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>cattle.machine_driver.id</code>.
     */
    @Override
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>cattle.machine_driver.id</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>cattle.machine_driver.name</code>.
     */
    @Override
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>cattle.machine_driver.name</code>.
     */
    @Column(name = "name", length = 255)
    @Override
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>cattle.machine_driver.kind</code>.
     */
    @Override
    public void setKind(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>cattle.machine_driver.kind</code>.
     */
    @Column(name = "kind", nullable = false, length = 255)
    @Override
    public String getKind() {
        return (String) get(2);
    }

    /**
     * Setter for <code>cattle.machine_driver.uuid</code>.
     */
    @Override
    public void setUuid(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>cattle.machine_driver.uuid</code>.
     */
    @Column(name = "uuid", nullable = false, length = 128)
    @Override
    public String getUuid() {
        return (String) get(3);
    }

    /**
     * Setter for <code>cattle.machine_driver.description</code>.
     */
    @Override
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>cattle.machine_driver.description</code>.
     */
    @Column(name = "description", length = 1024)
    @Override
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>cattle.machine_driver.state</code>.
     */
    @Override
    public void setState(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>cattle.machine_driver.state</code>.
     */
    @Column(name = "state", nullable = false, length = 128)
    @Override
    public String getState() {
        return (String) get(5);
    }

    /**
     * Setter for <code>cattle.machine_driver.created</code>.
     */
    @Override
    public void setCreated(Date value) {
        set(6, value);
    }

    /**
     * Getter for <code>cattle.machine_driver.created</code>.
     */
    @Column(name = "created")
    @Override
    public Date getCreated() {
        return (Date) get(6);
    }

    /**
     * Setter for <code>cattle.machine_driver.removed</code>.
     */
    @Override
    public void setRemoved(Date value) {
        set(7, value);
    }

    /**
     * Getter for <code>cattle.machine_driver.removed</code>.
     */
    @Column(name = "removed")
    @Override
    public Date getRemoved() {
        return (Date) get(7);
    }

    /**
     * Setter for <code>cattle.machine_driver.remove_time</code>.
     */
    @Override
    public void setRemoveTime(Date value) {
        set(8, value);
    }

    /**
     * Getter for <code>cattle.machine_driver.remove_time</code>.
     */
    @Column(name = "remove_time")
    @Override
    public Date getRemoveTime() {
        return (Date) get(8);
    }

    /**
     * Setter for <code>cattle.machine_driver.data</code>.
     */
    @Override
    public void setData(Map<String,Object> value) {
        set(9, value);
    }

    /**
     * Getter for <code>cattle.machine_driver.data</code>.
     */
    @Column(name = "data", length = 65535)
    @Override
    public Map<String,Object> getData() {
        return get(MachineDriverTable.MACHINE_DRIVER.DATA);
    }

    /**
     * Setter for <code>cattle.machine_driver.uri</code>.
     */
    @Override
    public void setUri(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>cattle.machine_driver.uri</code>.
     */
    @Column(name = "uri", length = 255)
    @Override
    public String getUri() {
        return (String) get(10);
    }

    /**
     * Setter for <code>cattle.machine_driver.md5checksum</code>.
     */
    @Override
    public void setMd5checksum(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>cattle.machine_driver.md5checksum</code>.
     */
    @Column(name = "md5checksum", length = 255)
    @Override
    public String getMd5checksum() {
        return (String) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return super.key().into(MachineDriverTable.MACHINE_DRIVER.ID);
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(MachineDriver from) {
        setId(from.getId());
        setName(from.getName());
        setKind(from.getKind());
        setUuid(from.getUuid());
        setDescription(from.getDescription());
        setState(from.getState());
        setCreated(from.getCreated());
        setRemoved(from.getRemoved());
        setRemoveTime(from.getRemoveTime());
        setData(from.getData());
        setUri(from.getUri());
        setMd5checksum(from.getMd5checksum());
        resetTouchedOnNotNull();
    }

    @Override
    public <E extends MachineDriver> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MachineDriverRecord
     */
    public MachineDriverRecord() {
        super(MachineDriverTable.MACHINE_DRIVER);
    }

    /**
     * Create a detached, initialised MachineDriverRecord
     */
    public MachineDriverRecord(Long id, String name, String kind, String uuid, String description, String state, Date created, Date removed, Date removeTime, Map<String,Object> data, String uri, String md5checksum) {
        super(MachineDriverTable.MACHINE_DRIVER);

        setId(id);
        setName(name);
        setKind(kind);
        setUuid(uuid);
        setDescription(description);
        setState(state);
        setCreated(created);
        setRemoved(removed);
        setRemoveTime(removeTime);
        setData(data);
        setUri(uri);
        setMd5checksum(md5checksum);
        resetTouchedOnNotNull();
    }
}
