/*
 * This file is generated by jOOQ.
 */
package io.cattle.platform.core.model.tables.records;


import io.cattle.platform.core.model.Nic;
import io.cattle.platform.core.model.tables.NicTable;
import io.cattle.platform.db.jooq.utils.TableRecordJaxb;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import java.util.Date;
import java.util.Map;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Entity
@Table(
    name = "nic",
    schema = "cattle",
    uniqueConstraints = {
        @UniqueConstraint(name = "KEY_nic_idx_nic_uuid", columnNames = { "uuid" })
    },
    indexes = {
        @Index(name = "idx_nic_name", columnList = "name ASC"),
        @Index(name = "idx_nic_remove_time", columnList = "remove_time ASC"),
        @Index(name = "idx_nic_removed", columnList = "removed ASC"),
        @Index(name = "idx_nic_state", columnList = "state ASC")
    }
)
public class NicRecord extends UpdatableRecordImpl<NicRecord> implements TableRecordJaxb, Nic {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>cattle.nic.id</code>.
     */
    @Override
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>cattle.nic.id</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>cattle.nic.name</code>.
     */
    @Override
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>cattle.nic.name</code>.
     */
    @Column(name = "name", length = 255)
    @Override
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>cattle.nic.account_id</code>.
     */
    @Override
    public void setAccountId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>cattle.nic.account_id</code>.
     */
    @Column(name = "account_id")
    @Override
    public Long getAccountId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>cattle.nic.kind</code>.
     */
    @Override
    public void setKind(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>cattle.nic.kind</code>.
     */
    @Column(name = "kind", nullable = false, length = 255)
    @Override
    public String getKind() {
        return (String) get(3);
    }

    /**
     * Setter for <code>cattle.nic.uuid</code>.
     */
    @Override
    public void setUuid(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>cattle.nic.uuid</code>.
     */
    @Column(name = "uuid", nullable = false, length = 128)
    @Override
    public String getUuid() {
        return (String) get(4);
    }

    /**
     * Setter for <code>cattle.nic.description</code>.
     */
    @Override
    public void setDescription(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>cattle.nic.description</code>.
     */
    @Column(name = "description", length = 1024)
    @Override
    public String getDescription() {
        return (String) get(5);
    }

    /**
     * Setter for <code>cattle.nic.state</code>.
     */
    @Override
    public void setState(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>cattle.nic.state</code>.
     */
    @Column(name = "state", nullable = false, length = 128)
    @Override
    public String getState() {
        return (String) get(6);
    }

    /**
     * Setter for <code>cattle.nic.created</code>.
     */
    @Override
    public void setCreated(Date value) {
        set(7, value);
    }

    /**
     * Getter for <code>cattle.nic.created</code>.
     */
    @Column(name = "created")
    @Override
    public Date getCreated() {
        return (Date) get(7);
    }

    /**
     * Setter for <code>cattle.nic.removed</code>.
     */
    @Override
    public void setRemoved(Date value) {
        set(8, value);
    }

    /**
     * Getter for <code>cattle.nic.removed</code>.
     */
    @Column(name = "removed")
    @Override
    public Date getRemoved() {
        return (Date) get(8);
    }

    /**
     * Setter for <code>cattle.nic.remove_time</code>.
     */
    @Override
    public void setRemoveTime(Date value) {
        set(9, value);
    }

    /**
     * Getter for <code>cattle.nic.remove_time</code>.
     */
    @Column(name = "remove_time")
    @Override
    public Date getRemoveTime() {
        return (Date) get(9);
    }

    /**
     * Setter for <code>cattle.nic.data</code>.
     */
    @Override
    public void setData(Map<String,Object> value) {
        set(10, value);
    }

    /**
     * Getter for <code>cattle.nic.data</code>.
     */
    @Column(name = "data", length = 16777215)
    @Override
    public Map<String,Object> getData() {
        return get(NicTable.NIC.DATA);
    }

    /**
     * Setter for <code>cattle.nic.instance_id</code>.
     */
    @Override
    public void setInstanceId(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>cattle.nic.instance_id</code>.
     */
    @Column(name = "instance_id")
    @Override
    public Long getInstanceId() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>cattle.nic.network_id</code>.
     */
    @Override
    public void setNetworkId(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>cattle.nic.network_id</code>.
     */
    @Column(name = "network_id")
    @Override
    public Long getNetworkId() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>cattle.nic.device_number</code>.
     */
    @Override
    public void setDeviceNumber(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>cattle.nic.device_number</code>.
     */
    @Column(name = "device_number")
    @Override
    public Integer getDeviceNumber() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>cattle.nic.mac_address</code>.
     */
    @Override
    public void setMacAddress(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>cattle.nic.mac_address</code>.
     */
    @Column(name = "mac_address", length = 128)
    @Override
    public String getMacAddress() {
        return (String) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return super.key().into(NicTable.NIC.ID);
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(Nic from) {
        setId(from.getId());
        setName(from.getName());
        setAccountId(from.getAccountId());
        setKind(from.getKind());
        setUuid(from.getUuid());
        setDescription(from.getDescription());
        setState(from.getState());
        setCreated(from.getCreated());
        setRemoved(from.getRemoved());
        setRemoveTime(from.getRemoveTime());
        setData(from.getData());
        setInstanceId(from.getInstanceId());
        setNetworkId(from.getNetworkId());
        setDeviceNumber(from.getDeviceNumber());
        setMacAddress(from.getMacAddress());
        resetTouchedOnNotNull();
    }

    @Override
    public <E extends Nic> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NicRecord
     */
    public NicRecord() {
        super(NicTable.NIC);
    }

    /**
     * Create a detached, initialised NicRecord
     */
    public NicRecord(Long id, String name, Long accountId, String kind, String uuid, String description, String state, Date created, Date removed, Date removeTime, Map<String,Object> data, Long instanceId, Long networkId, Integer deviceNumber, String macAddress) {
        super(NicTable.NIC);

        setId(id);
        setName(name);
        setAccountId(accountId);
        setKind(kind);
        setUuid(uuid);
        setDescription(description);
        setState(state);
        setCreated(created);
        setRemoved(removed);
        setRemoveTime(removeTime);
        setData(data);
        setInstanceId(instanceId);
        setNetworkId(networkId);
        setDeviceNumber(deviceNumber);
        setMacAddress(macAddress);
        resetTouchedOnNotNull();
    }
}
