/*
 * This file is generated by jOOQ.
 */
package io.cattle.platform.core.model.tables.records;


import io.cattle.platform.core.model.ResourcePool;
import io.cattle.platform.core.model.tables.ResourcePoolTable;
import io.cattle.platform.db.jooq.utils.TableRecordJaxb;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import java.util.Date;
import java.util.Map;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Entity
@Table(
    name = "resource_pool",
    schema = "cattle",
    uniqueConstraints = {
        @UniqueConstraint(name = "KEY_resource_pool_idx_pool_item2", columnNames = { "pool_type", "pool_id", "qualifier", "item" }),
        @UniqueConstraint(name = "KEY_resource_pool_idx_resource_pool_uuid", columnNames = { "uuid" })
    },
    indexes = {
        @Index(name = "idx_pool_owner2", columnList = "pool_type ASC, pool_id ASC, qualifier ASC, owner_type ASC, owner_id ASC"),
        @Index(name = "idx_resource_pool_name", columnList = "name ASC"),
        @Index(name = "idx_resource_pool_remove_time", columnList = "remove_time ASC"),
        @Index(name = "idx_resource_pool_removed", columnList = "removed ASC"),
        @Index(name = "idx_resource_pool_state", columnList = "state ASC")
    }
)
public class ResourcePoolRecord extends UpdatableRecordImpl<ResourcePoolRecord> implements TableRecordJaxb, ResourcePool {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>cattle.resource_pool.id</code>.
     */
    @Override
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>cattle.resource_pool.id</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>cattle.resource_pool.name</code>.
     */
    @Override
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>cattle.resource_pool.name</code>.
     */
    @Column(name = "name", length = 255)
    @Override
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>cattle.resource_pool.account_id</code>.
     */
    @Override
    public void setAccountId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>cattle.resource_pool.account_id</code>.
     */
    @Column(name = "account_id")
    @Override
    public Long getAccountId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>cattle.resource_pool.kind</code>.
     */
    @Override
    public void setKind(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>cattle.resource_pool.kind</code>.
     */
    @Column(name = "kind", nullable = false, length = 255)
    @Override
    public String getKind() {
        return (String) get(3);
    }

    /**
     * Setter for <code>cattle.resource_pool.uuid</code>.
     */
    @Override
    public void setUuid(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>cattle.resource_pool.uuid</code>.
     */
    @Column(name = "uuid", nullable = false, length = 128)
    @Override
    public String getUuid() {
        return (String) get(4);
    }

    /**
     * Setter for <code>cattle.resource_pool.description</code>.
     */
    @Override
    public void setDescription(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>cattle.resource_pool.description</code>.
     */
    @Column(name = "description", length = 1024)
    @Override
    public String getDescription() {
        return (String) get(5);
    }

    /**
     * Setter for <code>cattle.resource_pool.state</code>.
     */
    @Override
    public void setState(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>cattle.resource_pool.state</code>.
     */
    @Column(name = "state", nullable = false, length = 128)
    @Override
    public String getState() {
        return (String) get(6);
    }

    /**
     * Setter for <code>cattle.resource_pool.created</code>.
     */
    @Override
    public void setCreated(Date value) {
        set(7, value);
    }

    /**
     * Getter for <code>cattle.resource_pool.created</code>.
     */
    @Column(name = "created")
    @Override
    public Date getCreated() {
        return (Date) get(7);
    }

    /**
     * Setter for <code>cattle.resource_pool.removed</code>.
     */
    @Override
    public void setRemoved(Date value) {
        set(8, value);
    }

    /**
     * Getter for <code>cattle.resource_pool.removed</code>.
     */
    @Column(name = "removed")
    @Override
    public Date getRemoved() {
        return (Date) get(8);
    }

    /**
     * Setter for <code>cattle.resource_pool.remove_time</code>.
     */
    @Override
    public void setRemoveTime(Date value) {
        set(9, value);
    }

    /**
     * Getter for <code>cattle.resource_pool.remove_time</code>.
     */
    @Column(name = "remove_time")
    @Override
    public Date getRemoveTime() {
        return (Date) get(9);
    }

    /**
     * Setter for <code>cattle.resource_pool.data</code>.
     */
    @Override
    public void setData(Map<String,Object> value) {
        set(10, value);
    }

    /**
     * Getter for <code>cattle.resource_pool.data</code>.
     */
    @Column(name = "data", length = 16777215)
    @Override
    public Map<String,Object> getData() {
        return get(ResourcePoolTable.RESOURCE_POOL.DATA);
    }

    /**
     * Setter for <code>cattle.resource_pool.pool_type</code>.
     */
    @Override
    public void setPoolType(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>cattle.resource_pool.pool_type</code>.
     */
    @Column(name = "pool_type", length = 255)
    @Override
    public String getPoolType() {
        return (String) get(11);
    }

    /**
     * Setter for <code>cattle.resource_pool.pool_id</code>.
     */
    @Override
    public void setPoolId(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>cattle.resource_pool.pool_id</code>.
     */
    @Column(name = "pool_id")
    @Override
    public Long getPoolId() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>cattle.resource_pool.item</code>.
     */
    @Override
    public void setItem(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>cattle.resource_pool.item</code>.
     */
    @Column(name = "item", length = 255)
    @Override
    public String getItem() {
        return (String) get(13);
    }

    /**
     * Setter for <code>cattle.resource_pool.owner_type</code>.
     */
    @Override
    public void setOwnerType(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>cattle.resource_pool.owner_type</code>.
     */
    @Column(name = "owner_type", length = 255)
    @Override
    public String getOwnerType() {
        return (String) get(14);
    }

    /**
     * Setter for <code>cattle.resource_pool.owner_id</code>.
     */
    @Override
    public void setOwnerId(Long value) {
        set(15, value);
    }

    /**
     * Getter for <code>cattle.resource_pool.owner_id</code>.
     */
    @Column(name = "owner_id")
    @Override
    public Long getOwnerId() {
        return (Long) get(15);
    }

    /**
     * Setter for <code>cattle.resource_pool.qualifier</code>.
     */
    @Override
    public void setResourcePoolQualifier(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>cattle.resource_pool.qualifier</code>.
     */
    @Column(name = "qualifier", nullable = false, length = 128)
    @Override
    public String getResourcePoolQualifier() {
        return (String) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return super.key().into(ResourcePoolTable.RESOURCE_POOL.ID);
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(ResourcePool from) {
        setId(from.getId());
        setName(from.getName());
        setAccountId(from.getAccountId());
        setKind(from.getKind());
        setUuid(from.getUuid());
        setDescription(from.getDescription());
        setState(from.getState());
        setCreated(from.getCreated());
        setRemoved(from.getRemoved());
        setRemoveTime(from.getRemoveTime());
        setData(from.getData());
        setPoolType(from.getPoolType());
        setPoolId(from.getPoolId());
        setItem(from.getItem());
        setOwnerType(from.getOwnerType());
        setOwnerId(from.getOwnerId());
        setResourcePoolQualifier(from.getResourcePoolQualifier());
        resetTouchedOnNotNull();
    }

    @Override
    public <E extends ResourcePool> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ResourcePoolRecord
     */
    public ResourcePoolRecord() {
        super(ResourcePoolTable.RESOURCE_POOL);
    }

    /**
     * Create a detached, initialised ResourcePoolRecord
     */
    public ResourcePoolRecord(Long id, String name, Long accountId, String kind, String uuid, String description, String state, Date created, Date removed, Date removeTime, Map<String,Object> data, String poolType, Long poolId, String item, String ownerType, Long ownerId, String qualifier) {
        super(ResourcePoolTable.RESOURCE_POOL);

        setId(id);
        setName(name);
        setAccountId(accountId);
        setKind(kind);
        setUuid(uuid);
        setDescription(description);
        setState(state);
        setCreated(created);
        setRemoved(removed);
        setRemoveTime(removeTime);
        setData(data);
        setPoolType(poolType);
        setPoolId(poolId);
        setItem(item);
        setOwnerType(ownerType);
        setOwnerId(ownerId);
        setResourcePoolQualifier(qualifier);
        resetTouchedOnNotNull();
    }
}
