/*
 * This file is generated by jOOQ.
 */
package io.cattle.platform.core.model.tables.records;


import io.cattle.platform.core.model.Secret;
import io.cattle.platform.core.model.tables.SecretTable;
import io.cattle.platform.db.jooq.utils.TableRecordJaxb;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import java.util.Date;
import java.util.Map;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Entity
@Table(
    name = "secret",
    schema = "cattle",
    uniqueConstraints = {
        @UniqueConstraint(name = "KEY_secret_idx_secret_uuid", columnNames = { "uuid" })
    },
    indexes = {
        @Index(name = "idx_secret_name", columnList = "name ASC"),
        @Index(name = "idx_secret_remove_time", columnList = "remove_time ASC"),
        @Index(name = "idx_secret_removed", columnList = "removed ASC"),
        @Index(name = "idx_secret_state", columnList = "state ASC")
    }
)
public class SecretRecord extends UpdatableRecordImpl<SecretRecord> implements TableRecordJaxb, Secret {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>cattle.secret.id</code>.
     */
    @Override
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>cattle.secret.id</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>cattle.secret.name</code>.
     */
    @Override
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>cattle.secret.name</code>.
     */
    @Column(name = "name", length = 255)
    @Override
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>cattle.secret.account_id</code>.
     */
    @Override
    public void setAccountId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>cattle.secret.account_id</code>.
     */
    @Column(name = "account_id")
    @Override
    public Long getAccountId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>cattle.secret.kind</code>.
     */
    @Override
    public void setKind(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>cattle.secret.kind</code>.
     */
    @Column(name = "kind", nullable = false, length = 255)
    @Override
    public String getKind() {
        return (String) get(3);
    }

    /**
     * Setter for <code>cattle.secret.uuid</code>.
     */
    @Override
    public void setUuid(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>cattle.secret.uuid</code>.
     */
    @Column(name = "uuid", nullable = false, length = 128)
    @Override
    public String getUuid() {
        return (String) get(4);
    }

    /**
     * Setter for <code>cattle.secret.description</code>.
     */
    @Override
    public void setDescription(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>cattle.secret.description</code>.
     */
    @Column(name = "description", length = 1024)
    @Override
    public String getDescription() {
        return (String) get(5);
    }

    /**
     * Setter for <code>cattle.secret.state</code>.
     */
    @Override
    public void setState(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>cattle.secret.state</code>.
     */
    @Column(name = "state", nullable = false, length = 128)
    @Override
    public String getState() {
        return (String) get(6);
    }

    /**
     * Setter for <code>cattle.secret.created</code>.
     */
    @Override
    public void setCreated(Date value) {
        set(7, value);
    }

    /**
     * Getter for <code>cattle.secret.created</code>.
     */
    @Column(name = "created")
    @Override
    public Date getCreated() {
        return (Date) get(7);
    }

    /**
     * Setter for <code>cattle.secret.removed</code>.
     */
    @Override
    public void setRemoved(Date value) {
        set(8, value);
    }

    /**
     * Getter for <code>cattle.secret.removed</code>.
     */
    @Column(name = "removed")
    @Override
    public Date getRemoved() {
        return (Date) get(8);
    }

    /**
     * Setter for <code>cattle.secret.remove_time</code>.
     */
    @Override
    public void setRemoveTime(Date value) {
        set(9, value);
    }

    /**
     * Getter for <code>cattle.secret.remove_time</code>.
     */
    @Column(name = "remove_time")
    @Override
    public Date getRemoveTime() {
        return (Date) get(9);
    }

    /**
     * Setter for <code>cattle.secret.data</code>.
     */
    @Override
    public void setData(Map<String,Object> value) {
        set(10, value);
    }

    /**
     * Getter for <code>cattle.secret.data</code>.
     */
    @Column(name = "data", length = 16777215)
    @Override
    public Map<String,Object> getData() {
        return get(SecretTable.SECRET.DATA);
    }

    /**
     * Setter for <code>cattle.secret.value</code>.
     */
    @Override
    public void setValue(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>cattle.secret.value</code>.
     */
    @Column(name = "value", length = 16777215)
    @Override
    public String getValue() {
        return (String) get(11);
    }

    /**
     * Setter for <code>cattle.secret.environment_id</code>.
     */
    @Override
    public void setStackId(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>cattle.secret.environment_id</code>.
     */
    @Column(name = "environment_id")
    @Override
    public Long getStackId() {
        return (Long) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return super.key().into(SecretTable.SECRET.ID);
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(Secret from) {
        setId(from.getId());
        setName(from.getName());
        setAccountId(from.getAccountId());
        setKind(from.getKind());
        setUuid(from.getUuid());
        setDescription(from.getDescription());
        setState(from.getState());
        setCreated(from.getCreated());
        setRemoved(from.getRemoved());
        setRemoveTime(from.getRemoveTime());
        setData(from.getData());
        setValue(from.getValue());
        setStackId(from.getStackId());
        resetTouchedOnNotNull();
    }

    @Override
    public <E extends Secret> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SecretRecord
     */
    public SecretRecord() {
        super(SecretTable.SECRET);
    }

    /**
     * Create a detached, initialised SecretRecord
     */
    public SecretRecord(Long id, String name, Long accountId, String kind, String uuid, String description, String state, Date created, Date removed, Date removeTime, Map<String,Object> data, String value, Long environmentId) {
        super(SecretTable.SECRET);

        setId(id);
        setName(name);
        setAccountId(accountId);
        setKind(kind);
        setUuid(uuid);
        setDescription(description);
        setState(state);
        setCreated(created);
        setRemoved(removed);
        setRemoveTime(removeTime);
        setData(data);
        setValue(value);
        setStackId(environmentId);
        resetTouchedOnNotNull();
    }
}
