/*
 * This file is generated by jOOQ.
 */
package io.cattle.platform.core.model.tables.records;


import io.cattle.platform.core.model.Subnet;
import io.cattle.platform.core.model.tables.SubnetTable;
import io.cattle.platform.db.jooq.utils.TableRecordJaxb;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import java.util.Date;
import java.util.Map;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Entity
@Table(
    name = "subnet",
    schema = "cattle",
    uniqueConstraints = {
        @UniqueConstraint(name = "KEY_subnet_idx_subnet_uuid", columnNames = { "uuid" })
    },
    indexes = {
        @Index(name = "idx_subnet_name", columnList = "name ASC"),
        @Index(name = "idx_subnet_remove_time", columnList = "remove_time ASC"),
        @Index(name = "idx_subnet_removed", columnList = "removed ASC"),
        @Index(name = "idx_subnet_state", columnList = "state ASC")
    }
)
public class SubnetRecord extends UpdatableRecordImpl<SubnetRecord> implements TableRecordJaxb, Subnet {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>cattle.subnet.id</code>.
     */
    @Override
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>cattle.subnet.id</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>cattle.subnet.name</code>.
     */
    @Override
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>cattle.subnet.name</code>.
     */
    @Column(name = "name", length = 255)
    @Override
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>cattle.subnet.account_id</code>.
     */
    @Override
    public void setAccountId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>cattle.subnet.account_id</code>.
     */
    @Column(name = "account_id")
    @Override
    public Long getAccountId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>cattle.subnet.kind</code>.
     */
    @Override
    public void setKind(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>cattle.subnet.kind</code>.
     */
    @Column(name = "kind", nullable = false, length = 255)
    @Override
    public String getKind() {
        return (String) get(3);
    }

    /**
     * Setter for <code>cattle.subnet.uuid</code>.
     */
    @Override
    public void setUuid(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>cattle.subnet.uuid</code>.
     */
    @Column(name = "uuid", nullable = false, length = 128)
    @Override
    public String getUuid() {
        return (String) get(4);
    }

    /**
     * Setter for <code>cattle.subnet.description</code>.
     */
    @Override
    public void setDescription(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>cattle.subnet.description</code>.
     */
    @Column(name = "description", length = 1024)
    @Override
    public String getDescription() {
        return (String) get(5);
    }

    /**
     * Setter for <code>cattle.subnet.state</code>.
     */
    @Override
    public void setState(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>cattle.subnet.state</code>.
     */
    @Column(name = "state", nullable = false, length = 128)
    @Override
    public String getState() {
        return (String) get(6);
    }

    /**
     * Setter for <code>cattle.subnet.created</code>.
     */
    @Override
    public void setCreated(Date value) {
        set(7, value);
    }

    /**
     * Getter for <code>cattle.subnet.created</code>.
     */
    @Column(name = "created")
    @Override
    public Date getCreated() {
        return (Date) get(7);
    }

    /**
     * Setter for <code>cattle.subnet.removed</code>.
     */
    @Override
    public void setRemoved(Date value) {
        set(8, value);
    }

    /**
     * Getter for <code>cattle.subnet.removed</code>.
     */
    @Column(name = "removed")
    @Override
    public Date getRemoved() {
        return (Date) get(8);
    }

    /**
     * Setter for <code>cattle.subnet.remove_time</code>.
     */
    @Override
    public void setRemoveTime(Date value) {
        set(9, value);
    }

    /**
     * Getter for <code>cattle.subnet.remove_time</code>.
     */
    @Column(name = "remove_time")
    @Override
    public Date getRemoveTime() {
        return (Date) get(9);
    }

    /**
     * Setter for <code>cattle.subnet.data</code>.
     */
    @Override
    public void setData(Map<String,Object> value) {
        set(10, value);
    }

    /**
     * Getter for <code>cattle.subnet.data</code>.
     */
    @Column(name = "data", length = 16777215)
    @Override
    public Map<String,Object> getData() {
        return get(SubnetTable.SUBNET.DATA);
    }

    /**
     * Setter for <code>cattle.subnet.network_address</code>.
     */
    @Override
    public void setNetworkAddress(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>cattle.subnet.network_address</code>.
     */
    @Column(name = "network_address", length = 255)
    @Override
    public String getNetworkAddress() {
        return (String) get(11);
    }

    /**
     * Setter for <code>cattle.subnet.cidr_size</code>.
     */
    @Override
    public void setCidrSize(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>cattle.subnet.cidr_size</code>.
     */
    @Column(name = "cidr_size")
    @Override
    public Integer getCidrSize() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>cattle.subnet.start_address</code>.
     */
    @Override
    public void setStartAddress(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>cattle.subnet.start_address</code>.
     */
    @Column(name = "start_address", length = 255)
    @Override
    public String getStartAddress() {
        return (String) get(13);
    }

    /**
     * Setter for <code>cattle.subnet.end_address</code>.
     */
    @Override
    public void setEndAddress(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>cattle.subnet.end_address</code>.
     */
    @Column(name = "end_address", length = 255)
    @Override
    public String getEndAddress() {
        return (String) get(14);
    }

    /**
     * Setter for <code>cattle.subnet.gateway</code>.
     */
    @Override
    public void setGateway(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>cattle.subnet.gateway</code>.
     */
    @Column(name = "gateway", length = 255)
    @Override
    public String getGateway() {
        return (String) get(15);
    }

    /**
     * Setter for <code>cattle.subnet.network_id</code>.
     */
    @Override
    public void setNetworkId(Long value) {
        set(16, value);
    }

    /**
     * Getter for <code>cattle.subnet.network_id</code>.
     */
    @Column(name = "network_id")
    @Override
    public Long getNetworkId() {
        return (Long) get(16);
    }

    /**
     * Setter for <code>cattle.subnet.is_public</code>.
     */
    @Override
    public void setIsPublic(Boolean value) {
        set(17, value);
    }

    /**
     * Getter for <code>cattle.subnet.is_public</code>.
     */
    @Column(name = "is_public", nullable = false)
    @Override
    public Boolean getIsPublic() {
        return (Boolean) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return super.key().into(SubnetTable.SUBNET.ID);
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(Subnet from) {
        setId(from.getId());
        setName(from.getName());
        setAccountId(from.getAccountId());
        setKind(from.getKind());
        setUuid(from.getUuid());
        setDescription(from.getDescription());
        setState(from.getState());
        setCreated(from.getCreated());
        setRemoved(from.getRemoved());
        setRemoveTime(from.getRemoveTime());
        setData(from.getData());
        setNetworkAddress(from.getNetworkAddress());
        setCidrSize(from.getCidrSize());
        setStartAddress(from.getStartAddress());
        setEndAddress(from.getEndAddress());
        setGateway(from.getGateway());
        setNetworkId(from.getNetworkId());
        setIsPublic(from.getIsPublic());
        resetTouchedOnNotNull();
    }

    @Override
    public <E extends Subnet> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SubnetRecord
     */
    public SubnetRecord() {
        super(SubnetTable.SUBNET);
    }

    /**
     * Create a detached, initialised SubnetRecord
     */
    public SubnetRecord(Long id, String name, Long accountId, String kind, String uuid, String description, String state, Date created, Date removed, Date removeTime, Map<String,Object> data, String networkAddress, Integer cidrSize, String startAddress, String endAddress, String gateway, Long networkId, Boolean isPublic) {
        super(SubnetTable.SUBNET);

        setId(id);
        setName(name);
        setAccountId(accountId);
        setKind(kind);
        setUuid(uuid);
        setDescription(description);
        setState(state);
        setCreated(created);
        setRemoved(removed);
        setRemoveTime(removeTime);
        setData(data);
        setNetworkAddress(networkAddress);
        setCidrSize(cidrSize);
        setStartAddress(startAddress);
        setEndAddress(endAddress);
        setGateway(gateway);
        setNetworkId(networkId);
        setIsPublic(isPublic);
        resetTouchedOnNotNull();
    }
}
