/*
 * This file is generated by jOOQ.
 */
package io.cattle.platform.core.model.tables;


import io.cattle.platform.core.model.CattleTable;
import io.cattle.platform.core.model.Indexes;
import io.cattle.platform.core.model.Keys;
import io.cattle.platform.core.model.tables.AccountTable.AccountPath;
import io.cattle.platform.core.model.tables.records.AuditLogRecord;
import io.cattle.platform.db.jooq.converter.DataConverter;
import io.cattle.platform.db.jooq.converter.DateConverter;

import java.util.Arrays;
import java.util.Collection;
import java.util.Date;
import java.util.List;
import java.util.Map;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
public class AuditLogTable extends TableImpl<AuditLogRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>cattle.audit_log</code>
     */
    public static final AuditLogTable AUDIT_LOG = new AuditLogTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AuditLogRecord> getRecordType() {
        return AuditLogRecord.class;
    }

    /**
     * The column <code>cattle.audit_log.id</code>.
     */
    public final TableField<AuditLogRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>cattle.audit_log.account_id</code>.
     */
    public final TableField<AuditLogRecord, Long> ACCOUNT_ID = createField(DSL.name("account_id"), SQLDataType.BIGINT.defaultValue(DSL.inline("NULL", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>cattle.audit_log.authenticated_as_account_id</code>.
     */
    public final TableField<AuditLogRecord, Long> AUTHENTICATED_AS_ACCOUNT_ID = createField(DSL.name("authenticated_as_account_id"), SQLDataType.BIGINT.defaultValue(DSL.inline("NULL", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>cattle.audit_log.kind</code>.
     */
    public final TableField<AuditLogRecord, String> KIND = createField(DSL.name("kind"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>cattle.audit_log.auth_type</code>.
     */
    public final TableField<AuditLogRecord, String> AUTH_TYPE = createField(DSL.name("auth_type"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.audit_log.event_type</code>.
     */
    public final TableField<AuditLogRecord, String> EVENT_TYPE = createField(DSL.name("event_type"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>cattle.audit_log.resource_type</code>.
     */
    public final TableField<AuditLogRecord, String> RESOURCE_TYPE = createField(DSL.name("resource_type"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>cattle.audit_log.resource_id</code>.
     */
    public final TableField<AuditLogRecord, Long> RESOURCE_ID = createField(DSL.name("resource_id"), SQLDataType.BIGINT.defaultValue(DSL.inline("NULL", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>cattle.audit_log.description</code>.
     */
    public final TableField<AuditLogRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(1024).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.audit_log.created</code>.
     */
    public final TableField<AuditLogRecord, Date> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.audit_log.data</code>.
     */
    public final TableField<AuditLogRecord, Map<String,Object>> DATA = createField(DSL.name("data"), SQLDataType.CLOB(16777215).defaultValue(DSL.inline("NULL", SQLDataType.CLOB)), this, "", new DataConverter());

    /**
     * The column <code>cattle.audit_log.authenticated_as_identity_id</code>.
     */
    public final TableField<AuditLogRecord, String> AUTHENTICATED_AS_IDENTITY_ID = createField(DSL.name("authenticated_as_identity_id"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.audit_log.runtime</code>.
     */
    public final TableField<AuditLogRecord, Long> RUNTIME = createField(DSL.name("runtime"), SQLDataType.BIGINT.defaultValue(DSL.inline("NULL", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>cattle.audit_log.client_ip</code>.
     */
    public final TableField<AuditLogRecord, String> CLIENT_IP = createField(DSL.name("client_ip"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    private AuditLogTable(Name alias, Table<AuditLogRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AuditLogTable(Name alias, Table<AuditLogRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>cattle.audit_log</code> table reference
     */
    public AuditLogTable(String alias) {
        this(DSL.name(alias), AUDIT_LOG);
    }

    /**
     * Create an aliased <code>cattle.audit_log</code> table reference
     */
    public AuditLogTable(Name alias) {
        this(alias, AUDIT_LOG);
    }

    /**
     * Create a <code>cattle.audit_log</code> table reference
     */
    public AuditLogTable() {
        this(DSL.name("audit_log"), null);
    }

    public <O extends Record> AuditLogTable(Table<O> path, ForeignKey<O, AuditLogRecord> childPath, InverseForeignKey<O, AuditLogRecord> parentPath) {
        super(path, childPath, parentPath, AUDIT_LOG);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AuditLogPath extends AuditLogTable implements Path<AuditLogRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AuditLogPath(Table<O> path, ForeignKey<O, AuditLogRecord> childPath, InverseForeignKey<O, AuditLogRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AuditLogPath(Name alias, Table<AuditLogRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AuditLogPath as(String alias) {
            return new AuditLogPath(DSL.name(alias), this);
        }

        @Override
        public AuditLogPath as(Name alias) {
            return new AuditLogPath(alias, this);
        }

        @Override
        public AuditLogPath as(Table<?> alias) {
            return new AuditLogPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : CattleTable.CATTLE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.AUDIT_LOG_IDX_AUDIT_LOG_CLIENT_IP, Indexes.AUDIT_LOG_IDX_AUDIT_LOG_CREATED, Indexes.AUDIT_LOG_IDX_AUDIT_LOG_EVENT_TYPE);
    }

    @Override
    public Identity<AuditLogRecord, Long> getIdentity() {
        return Internal.createIdentity(this, ID);
    }

    @Override
    public UniqueKey<AuditLogRecord> getPrimaryKey() {
        return Keys.KEY_AUDIT_LOG_PRIMARY;
    }

    @Override
    public List<ForeignKey<AuditLogRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_AUDIT_LOG__ACCOUNT_ID, Keys.FK_AUDIT_LOG__AUTHENTICATED_AS_ACCOUNT_ID);
    }

    private transient AccountPath _fkAuditLog_AccountId;

    /**
     * Get the implicit join path to the <code>cattle.account</code> table, via
     * the <code>fk_audit_log__account_id</code> key.
     */
    public AccountPath fkAuditLog_AccountId() {
        if (_fkAuditLog_AccountId == null)
            _fkAuditLog_AccountId = new AccountPath(this, Keys.FK_AUDIT_LOG__ACCOUNT_ID, null);

        return _fkAuditLog_AccountId;
    }

    private transient AccountPath _fkAuditLog_AuthenticatedAsAccountId;

    /**
     * Get the implicit join path to the <code>cattle.account</code> table, via
     * the <code>fk_audit_log__authenticated_as_account_id</code> key.
     */
    public AccountPath fkAuditLog_AuthenticatedAsAccountId() {
        if (_fkAuditLog_AuthenticatedAsAccountId == null)
            _fkAuditLog_AuthenticatedAsAccountId = new AccountPath(this, Keys.FK_AUDIT_LOG__AUTHENTICATED_AS_ACCOUNT_ID, null);

        return _fkAuditLog_AuthenticatedAsAccountId;
    }

    @Override
    public AuditLogTable as(String alias) {
        return new AuditLogTable(DSL.name(alias), this);
    }

    @Override
    public AuditLogTable as(Name alias) {
        return new AuditLogTable(alias, this);
    }

    @Override
    public AuditLogTable as(Table<?> alias) {
        return new AuditLogTable(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AuditLogTable rename(String name) {
        return new AuditLogTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuditLogTable rename(Name name) {
        return new AuditLogTable(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuditLogTable rename(Table<?> name) {
        return new AuditLogTable(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuditLogTable where(Condition condition) {
        return new AuditLogTable(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuditLogTable where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuditLogTable where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuditLogTable where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuditLogTable where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuditLogTable where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuditLogTable where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuditLogTable where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuditLogTable whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuditLogTable whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
