/*
 * This file is generated by jOOQ.
 */
package io.cattle.platform.core.model.tables;


import io.cattle.platform.core.model.CattleTable;
import io.cattle.platform.core.model.Indexes;
import io.cattle.platform.core.model.Keys;
import io.cattle.platform.core.model.tables.AccountTable.AccountPath;
import io.cattle.platform.core.model.tables.records.CertificateRecord;
import io.cattle.platform.db.jooq.converter.DataConverter;
import io.cattle.platform.db.jooq.converter.DateConverter;

import java.util.Arrays;
import java.util.Collection;
import java.util.Date;
import java.util.List;
import java.util.Map;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
public class CertificateTable extends TableImpl<CertificateRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>cattle.certificate</code>
     */
    public static final CertificateTable CERTIFICATE = new CertificateTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CertificateRecord> getRecordType() {
        return CertificateRecord.class;
    }

    /**
     * The column <code>cattle.certificate.id</code>.
     */
    public final TableField<CertificateRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>cattle.certificate.name</code>.
     */
    public final TableField<CertificateRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.certificate.account_id</code>.
     */
    public final TableField<CertificateRecord, Long> ACCOUNT_ID = createField(DSL.name("account_id"), SQLDataType.BIGINT.defaultValue(DSL.inline("NULL", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>cattle.certificate.kind</code>.
     */
    public final TableField<CertificateRecord, String> KIND = createField(DSL.name("kind"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>cattle.certificate.uuid</code>.
     */
    public final TableField<CertificateRecord, String> UUID = createField(DSL.name("uuid"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>cattle.certificate.description</code>.
     */
    public final TableField<CertificateRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(1024).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.certificate.state</code>.
     */
    public final TableField<CertificateRecord, String> STATE = createField(DSL.name("state"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>cattle.certificate.created</code>.
     */
    public final TableField<CertificateRecord, Date> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.certificate.removed</code>.
     */
    public final TableField<CertificateRecord, Date> REMOVED = createField(DSL.name("removed"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.certificate.remove_time</code>.
     */
    public final TableField<CertificateRecord, Date> REMOVE_TIME = createField(DSL.name("remove_time"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.certificate.data</code>.
     */
    public final TableField<CertificateRecord, Map<String,Object>> DATA = createField(DSL.name("data"), SQLDataType.CLOB(16777215).defaultValue(DSL.inline("NULL", SQLDataType.CLOB)), this, "", new DataConverter());

    /**
     * The column <code>cattle.certificate.cert_chain</code>.
     */
    public final TableField<CertificateRecord, String> CERT_CHAIN = createField(DSL.name("cert_chain"), SQLDataType.CLOB(65535).defaultValue(DSL.inline("NULL", SQLDataType.CLOB)), this, "");

    /**
     * The column <code>cattle.certificate.cert</code>.
     */
    public final TableField<CertificateRecord, String> CERT = createField(DSL.name("cert"), SQLDataType.CLOB(65535).defaultValue(DSL.inline("NULL", SQLDataType.CLOB)), this, "");

    /**
     * The column <code>cattle.certificate.key</code>.
     */
    public final TableField<CertificateRecord, String> KEY = createField(DSL.name("key"), SQLDataType.CLOB(65535).defaultValue(DSL.inline("NULL", SQLDataType.CLOB)), this, "");

    private CertificateTable(Name alias, Table<CertificateRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CertificateTable(Name alias, Table<CertificateRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>cattle.certificate</code> table reference
     */
    public CertificateTable(String alias) {
        this(DSL.name(alias), CERTIFICATE);
    }

    /**
     * Create an aliased <code>cattle.certificate</code> table reference
     */
    public CertificateTable(Name alias) {
        this(alias, CERTIFICATE);
    }

    /**
     * Create a <code>cattle.certificate</code> table reference
     */
    public CertificateTable() {
        this(DSL.name("certificate"), null);
    }

    public <O extends Record> CertificateTable(Table<O> path, ForeignKey<O, CertificateRecord> childPath, InverseForeignKey<O, CertificateRecord> parentPath) {
        super(path, childPath, parentPath, CERTIFICATE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class CertificatePath extends CertificateTable implements Path<CertificateRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> CertificatePath(Table<O> path, ForeignKey<O, CertificateRecord> childPath, InverseForeignKey<O, CertificateRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private CertificatePath(Name alias, Table<CertificateRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public CertificatePath as(String alias) {
            return new CertificatePath(DSL.name(alias), this);
        }

        @Override
        public CertificatePath as(Name alias) {
            return new CertificatePath(alias, this);
        }

        @Override
        public CertificatePath as(Table<?> alias) {
            return new CertificatePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : CattleTable.CATTLE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.CERTIFICATE_IDX_CERT_DATA_NAME, Indexes.CERTIFICATE_IDX_CERT_DATA_REMOVE_TIME, Indexes.CERTIFICATE_IDX_CERT_DATA_REMOVED, Indexes.CERTIFICATE_IDX_CERT_DATA_STATE);
    }

    @Override
    public Identity<CertificateRecord, Long> getIdentity() {
        return Internal.createIdentity(this, ID);
    }

    @Override
    public UniqueKey<CertificateRecord> getPrimaryKey() {
        return Keys.KEY_CERTIFICATE_PRIMARY;
    }

    @Override
    public List<UniqueKey<CertificateRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_CERTIFICATE_IDX_CERT_DATA_UUID);
    }

    @Override
    public List<ForeignKey<CertificateRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_CERT_DATA__ACCOUNT_ID);
    }

    private transient AccountPath _account;

    /**
     * Get the implicit join path to the <code>cattle.account</code> table.
     */
    public AccountPath account() {
        if (_account == null)
            _account = new AccountPath(this, Keys.FK_CERT_DATA__ACCOUNT_ID, null);

        return _account;
    }

    @Override
    public CertificateTable as(String alias) {
        return new CertificateTable(DSL.name(alias), this);
    }

    @Override
    public CertificateTable as(Name alias) {
        return new CertificateTable(alias, this);
    }

    @Override
    public CertificateTable as(Table<?> alias) {
        return new CertificateTable(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CertificateTable rename(String name) {
        return new CertificateTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CertificateTable rename(Name name) {
        return new CertificateTable(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CertificateTable rename(Table<?> name) {
        return new CertificateTable(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CertificateTable where(Condition condition) {
        return new CertificateTable(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CertificateTable where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CertificateTable where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CertificateTable where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CertificateTable where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CertificateTable where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CertificateTable where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CertificateTable where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CertificateTable whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CertificateTable whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
