/*
 * This file is generated by jOOQ.
 */
package io.cattle.platform.core.model.tables;


import io.cattle.platform.core.model.CattleTable;
import io.cattle.platform.core.model.Indexes;
import io.cattle.platform.core.model.Keys;
import io.cattle.platform.core.model.tables.HostTable.HostPath;
import io.cattle.platform.core.model.tables.records.ClusterHostMapRecord;
import io.cattle.platform.db.jooq.converter.DataConverter;
import io.cattle.platform.db.jooq.converter.DateConverter;

import java.util.Arrays;
import java.util.Collection;
import java.util.Date;
import java.util.List;
import java.util.Map;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
public class ClusterHostMapTable extends TableImpl<ClusterHostMapRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>cattle.cluster_host_map</code>
     */
    public static final ClusterHostMapTable CLUSTER_HOST_MAP = new ClusterHostMapTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ClusterHostMapRecord> getRecordType() {
        return ClusterHostMapRecord.class;
    }

    /**
     * The column <code>cattle.cluster_host_map.id</code>.
     */
    public final TableField<ClusterHostMapRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>cattle.cluster_host_map.name</code>.
     */
    public final TableField<ClusterHostMapRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.cluster_host_map.kind</code>.
     */
    public final TableField<ClusterHostMapRecord, String> KIND = createField(DSL.name("kind"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>cattle.cluster_host_map.uuid</code>.
     */
    public final TableField<ClusterHostMapRecord, String> UUID = createField(DSL.name("uuid"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>cattle.cluster_host_map.description</code>.
     */
    public final TableField<ClusterHostMapRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(1024).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.cluster_host_map.state</code>.
     */
    public final TableField<ClusterHostMapRecord, String> STATE = createField(DSL.name("state"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>cattle.cluster_host_map.created</code>.
     */
    public final TableField<ClusterHostMapRecord, Date> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.cluster_host_map.removed</code>.
     */
    public final TableField<ClusterHostMapRecord, Date> REMOVED = createField(DSL.name("removed"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.cluster_host_map.remove_time</code>.
     */
    public final TableField<ClusterHostMapRecord, Date> REMOVE_TIME = createField(DSL.name("remove_time"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.cluster_host_map.data</code>.
     */
    public final TableField<ClusterHostMapRecord, Map<String,Object>> DATA = createField(DSL.name("data"), SQLDataType.CLOB(16777215).defaultValue(DSL.inline("NULL", SQLDataType.CLOB)), this, "", new DataConverter());

    /**
     * The column <code>cattle.cluster_host_map.cluster_id</code>.
     */
    public final TableField<ClusterHostMapRecord, Long> CLUSTER_ID = createField(DSL.name("cluster_id"), SQLDataType.BIGINT.defaultValue(DSL.inline("NULL", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>cattle.cluster_host_map.host_id</code>.
     */
    public final TableField<ClusterHostMapRecord, Long> HOST_ID = createField(DSL.name("host_id"), SQLDataType.BIGINT.defaultValue(DSL.inline("NULL", SQLDataType.BIGINT)), this, "");

    private ClusterHostMapTable(Name alias, Table<ClusterHostMapRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ClusterHostMapTable(Name alias, Table<ClusterHostMapRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>cattle.cluster_host_map</code> table reference
     */
    public ClusterHostMapTable(String alias) {
        this(DSL.name(alias), CLUSTER_HOST_MAP);
    }

    /**
     * Create an aliased <code>cattle.cluster_host_map</code> table reference
     */
    public ClusterHostMapTable(Name alias) {
        this(alias, CLUSTER_HOST_MAP);
    }

    /**
     * Create a <code>cattle.cluster_host_map</code> table reference
     */
    public ClusterHostMapTable() {
        this(DSL.name("cluster_host_map"), null);
    }

    public <O extends Record> ClusterHostMapTable(Table<O> path, ForeignKey<O, ClusterHostMapRecord> childPath, InverseForeignKey<O, ClusterHostMapRecord> parentPath) {
        super(path, childPath, parentPath, CLUSTER_HOST_MAP);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ClusterHostMapPath extends ClusterHostMapTable implements Path<ClusterHostMapRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ClusterHostMapPath(Table<O> path, ForeignKey<O, ClusterHostMapRecord> childPath, InverseForeignKey<O, ClusterHostMapRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ClusterHostMapPath(Name alias, Table<ClusterHostMapRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ClusterHostMapPath as(String alias) {
            return new ClusterHostMapPath(DSL.name(alias), this);
        }

        @Override
        public ClusterHostMapPath as(Name alias) {
            return new ClusterHostMapPath(alias, this);
        }

        @Override
        public ClusterHostMapPath as(Table<?> alias) {
            return new ClusterHostMapPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : CattleTable.CATTLE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.CLUSTER_HOST_MAP_IDX_CLUSTER_HOST_MAP_NAME, Indexes.CLUSTER_HOST_MAP_IDX_CLUSTER_HOST_MAP_REMOVE_TIME, Indexes.CLUSTER_HOST_MAP_IDX_CLUSTER_HOST_MAP_REMOVED, Indexes.CLUSTER_HOST_MAP_IDX_CLUSTER_HOST_MAP_STATE);
    }

    @Override
    public Identity<ClusterHostMapRecord, Long> getIdentity() {
        return Internal.createIdentity(this, ID);
    }

    @Override
    public UniqueKey<ClusterHostMapRecord> getPrimaryKey() {
        return Keys.KEY_CLUSTER_HOST_MAP_PRIMARY;
    }

    @Override
    public List<UniqueKey<ClusterHostMapRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_CLUSTER_HOST_MAP_IDX_CLUSTER_HOST_MAP_UUID);
    }

    @Override
    public List<ForeignKey<ClusterHostMapRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_CLUSTER_HOST_MAP__HOST_ID, Keys.FK_HOST_HOST_MAP__HOST_ID);
    }

    private transient HostPath _fkClusterHostMap_HostId;

    /**
     * Get the implicit join path to the <code>cattle.host</code> table, via the
     * <code>fk_cluster_host_map__host_id</code> key.
     */
    public HostPath fkClusterHostMap_HostId() {
        if (_fkClusterHostMap_HostId == null)
            _fkClusterHostMap_HostId = new HostPath(this, Keys.FK_CLUSTER_HOST_MAP__HOST_ID, null);

        return _fkClusterHostMap_HostId;
    }

    private transient HostPath _fkHostHostMap_HostId;

    /**
     * Get the implicit join path to the <code>cattle.host</code> table, via the
     * <code>fk_host_host_map__host_id</code> key.
     */
    public HostPath fkHostHostMap_HostId() {
        if (_fkHostHostMap_HostId == null)
            _fkHostHostMap_HostId = new HostPath(this, Keys.FK_HOST_HOST_MAP__HOST_ID, null);

        return _fkHostHostMap_HostId;
    }

    @Override
    public ClusterHostMapTable as(String alias) {
        return new ClusterHostMapTable(DSL.name(alias), this);
    }

    @Override
    public ClusterHostMapTable as(Name alias) {
        return new ClusterHostMapTable(alias, this);
    }

    @Override
    public ClusterHostMapTable as(Table<?> alias) {
        return new ClusterHostMapTable(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ClusterHostMapTable rename(String name) {
        return new ClusterHostMapTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ClusterHostMapTable rename(Name name) {
        return new ClusterHostMapTable(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ClusterHostMapTable rename(Table<?> name) {
        return new ClusterHostMapTable(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClusterHostMapTable where(Condition condition) {
        return new ClusterHostMapTable(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClusterHostMapTable where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClusterHostMapTable where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClusterHostMapTable where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClusterHostMapTable where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClusterHostMapTable where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClusterHostMapTable where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClusterHostMapTable where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClusterHostMapTable whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClusterHostMapTable whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
