/*
 * This file is generated by jOOQ.
 */
package io.cattle.platform.core.model.tables;


import io.cattle.platform.core.model.CattleTable;
import io.cattle.platform.core.model.Indexes;
import io.cattle.platform.core.model.Keys;
import io.cattle.platform.core.model.tables.CredentialTable.CredentialPath;
import io.cattle.platform.core.model.tables.InstanceTable.InstancePath;
import io.cattle.platform.core.model.tables.records.CredentialInstanceMapRecord;
import io.cattle.platform.db.jooq.converter.DataConverter;
import io.cattle.platform.db.jooq.converter.DateConverter;

import java.util.Arrays;
import java.util.Collection;
import java.util.Date;
import java.util.List;
import java.util.Map;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
public class CredentialInstanceMapTable extends TableImpl<CredentialInstanceMapRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>cattle.credential_instance_map</code>
     */
    public static final CredentialInstanceMapTable CREDENTIAL_INSTANCE_MAP = new CredentialInstanceMapTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CredentialInstanceMapRecord> getRecordType() {
        return CredentialInstanceMapRecord.class;
    }

    /**
     * The column <code>cattle.credential_instance_map.id</code>.
     */
    public final TableField<CredentialInstanceMapRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>cattle.credential_instance_map.name</code>.
     */
    public final TableField<CredentialInstanceMapRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.credential_instance_map.kind</code>.
     */
    public final TableField<CredentialInstanceMapRecord, String> KIND = createField(DSL.name("kind"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>cattle.credential_instance_map.uuid</code>.
     */
    public final TableField<CredentialInstanceMapRecord, String> UUID = createField(DSL.name("uuid"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>cattle.credential_instance_map.description</code>.
     */
    public final TableField<CredentialInstanceMapRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(1024).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.credential_instance_map.state</code>.
     */
    public final TableField<CredentialInstanceMapRecord, String> STATE = createField(DSL.name("state"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>cattle.credential_instance_map.created</code>.
     */
    public final TableField<CredentialInstanceMapRecord, Date> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.credential_instance_map.removed</code>.
     */
    public final TableField<CredentialInstanceMapRecord, Date> REMOVED = createField(DSL.name("removed"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.credential_instance_map.remove_time</code>.
     */
    public final TableField<CredentialInstanceMapRecord, Date> REMOVE_TIME = createField(DSL.name("remove_time"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.credential_instance_map.data</code>.
     */
    public final TableField<CredentialInstanceMapRecord, Map<String,Object>> DATA = createField(DSL.name("data"), SQLDataType.CLOB(16777215).defaultValue(DSL.inline("NULL", SQLDataType.CLOB)), this, "", new DataConverter());

    /**
     * The column <code>cattle.credential_instance_map.credential_id</code>.
     */
    public final TableField<CredentialInstanceMapRecord, Long> CREDENTIAL_ID = createField(DSL.name("credential_id"), SQLDataType.BIGINT.defaultValue(DSL.inline("NULL", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>cattle.credential_instance_map.instance_id</code>.
     */
    public final TableField<CredentialInstanceMapRecord, Long> INSTANCE_ID = createField(DSL.name("instance_id"), SQLDataType.BIGINT.defaultValue(DSL.inline("NULL", SQLDataType.BIGINT)), this, "");

    private CredentialInstanceMapTable(Name alias, Table<CredentialInstanceMapRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CredentialInstanceMapTable(Name alias, Table<CredentialInstanceMapRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>cattle.credential_instance_map</code> table
     * reference
     */
    public CredentialInstanceMapTable(String alias) {
        this(DSL.name(alias), CREDENTIAL_INSTANCE_MAP);
    }

    /**
     * Create an aliased <code>cattle.credential_instance_map</code> table
     * reference
     */
    public CredentialInstanceMapTable(Name alias) {
        this(alias, CREDENTIAL_INSTANCE_MAP);
    }

    /**
     * Create a <code>cattle.credential_instance_map</code> table reference
     */
    public CredentialInstanceMapTable() {
        this(DSL.name("credential_instance_map"), null);
    }

    public <O extends Record> CredentialInstanceMapTable(Table<O> path, ForeignKey<O, CredentialInstanceMapRecord> childPath, InverseForeignKey<O, CredentialInstanceMapRecord> parentPath) {
        super(path, childPath, parentPath, CREDENTIAL_INSTANCE_MAP);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class CredentialInstanceMapPath extends CredentialInstanceMapTable implements Path<CredentialInstanceMapRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> CredentialInstanceMapPath(Table<O> path, ForeignKey<O, CredentialInstanceMapRecord> childPath, InverseForeignKey<O, CredentialInstanceMapRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private CredentialInstanceMapPath(Name alias, Table<CredentialInstanceMapRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public CredentialInstanceMapPath as(String alias) {
            return new CredentialInstanceMapPath(DSL.name(alias), this);
        }

        @Override
        public CredentialInstanceMapPath as(Name alias) {
            return new CredentialInstanceMapPath(alias, this);
        }

        @Override
        public CredentialInstanceMapPath as(Table<?> alias) {
            return new CredentialInstanceMapPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : CattleTable.CATTLE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.CREDENTIAL_INSTANCE_MAP_IDX_CREDENTIAL_INSTANCE_MAP_NAME, Indexes.CREDENTIAL_INSTANCE_MAP_IDX_CREDENTIAL_INSTANCE_MAP_REMOVE_TIME, Indexes.CREDENTIAL_INSTANCE_MAP_IDX_CREDENTIAL_INSTANCE_MAP_REMOVED, Indexes.CREDENTIAL_INSTANCE_MAP_IDX_CREDENTIAL_INSTANCE_MAP_STATE);
    }

    @Override
    public Identity<CredentialInstanceMapRecord, Long> getIdentity() {
        return Internal.createIdentity(this, ID);
    }

    @Override
    public UniqueKey<CredentialInstanceMapRecord> getPrimaryKey() {
        return Keys.KEY_CREDENTIAL_INSTANCE_MAP_PRIMARY;
    }

    @Override
    public List<UniqueKey<CredentialInstanceMapRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_CREDENTIAL_INSTANCE_MAP_IDX_CREDENTIAL_INSTANCE_MAP_UUID);
    }

    @Override
    public List<ForeignKey<CredentialInstanceMapRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_CREDENTIAL_INSTANCE_MAP__CREDENTIAL_ID, Keys.FK_CREDENTIAL_INSTANCE_MAP__INSTANCE_ID);
    }

    private transient CredentialPath _credential;

    /**
     * Get the implicit join path to the <code>cattle.credential</code> table.
     */
    public CredentialPath credential() {
        if (_credential == null)
            _credential = new CredentialPath(this, Keys.FK_CREDENTIAL_INSTANCE_MAP__CREDENTIAL_ID, null);

        return _credential;
    }

    private transient InstancePath _instance;

    /**
     * Get the implicit join path to the <code>cattle.instance</code> table.
     */
    public InstancePath instance() {
        if (_instance == null)
            _instance = new InstancePath(this, Keys.FK_CREDENTIAL_INSTANCE_MAP__INSTANCE_ID, null);

        return _instance;
    }

    @Override
    public CredentialInstanceMapTable as(String alias) {
        return new CredentialInstanceMapTable(DSL.name(alias), this);
    }

    @Override
    public CredentialInstanceMapTable as(Name alias) {
        return new CredentialInstanceMapTable(alias, this);
    }

    @Override
    public CredentialInstanceMapTable as(Table<?> alias) {
        return new CredentialInstanceMapTable(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CredentialInstanceMapTable rename(String name) {
        return new CredentialInstanceMapTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CredentialInstanceMapTable rename(Name name) {
        return new CredentialInstanceMapTable(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CredentialInstanceMapTable rename(Table<?> name) {
        return new CredentialInstanceMapTable(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CredentialInstanceMapTable where(Condition condition) {
        return new CredentialInstanceMapTable(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CredentialInstanceMapTable where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CredentialInstanceMapTable where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CredentialInstanceMapTable where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CredentialInstanceMapTable where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CredentialInstanceMapTable where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CredentialInstanceMapTable where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CredentialInstanceMapTable where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CredentialInstanceMapTable whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CredentialInstanceMapTable whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
