/*
 * This file is generated by jOOQ.
 */
package io.cattle.platform.core.model.tables;


import io.cattle.platform.core.model.CattleTable;
import io.cattle.platform.core.model.Indexes;
import io.cattle.platform.core.model.Keys;
import io.cattle.platform.core.model.tables.HostTable.HostPath;
import io.cattle.platform.core.model.tables.IpAddressTable.IpAddressPath;
import io.cattle.platform.core.model.tables.records.HostIpAddressMapRecord;
import io.cattle.platform.db.jooq.converter.DataConverter;
import io.cattle.platform.db.jooq.converter.DateConverter;

import java.util.Arrays;
import java.util.Collection;
import java.util.Date;
import java.util.List;
import java.util.Map;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
public class HostIpAddressMapTable extends TableImpl<HostIpAddressMapRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>cattle.host_ip_address_map</code>
     */
    public static final HostIpAddressMapTable HOST_IP_ADDRESS_MAP = new HostIpAddressMapTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<HostIpAddressMapRecord> getRecordType() {
        return HostIpAddressMapRecord.class;
    }

    /**
     * The column <code>cattle.host_ip_address_map.id</code>.
     */
    public final TableField<HostIpAddressMapRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>cattle.host_ip_address_map.name</code>.
     */
    public final TableField<HostIpAddressMapRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.host_ip_address_map.kind</code>.
     */
    public final TableField<HostIpAddressMapRecord, String> KIND = createField(DSL.name("kind"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>cattle.host_ip_address_map.uuid</code>.
     */
    public final TableField<HostIpAddressMapRecord, String> UUID = createField(DSL.name("uuid"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>cattle.host_ip_address_map.description</code>.
     */
    public final TableField<HostIpAddressMapRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(1024).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.host_ip_address_map.state</code>.
     */
    public final TableField<HostIpAddressMapRecord, String> STATE = createField(DSL.name("state"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>cattle.host_ip_address_map.created</code>.
     */
    public final TableField<HostIpAddressMapRecord, Date> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.host_ip_address_map.removed</code>.
     */
    public final TableField<HostIpAddressMapRecord, Date> REMOVED = createField(DSL.name("removed"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.host_ip_address_map.remove_time</code>.
     */
    public final TableField<HostIpAddressMapRecord, Date> REMOVE_TIME = createField(DSL.name("remove_time"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.host_ip_address_map.data</code>.
     */
    public final TableField<HostIpAddressMapRecord, Map<String,Object>> DATA = createField(DSL.name("data"), SQLDataType.CLOB(16777215).defaultValue(DSL.inline("NULL", SQLDataType.CLOB)), this, "", new DataConverter());

    /**
     * The column <code>cattle.host_ip_address_map.host_id</code>.
     */
    public final TableField<HostIpAddressMapRecord, Long> HOST_ID = createField(DSL.name("host_id"), SQLDataType.BIGINT.defaultValue(DSL.inline("NULL", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>cattle.host_ip_address_map.ip_address_id</code>.
     */
    public final TableField<HostIpAddressMapRecord, Long> IP_ADDRESS_ID = createField(DSL.name("ip_address_id"), SQLDataType.BIGINT.defaultValue(DSL.inline("NULL", SQLDataType.BIGINT)), this, "");

    private HostIpAddressMapTable(Name alias, Table<HostIpAddressMapRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private HostIpAddressMapTable(Name alias, Table<HostIpAddressMapRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>cattle.host_ip_address_map</code> table reference
     */
    public HostIpAddressMapTable(String alias) {
        this(DSL.name(alias), HOST_IP_ADDRESS_MAP);
    }

    /**
     * Create an aliased <code>cattle.host_ip_address_map</code> table reference
     */
    public HostIpAddressMapTable(Name alias) {
        this(alias, HOST_IP_ADDRESS_MAP);
    }

    /**
     * Create a <code>cattle.host_ip_address_map</code> table reference
     */
    public HostIpAddressMapTable() {
        this(DSL.name("host_ip_address_map"), null);
    }

    public <O extends Record> HostIpAddressMapTable(Table<O> path, ForeignKey<O, HostIpAddressMapRecord> childPath, InverseForeignKey<O, HostIpAddressMapRecord> parentPath) {
        super(path, childPath, parentPath, HOST_IP_ADDRESS_MAP);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class HostIpAddressMapPath extends HostIpAddressMapTable implements Path<HostIpAddressMapRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> HostIpAddressMapPath(Table<O> path, ForeignKey<O, HostIpAddressMapRecord> childPath, InverseForeignKey<O, HostIpAddressMapRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private HostIpAddressMapPath(Name alias, Table<HostIpAddressMapRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public HostIpAddressMapPath as(String alias) {
            return new HostIpAddressMapPath(DSL.name(alias), this);
        }

        @Override
        public HostIpAddressMapPath as(Name alias) {
            return new HostIpAddressMapPath(alias, this);
        }

        @Override
        public HostIpAddressMapPath as(Table<?> alias) {
            return new HostIpAddressMapPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : CattleTable.CATTLE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.HOST_IP_ADDRESS_MAP_IDX_HOST_IP_ADDRESS_MAP_NAME, Indexes.HOST_IP_ADDRESS_MAP_IDX_HOST_IP_ADDRESS_MAP_REMOVE_TIME, Indexes.HOST_IP_ADDRESS_MAP_IDX_HOST_IP_ADDRESS_MAP_REMOVED, Indexes.HOST_IP_ADDRESS_MAP_IDX_HOST_IP_ADDRESS_MAP_STATE);
    }

    @Override
    public Identity<HostIpAddressMapRecord, Long> getIdentity() {
        return Internal.createIdentity(this, ID);
    }

    @Override
    public UniqueKey<HostIpAddressMapRecord> getPrimaryKey() {
        return Keys.KEY_HOST_IP_ADDRESS_MAP_PRIMARY;
    }

    @Override
    public List<UniqueKey<HostIpAddressMapRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_HOST_IP_ADDRESS_MAP_IDX_HOST_IP_ADDRESS_MAP_UUID);
    }

    @Override
    public List<ForeignKey<HostIpAddressMapRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_HOST_IP_ADDRESS_MAP__HOST_ID, Keys.FK_HOST_IP_ADDRESS_MAP__IP_ADDRESS_ID);
    }

    private transient HostPath _host;

    /**
     * Get the implicit join path to the <code>cattle.host</code> table.
     */
    public HostPath host() {
        if (_host == null)
            _host = new HostPath(this, Keys.FK_HOST_IP_ADDRESS_MAP__HOST_ID, null);

        return _host;
    }

    private transient IpAddressPath _ipAddress;

    /**
     * Get the implicit join path to the <code>cattle.ip_address</code> table.
     */
    public IpAddressPath ipAddress() {
        if (_ipAddress == null)
            _ipAddress = new IpAddressPath(this, Keys.FK_HOST_IP_ADDRESS_MAP__IP_ADDRESS_ID, null);

        return _ipAddress;
    }

    @Override
    public HostIpAddressMapTable as(String alias) {
        return new HostIpAddressMapTable(DSL.name(alias), this);
    }

    @Override
    public HostIpAddressMapTable as(Name alias) {
        return new HostIpAddressMapTable(alias, this);
    }

    @Override
    public HostIpAddressMapTable as(Table<?> alias) {
        return new HostIpAddressMapTable(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public HostIpAddressMapTable rename(String name) {
        return new HostIpAddressMapTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public HostIpAddressMapTable rename(Name name) {
        return new HostIpAddressMapTable(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public HostIpAddressMapTable rename(Table<?> name) {
        return new HostIpAddressMapTable(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HostIpAddressMapTable where(Condition condition) {
        return new HostIpAddressMapTable(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HostIpAddressMapTable where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HostIpAddressMapTable where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HostIpAddressMapTable where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HostIpAddressMapTable where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HostIpAddressMapTable where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HostIpAddressMapTable where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HostIpAddressMapTable where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HostIpAddressMapTable whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HostIpAddressMapTable whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
