/*
 * This file is generated by jOOQ.
 */
package io.cattle.platform.core.model.tables;


import io.cattle.platform.core.model.CattleTable;
import io.cattle.platform.core.model.Indexes;
import io.cattle.platform.core.model.Keys;
import io.cattle.platform.core.model.tables.AccountTable.AccountPath;
import io.cattle.platform.core.model.tables.HostTable.HostPath;
import io.cattle.platform.core.model.tables.LabelTable.LabelPath;
import io.cattle.platform.core.model.tables.records.HostLabelMapRecord;
import io.cattle.platform.db.jooq.converter.DataConverter;
import io.cattle.platform.db.jooq.converter.DateConverter;

import java.util.Arrays;
import java.util.Collection;
import java.util.Date;
import java.util.List;
import java.util.Map;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
public class HostLabelMapTable extends TableImpl<HostLabelMapRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>cattle.host_label_map</code>
     */
    public static final HostLabelMapTable HOST_LABEL_MAP = new HostLabelMapTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<HostLabelMapRecord> getRecordType() {
        return HostLabelMapRecord.class;
    }

    /**
     * The column <code>cattle.host_label_map.id</code>.
     */
    public final TableField<HostLabelMapRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>cattle.host_label_map.name</code>.
     */
    public final TableField<HostLabelMapRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.host_label_map.account_id</code>.
     */
    public final TableField<HostLabelMapRecord, Long> ACCOUNT_ID = createField(DSL.name("account_id"), SQLDataType.BIGINT.defaultValue(DSL.inline("NULL", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>cattle.host_label_map.kind</code>.
     */
    public final TableField<HostLabelMapRecord, String> KIND = createField(DSL.name("kind"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>cattle.host_label_map.uuid</code>.
     */
    public final TableField<HostLabelMapRecord, String> UUID = createField(DSL.name("uuid"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>cattle.host_label_map.description</code>.
     */
    public final TableField<HostLabelMapRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(1024).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.host_label_map.state</code>.
     */
    public final TableField<HostLabelMapRecord, String> STATE = createField(DSL.name("state"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>cattle.host_label_map.created</code>.
     */
    public final TableField<HostLabelMapRecord, Date> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.host_label_map.removed</code>.
     */
    public final TableField<HostLabelMapRecord, Date> REMOVED = createField(DSL.name("removed"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.host_label_map.remove_time</code>.
     */
    public final TableField<HostLabelMapRecord, Date> REMOVE_TIME = createField(DSL.name("remove_time"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.host_label_map.data</code>.
     */
    public final TableField<HostLabelMapRecord, Map<String,Object>> DATA = createField(DSL.name("data"), SQLDataType.CLOB(16777215).defaultValue(DSL.inline("NULL", SQLDataType.CLOB)), this, "", new DataConverter());

    /**
     * The column <code>cattle.host_label_map.host_id</code>.
     */
    public final TableField<HostLabelMapRecord, Long> HOST_ID = createField(DSL.name("host_id"), SQLDataType.BIGINT.defaultValue(DSL.inline("NULL", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>cattle.host_label_map.label_id</code>.
     */
    public final TableField<HostLabelMapRecord, Long> LABEL_ID = createField(DSL.name("label_id"), SQLDataType.BIGINT.defaultValue(DSL.inline("NULL", SQLDataType.BIGINT)), this, "");

    private HostLabelMapTable(Name alias, Table<HostLabelMapRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private HostLabelMapTable(Name alias, Table<HostLabelMapRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>cattle.host_label_map</code> table reference
     */
    public HostLabelMapTable(String alias) {
        this(DSL.name(alias), HOST_LABEL_MAP);
    }

    /**
     * Create an aliased <code>cattle.host_label_map</code> table reference
     */
    public HostLabelMapTable(Name alias) {
        this(alias, HOST_LABEL_MAP);
    }

    /**
     * Create a <code>cattle.host_label_map</code> table reference
     */
    public HostLabelMapTable() {
        this(DSL.name("host_label_map"), null);
    }

    public <O extends Record> HostLabelMapTable(Table<O> path, ForeignKey<O, HostLabelMapRecord> childPath, InverseForeignKey<O, HostLabelMapRecord> parentPath) {
        super(path, childPath, parentPath, HOST_LABEL_MAP);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class HostLabelMapPath extends HostLabelMapTable implements Path<HostLabelMapRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> HostLabelMapPath(Table<O> path, ForeignKey<O, HostLabelMapRecord> childPath, InverseForeignKey<O, HostLabelMapRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private HostLabelMapPath(Name alias, Table<HostLabelMapRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public HostLabelMapPath as(String alias) {
            return new HostLabelMapPath(DSL.name(alias), this);
        }

        @Override
        public HostLabelMapPath as(Name alias) {
            return new HostLabelMapPath(alias, this);
        }

        @Override
        public HostLabelMapPath as(Table<?> alias) {
            return new HostLabelMapPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : CattleTable.CATTLE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.HOST_LABEL_MAP_IDX_HOST_LABEL_MAP_NAME, Indexes.HOST_LABEL_MAP_IDX_HOST_LABEL_MAP_REMOVE_TIME, Indexes.HOST_LABEL_MAP_IDX_HOST_LABEL_MAP_REMOVED, Indexes.HOST_LABEL_MAP_IDX_HOST_LABEL_MAP_STATE);
    }

    @Override
    public Identity<HostLabelMapRecord, Long> getIdentity() {
        return Internal.createIdentity(this, ID);
    }

    @Override
    public UniqueKey<HostLabelMapRecord> getPrimaryKey() {
        return Keys.KEY_HOST_LABEL_MAP_PRIMARY;
    }

    @Override
    public List<UniqueKey<HostLabelMapRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_HOST_LABEL_MAP_IDX_HOST_LABEL_MAP_UUID);
    }

    @Override
    public List<ForeignKey<HostLabelMapRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_HOST_LABEL_MAP__ACCOUNT_ID, Keys.FK_HOST_LABEL_MAP__HOST_ID, Keys.FK_HOST_LABEL_MAP__LABEL_ID);
    }

    private transient AccountPath _account;

    /**
     * Get the implicit join path to the <code>cattle.account</code> table.
     */
    public AccountPath account() {
        if (_account == null)
            _account = new AccountPath(this, Keys.FK_HOST_LABEL_MAP__ACCOUNT_ID, null);

        return _account;
    }

    private transient HostPath _host;

    /**
     * Get the implicit join path to the <code>cattle.host</code> table.
     */
    public HostPath host() {
        if (_host == null)
            _host = new HostPath(this, Keys.FK_HOST_LABEL_MAP__HOST_ID, null);

        return _host;
    }

    private transient LabelPath _label;

    /**
     * Get the implicit join path to the <code>cattle.label</code> table.
     */
    public LabelPath label() {
        if (_label == null)
            _label = new LabelPath(this, Keys.FK_HOST_LABEL_MAP__LABEL_ID, null);

        return _label;
    }

    @Override
    public HostLabelMapTable as(String alias) {
        return new HostLabelMapTable(DSL.name(alias), this);
    }

    @Override
    public HostLabelMapTable as(Name alias) {
        return new HostLabelMapTable(alias, this);
    }

    @Override
    public HostLabelMapTable as(Table<?> alias) {
        return new HostLabelMapTable(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public HostLabelMapTable rename(String name) {
        return new HostLabelMapTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public HostLabelMapTable rename(Name name) {
        return new HostLabelMapTable(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public HostLabelMapTable rename(Table<?> name) {
        return new HostLabelMapTable(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HostLabelMapTable where(Condition condition) {
        return new HostLabelMapTable(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HostLabelMapTable where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HostLabelMapTable where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HostLabelMapTable where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HostLabelMapTable where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HostLabelMapTable where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HostLabelMapTable where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HostLabelMapTable where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HostLabelMapTable whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HostLabelMapTable whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
