/*
 * This file is generated by jOOQ.
 */
package io.cattle.platform.core.model.tables;


import io.cattle.platform.core.model.CattleTable;
import io.cattle.platform.core.model.Indexes;
import io.cattle.platform.core.model.Keys;
import io.cattle.platform.core.model.tables.AccountTable.AccountPath;
import io.cattle.platform.core.model.tables.HostTable.HostPath;
import io.cattle.platform.core.model.tables.records.HostTemplateRecord;
import io.cattle.platform.db.jooq.converter.DataConverter;
import io.cattle.platform.db.jooq.converter.DateConverter;

import java.util.Arrays;
import java.util.Collection;
import java.util.Date;
import java.util.List;
import java.util.Map;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
public class HostTemplateTable extends TableImpl<HostTemplateRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>cattle.host_template</code>
     */
    public static final HostTemplateTable HOST_TEMPLATE = new HostTemplateTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<HostTemplateRecord> getRecordType() {
        return HostTemplateRecord.class;
    }

    /**
     * The column <code>cattle.host_template.id</code>.
     */
    public final TableField<HostTemplateRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>cattle.host_template.name</code>.
     */
    public final TableField<HostTemplateRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.host_template.account_id</code>.
     */
    public final TableField<HostTemplateRecord, Long> ACCOUNT_ID = createField(DSL.name("account_id"), SQLDataType.BIGINT.defaultValue(DSL.inline("NULL", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>cattle.host_template.kind</code>.
     */
    public final TableField<HostTemplateRecord, String> KIND = createField(DSL.name("kind"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>cattle.host_template.uuid</code>.
     */
    public final TableField<HostTemplateRecord, String> UUID = createField(DSL.name("uuid"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>cattle.host_template.description</code>.
     */
    public final TableField<HostTemplateRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(1024).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.host_template.state</code>.
     */
    public final TableField<HostTemplateRecord, String> STATE = createField(DSL.name("state"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>cattle.host_template.created</code>.
     */
    public final TableField<HostTemplateRecord, Date> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.host_template.removed</code>.
     */
    public final TableField<HostTemplateRecord, Date> REMOVED = createField(DSL.name("removed"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.host_template.remove_time</code>.
     */
    public final TableField<HostTemplateRecord, Date> REMOVE_TIME = createField(DSL.name("remove_time"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.host_template.data</code>.
     */
    public final TableField<HostTemplateRecord, Map<String,Object>> DATA = createField(DSL.name("data"), SQLDataType.CLOB(16777215).defaultValue(DSL.inline("NULL", SQLDataType.CLOB)), this, "", new DataConverter());

    /**
     * The column <code>cattle.host_template.driver</code>.
     */
    public final TableField<HostTemplateRecord, String> DRIVER = createField(DSL.name("driver"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.host_template.flavor_prefix</code>.
     */
    public final TableField<HostTemplateRecord, String> FLAVOR_PREFIX = createField(DSL.name("flavor_prefix"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    private HostTemplateTable(Name alias, Table<HostTemplateRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private HostTemplateTable(Name alias, Table<HostTemplateRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>cattle.host_template</code> table reference
     */
    public HostTemplateTable(String alias) {
        this(DSL.name(alias), HOST_TEMPLATE);
    }

    /**
     * Create an aliased <code>cattle.host_template</code> table reference
     */
    public HostTemplateTable(Name alias) {
        this(alias, HOST_TEMPLATE);
    }

    /**
     * Create a <code>cattle.host_template</code> table reference
     */
    public HostTemplateTable() {
        this(DSL.name("host_template"), null);
    }

    public <O extends Record> HostTemplateTable(Table<O> path, ForeignKey<O, HostTemplateRecord> childPath, InverseForeignKey<O, HostTemplateRecord> parentPath) {
        super(path, childPath, parentPath, HOST_TEMPLATE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class HostTemplatePath extends HostTemplateTable implements Path<HostTemplateRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> HostTemplatePath(Table<O> path, ForeignKey<O, HostTemplateRecord> childPath, InverseForeignKey<O, HostTemplateRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private HostTemplatePath(Name alias, Table<HostTemplateRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public HostTemplatePath as(String alias) {
            return new HostTemplatePath(DSL.name(alias), this);
        }

        @Override
        public HostTemplatePath as(Name alias) {
            return new HostTemplatePath(alias, this);
        }

        @Override
        public HostTemplatePath as(Table<?> alias) {
            return new HostTemplatePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : CattleTable.CATTLE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.HOST_TEMPLATE_IDX_HOST_TEMPLATE_NAME, Indexes.HOST_TEMPLATE_IDX_HOST_TEMPLATE_REMOVE_TIME, Indexes.HOST_TEMPLATE_IDX_HOST_TEMPLATE_REMOVED, Indexes.HOST_TEMPLATE_IDX_HOST_TEMPLATE_STATE);
    }

    @Override
    public Identity<HostTemplateRecord, Long> getIdentity() {
        return Internal.createIdentity(this, ID);
    }

    @Override
    public UniqueKey<HostTemplateRecord> getPrimaryKey() {
        return Keys.KEY_HOST_TEMPLATE_PRIMARY;
    }

    @Override
    public List<UniqueKey<HostTemplateRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_HOST_TEMPLATE_IDX_HOST_TEMPLATE_UUID);
    }

    @Override
    public List<ForeignKey<HostTemplateRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_HOST_TEMPLATE__ACCOUNT_ID);
    }

    private transient AccountPath _account;

    /**
     * Get the implicit join path to the <code>cattle.account</code> table.
     */
    public AccountPath account() {
        if (_account == null)
            _account = new AccountPath(this, Keys.FK_HOST_TEMPLATE__ACCOUNT_ID, null);

        return _account;
    }

    private transient HostPath _host;

    /**
     * Get the implicit to-many join path to the <code>cattle.host</code> table
     */
    public HostPath host() {
        if (_host == null)
            _host = new HostPath(this, null, Keys.FK_HOST__HOST_TEMPLATE_ID.getInverseKey());

        return _host;
    }

    @Override
    public HostTemplateTable as(String alias) {
        return new HostTemplateTable(DSL.name(alias), this);
    }

    @Override
    public HostTemplateTable as(Name alias) {
        return new HostTemplateTable(alias, this);
    }

    @Override
    public HostTemplateTable as(Table<?> alias) {
        return new HostTemplateTable(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public HostTemplateTable rename(String name) {
        return new HostTemplateTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public HostTemplateTable rename(Name name) {
        return new HostTemplateTable(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public HostTemplateTable rename(Table<?> name) {
        return new HostTemplateTable(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HostTemplateTable where(Condition condition) {
        return new HostTemplateTable(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HostTemplateTable where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HostTemplateTable where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HostTemplateTable where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HostTemplateTable where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HostTemplateTable where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HostTemplateTable where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HostTemplateTable where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HostTemplateTable whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HostTemplateTable whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
