/*
 * This file is generated by jOOQ.
 */
package io.cattle.platform.core.model.tables;


import io.cattle.platform.core.model.CattleTable;
import io.cattle.platform.core.model.Indexes;
import io.cattle.platform.core.model.Keys;
import io.cattle.platform.core.model.tables.AccountTable.AccountPath;
import io.cattle.platform.core.model.tables.CredentialTable.CredentialPath;
import io.cattle.platform.core.model.tables.ImageStoragePoolMapTable.ImageStoragePoolMapPath;
import io.cattle.platform.core.model.tables.InstanceTable.InstancePath;
import io.cattle.platform.core.model.tables.VolumeTable.VolumePath;
import io.cattle.platform.core.model.tables.records.ImageRecord;
import io.cattle.platform.db.jooq.converter.DataConverter;
import io.cattle.platform.db.jooq.converter.DateConverter;

import java.util.Arrays;
import java.util.Collection;
import java.util.Date;
import java.util.List;
import java.util.Map;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
public class ImageTable extends TableImpl<ImageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>cattle.image</code>
     */
    public static final ImageTable IMAGE = new ImageTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ImageRecord> getRecordType() {
        return ImageRecord.class;
    }

    /**
     * The column <code>cattle.image.id</code>.
     */
    public final TableField<ImageRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>cattle.image.name</code>.
     */
    public final TableField<ImageRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.image.account_id</code>.
     */
    public final TableField<ImageRecord, Long> ACCOUNT_ID = createField(DSL.name("account_id"), SQLDataType.BIGINT.defaultValue(DSL.inline("NULL", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>cattle.image.kind</code>.
     */
    public final TableField<ImageRecord, String> KIND = createField(DSL.name("kind"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>cattle.image.uuid</code>.
     */
    public final TableField<ImageRecord, String> UUID = createField(DSL.name("uuid"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>cattle.image.description</code>.
     */
    public final TableField<ImageRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(1024).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.image.state</code>.
     */
    public final TableField<ImageRecord, String> STATE = createField(DSL.name("state"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>cattle.image.created</code>.
     */
    public final TableField<ImageRecord, Date> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.image.removed</code>.
     */
    public final TableField<ImageRecord, Date> REMOVED = createField(DSL.name("removed"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.image.remove_time</code>.
     */
    public final TableField<ImageRecord, Date> REMOVE_TIME = createField(DSL.name("remove_time"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.image.data</code>.
     */
    public final TableField<ImageRecord, Map<String,Object>> DATA = createField(DSL.name("data"), SQLDataType.CLOB(16777215).defaultValue(DSL.inline("NULL", SQLDataType.CLOB)), this, "", new DataConverter());

    /**
     * The column <code>cattle.image.url</code>.
     */
    public final TableField<ImageRecord, String> URL = createField(DSL.name("url"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.image.is_public</code>.
     */
    public final TableField<ImageRecord, Boolean> IS_PUBLIC = createField(DSL.name("is_public"), SQLDataType.BIT.nullable(false).defaultValue(DSL.inline("b'0'", SQLDataType.BIT)), this, "");

    /**
     * The column <code>cattle.image.physical_size_mb</code>.
     */
    public final TableField<ImageRecord, Long> PHYSICAL_SIZE_MB = createField(DSL.name("physical_size_mb"), SQLDataType.BIGINT.defaultValue(DSL.inline("NULL", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>cattle.image.virtual_size_mb</code>.
     */
    public final TableField<ImageRecord, Long> VIRTUAL_SIZE_MB = createField(DSL.name("virtual_size_mb"), SQLDataType.BIGINT.defaultValue(DSL.inline("NULL", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>cattle.image.checksum</code>.
     */
    public final TableField<ImageRecord, String> CHECKSUM = createField(DSL.name("checksum"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.image.format</code>.
     */
    public final TableField<ImageRecord, String> FORMAT = createField(DSL.name("format"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.image.instance_kind</code>.
     */
    public final TableField<ImageRecord, String> INSTANCE_KIND = createField(DSL.name("instance_kind"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.image.registry_credential_id</code>.
     */
    public final TableField<ImageRecord, Long> REGISTRY_CREDENTIAL_ID = createField(DSL.name("registry_credential_id"), SQLDataType.BIGINT.defaultValue(DSL.inline("NULL", SQLDataType.BIGINT)), this, "");

    private ImageTable(Name alias, Table<ImageRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ImageTable(Name alias, Table<ImageRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>cattle.image</code> table reference
     */
    public ImageTable(String alias) {
        this(DSL.name(alias), IMAGE);
    }

    /**
     * Create an aliased <code>cattle.image</code> table reference
     */
    public ImageTable(Name alias) {
        this(alias, IMAGE);
    }

    /**
     * Create a <code>cattle.image</code> table reference
     */
    public ImageTable() {
        this(DSL.name("image"), null);
    }

    public <O extends Record> ImageTable(Table<O> path, ForeignKey<O, ImageRecord> childPath, InverseForeignKey<O, ImageRecord> parentPath) {
        super(path, childPath, parentPath, IMAGE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ImagePath extends ImageTable implements Path<ImageRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ImagePath(Table<O> path, ForeignKey<O, ImageRecord> childPath, InverseForeignKey<O, ImageRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ImagePath(Name alias, Table<ImageRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ImagePath as(String alias) {
            return new ImagePath(DSL.name(alias), this);
        }

        @Override
        public ImagePath as(Name alias) {
            return new ImagePath(alias, this);
        }

        @Override
        public ImagePath as(Table<?> alias) {
            return new ImagePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : CattleTable.CATTLE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IMAGE_IDX_IMAGE_INSTANCE_KIND, Indexes.IMAGE_IDX_IMAGE_NAME, Indexes.IMAGE_IDX_IMAGE_REMOVE_TIME, Indexes.IMAGE_IDX_IMAGE_REMOVED, Indexes.IMAGE_IDX_IMAGE_STATE);
    }

    @Override
    public Identity<ImageRecord, Long> getIdentity() {
        return Internal.createIdentity(this, ID);
    }

    @Override
    public UniqueKey<ImageRecord> getPrimaryKey() {
        return Keys.KEY_IMAGE_PRIMARY;
    }

    @Override
    public List<UniqueKey<ImageRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_IMAGE_IDX_IMAGE_UUID);
    }

    @Override
    public List<ForeignKey<ImageRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_IMAGE__ACCOUNT_ID, Keys.FK_IMAGE_REGISTRY_CREDENTIAL_ID);
    }

    private transient AccountPath _account;

    /**
     * Get the implicit join path to the <code>cattle.account</code> table.
     */
    public AccountPath account() {
        if (_account == null)
            _account = new AccountPath(this, Keys.FK_IMAGE__ACCOUNT_ID, null);

        return _account;
    }

    private transient CredentialPath _credential;

    /**
     * Get the implicit join path to the <code>cattle.credential</code> table.
     */
    public CredentialPath credential() {
        if (_credential == null)
            _credential = new CredentialPath(this, Keys.FK_IMAGE_REGISTRY_CREDENTIAL_ID, null);

        return _credential;
    }

    private transient ImageStoragePoolMapPath _imageStoragePoolMap;

    /**
     * Get the implicit to-many join path to the
     * <code>cattle.image_storage_pool_map</code> table
     */
    public ImageStoragePoolMapPath imageStoragePoolMap() {
        if (_imageStoragePoolMap == null)
            _imageStoragePoolMap = new ImageStoragePoolMapPath(this, null, Keys.FK_IMAGE_STORAGE_POOL_MAP__IMAGE_ID.getInverseKey());

        return _imageStoragePoolMap;
    }

    private transient InstancePath _instance;

    /**
     * Get the implicit to-many join path to the <code>cattle.instance</code>
     * table
     */
    public InstancePath instance() {
        if (_instance == null)
            _instance = new InstancePath(this, null, Keys.FK_INSTANCE__IMAGE_ID.getInverseKey());

        return _instance;
    }

    private transient VolumePath _volume;

    /**
     * Get the implicit to-many join path to the <code>cattle.volume</code>
     * table
     */
    public VolumePath volume() {
        if (_volume == null)
            _volume = new VolumePath(this, null, Keys.FK_VOLUME__IMAGE_ID.getInverseKey());

        return _volume;
    }

    @Override
    public ImageTable as(String alias) {
        return new ImageTable(DSL.name(alias), this);
    }

    @Override
    public ImageTable as(Name alias) {
        return new ImageTable(alias, this);
    }

    @Override
    public ImageTable as(Table<?> alias) {
        return new ImageTable(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ImageTable rename(String name) {
        return new ImageTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ImageTable rename(Name name) {
        return new ImageTable(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ImageTable rename(Table<?> name) {
        return new ImageTable(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ImageTable where(Condition condition) {
        return new ImageTable(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ImageTable where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ImageTable where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ImageTable where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ImageTable where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ImageTable where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ImageTable where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ImageTable where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ImageTable whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ImageTable whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
