/*
 * This file is generated by jOOQ.
 */
package io.cattle.platform.core.model.tables;


import io.cattle.platform.core.model.CattleTable;
import io.cattle.platform.core.model.Indexes;
import io.cattle.platform.core.model.Keys;
import io.cattle.platform.core.model.tables.HostTable.HostPath;
import io.cattle.platform.core.model.tables.InstanceTable.InstancePath;
import io.cattle.platform.core.model.tables.records.InstanceHostMapRecord;
import io.cattle.platform.db.jooq.converter.DataConverter;
import io.cattle.platform.db.jooq.converter.DateConverter;

import java.util.Arrays;
import java.util.Collection;
import java.util.Date;
import java.util.List;
import java.util.Map;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
public class InstanceHostMapTable extends TableImpl<InstanceHostMapRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>cattle.instance_host_map</code>
     */
    public static final InstanceHostMapTable INSTANCE_HOST_MAP = new InstanceHostMapTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<InstanceHostMapRecord> getRecordType() {
        return InstanceHostMapRecord.class;
    }

    /**
     * The column <code>cattle.instance_host_map.id</code>.
     */
    public final TableField<InstanceHostMapRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>cattle.instance_host_map.name</code>.
     */
    public final TableField<InstanceHostMapRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.instance_host_map.kind</code>.
     */
    public final TableField<InstanceHostMapRecord, String> KIND = createField(DSL.name("kind"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>cattle.instance_host_map.uuid</code>.
     */
    public final TableField<InstanceHostMapRecord, String> UUID = createField(DSL.name("uuid"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>cattle.instance_host_map.description</code>.
     */
    public final TableField<InstanceHostMapRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(1024).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.instance_host_map.state</code>.
     */
    public final TableField<InstanceHostMapRecord, String> STATE = createField(DSL.name("state"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>cattle.instance_host_map.created</code>.
     */
    public final TableField<InstanceHostMapRecord, Date> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.instance_host_map.removed</code>.
     */
    public final TableField<InstanceHostMapRecord, Date> REMOVED = createField(DSL.name("removed"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.instance_host_map.remove_time</code>.
     */
    public final TableField<InstanceHostMapRecord, Date> REMOVE_TIME = createField(DSL.name("remove_time"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.instance_host_map.data</code>.
     */
    public final TableField<InstanceHostMapRecord, Map<String,Object>> DATA = createField(DSL.name("data"), SQLDataType.CLOB(16777215).defaultValue(DSL.inline("NULL", SQLDataType.CLOB)), this, "", new DataConverter());

    /**
     * The column <code>cattle.instance_host_map.instance_id</code>.
     */
    public final TableField<InstanceHostMapRecord, Long> INSTANCE_ID = createField(DSL.name("instance_id"), SQLDataType.BIGINT.defaultValue(DSL.inline("NULL", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>cattle.instance_host_map.host_id</code>.
     */
    public final TableField<InstanceHostMapRecord, Long> HOST_ID = createField(DSL.name("host_id"), SQLDataType.BIGINT.defaultValue(DSL.inline("NULL", SQLDataType.BIGINT)), this, "");

    private InstanceHostMapTable(Name alias, Table<InstanceHostMapRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private InstanceHostMapTable(Name alias, Table<InstanceHostMapRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>cattle.instance_host_map</code> table reference
     */
    public InstanceHostMapTable(String alias) {
        this(DSL.name(alias), INSTANCE_HOST_MAP);
    }

    /**
     * Create an aliased <code>cattle.instance_host_map</code> table reference
     */
    public InstanceHostMapTable(Name alias) {
        this(alias, INSTANCE_HOST_MAP);
    }

    /**
     * Create a <code>cattle.instance_host_map</code> table reference
     */
    public InstanceHostMapTable() {
        this(DSL.name("instance_host_map"), null);
    }

    public <O extends Record> InstanceHostMapTable(Table<O> path, ForeignKey<O, InstanceHostMapRecord> childPath, InverseForeignKey<O, InstanceHostMapRecord> parentPath) {
        super(path, childPath, parentPath, INSTANCE_HOST_MAP);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class InstanceHostMapPath extends InstanceHostMapTable implements Path<InstanceHostMapRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> InstanceHostMapPath(Table<O> path, ForeignKey<O, InstanceHostMapRecord> childPath, InverseForeignKey<O, InstanceHostMapRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private InstanceHostMapPath(Name alias, Table<InstanceHostMapRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public InstanceHostMapPath as(String alias) {
            return new InstanceHostMapPath(DSL.name(alias), this);
        }

        @Override
        public InstanceHostMapPath as(Name alias) {
            return new InstanceHostMapPath(alias, this);
        }

        @Override
        public InstanceHostMapPath as(Table<?> alias) {
            return new InstanceHostMapPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : CattleTable.CATTLE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.INSTANCE_HOST_MAP_IDX_INSTANCE_HOST_MAP_NAME, Indexes.INSTANCE_HOST_MAP_IDX_INSTANCE_HOST_MAP_REMOVE_TIME, Indexes.INSTANCE_HOST_MAP_IDX_INSTANCE_HOST_MAP_REMOVED, Indexes.INSTANCE_HOST_MAP_IDX_INSTANCE_HOST_MAP_STATE);
    }

    @Override
    public Identity<InstanceHostMapRecord, Long> getIdentity() {
        return Internal.createIdentity(this, ID);
    }

    @Override
    public UniqueKey<InstanceHostMapRecord> getPrimaryKey() {
        return Keys.KEY_INSTANCE_HOST_MAP_PRIMARY;
    }

    @Override
    public List<UniqueKey<InstanceHostMapRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_INSTANCE_HOST_MAP_IDX_INSTANCE_HOST_MAP_UUID);
    }

    @Override
    public List<ForeignKey<InstanceHostMapRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_INSTANCE_HOST_MAP__HOST_ID, Keys.FK_INSTANCE_HOST_MAP__INSTANCE_ID);
    }

    private transient HostPath _host;

    /**
     * Get the implicit join path to the <code>cattle.host</code> table.
     */
    public HostPath host() {
        if (_host == null)
            _host = new HostPath(this, Keys.FK_INSTANCE_HOST_MAP__HOST_ID, null);

        return _host;
    }

    private transient InstancePath _instance;

    /**
     * Get the implicit join path to the <code>cattle.instance</code> table.
     */
    public InstancePath instance() {
        if (_instance == null)
            _instance = new InstancePath(this, Keys.FK_INSTANCE_HOST_MAP__INSTANCE_ID, null);

        return _instance;
    }

    @Override
    public InstanceHostMapTable as(String alias) {
        return new InstanceHostMapTable(DSL.name(alias), this);
    }

    @Override
    public InstanceHostMapTable as(Name alias) {
        return new InstanceHostMapTable(alias, this);
    }

    @Override
    public InstanceHostMapTable as(Table<?> alias) {
        return new InstanceHostMapTable(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public InstanceHostMapTable rename(String name) {
        return new InstanceHostMapTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public InstanceHostMapTable rename(Name name) {
        return new InstanceHostMapTable(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public InstanceHostMapTable rename(Table<?> name) {
        return new InstanceHostMapTable(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InstanceHostMapTable where(Condition condition) {
        return new InstanceHostMapTable(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InstanceHostMapTable where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InstanceHostMapTable where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InstanceHostMapTable where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InstanceHostMapTable where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InstanceHostMapTable where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InstanceHostMapTable where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InstanceHostMapTable where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InstanceHostMapTable whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InstanceHostMapTable whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
