/*
 * This file is generated by jOOQ.
 */
package io.cattle.platform.core.model.tables;


import io.cattle.platform.core.model.CattleTable;
import io.cattle.platform.core.model.Indexes;
import io.cattle.platform.core.model.Keys;
import io.cattle.platform.core.model.tables.AccountTable.AccountPath;
import io.cattle.platform.core.model.tables.InstanceTable.InstancePath;
import io.cattle.platform.core.model.tables.ServiceConsumeMapTable.ServiceConsumeMapPath;
import io.cattle.platform.core.model.tables.records.InstanceLinkRecord;
import io.cattle.platform.db.jooq.converter.DataConverter;
import io.cattle.platform.db.jooq.converter.DateConverter;

import java.util.Arrays;
import java.util.Collection;
import java.util.Date;
import java.util.List;
import java.util.Map;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
public class InstanceLinkTable extends TableImpl<InstanceLinkRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>cattle.instance_link</code>
     */
    public static final InstanceLinkTable INSTANCE_LINK = new InstanceLinkTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<InstanceLinkRecord> getRecordType() {
        return InstanceLinkRecord.class;
    }

    /**
     * The column <code>cattle.instance_link.id</code>.
     */
    public final TableField<InstanceLinkRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>cattle.instance_link.name</code>.
     */
    public final TableField<InstanceLinkRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.instance_link.account_id</code>.
     */
    public final TableField<InstanceLinkRecord, Long> ACCOUNT_ID = createField(DSL.name("account_id"), SQLDataType.BIGINT.defaultValue(DSL.inline("NULL", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>cattle.instance_link.kind</code>.
     */
    public final TableField<InstanceLinkRecord, String> KIND = createField(DSL.name("kind"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>cattle.instance_link.uuid</code>.
     */
    public final TableField<InstanceLinkRecord, String> UUID = createField(DSL.name("uuid"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>cattle.instance_link.description</code>.
     */
    public final TableField<InstanceLinkRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(1024).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.instance_link.state</code>.
     */
    public final TableField<InstanceLinkRecord, String> STATE = createField(DSL.name("state"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>cattle.instance_link.created</code>.
     */
    public final TableField<InstanceLinkRecord, Date> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.instance_link.removed</code>.
     */
    public final TableField<InstanceLinkRecord, Date> REMOVED = createField(DSL.name("removed"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.instance_link.remove_time</code>.
     */
    public final TableField<InstanceLinkRecord, Date> REMOVE_TIME = createField(DSL.name("remove_time"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.instance_link.data</code>.
     */
    public final TableField<InstanceLinkRecord, Map<String,Object>> DATA = createField(DSL.name("data"), SQLDataType.CLOB(16777215).defaultValue(DSL.inline("NULL", SQLDataType.CLOB)), this, "", new DataConverter());

    /**
     * The column <code>cattle.instance_link.link_name</code>.
     */
    public final TableField<InstanceLinkRecord, String> LINK_NAME = createField(DSL.name("link_name"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.instance_link.instance_id</code>.
     */
    public final TableField<InstanceLinkRecord, Long> INSTANCE_ID = createField(DSL.name("instance_id"), SQLDataType.BIGINT.defaultValue(DSL.inline("NULL", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>cattle.instance_link.target_instance_id</code>.
     */
    public final TableField<InstanceLinkRecord, Long> TARGET_INSTANCE_ID = createField(DSL.name("target_instance_id"), SQLDataType.BIGINT.defaultValue(DSL.inline("NULL", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>cattle.instance_link.service_consume_map_id</code>.
     */
    public final TableField<InstanceLinkRecord, Long> SERVICE_CONSUME_MAP_ID = createField(DSL.name("service_consume_map_id"), SQLDataType.BIGINT.defaultValue(DSL.inline("NULL", SQLDataType.BIGINT)), this, "");

    private InstanceLinkTable(Name alias, Table<InstanceLinkRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private InstanceLinkTable(Name alias, Table<InstanceLinkRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>cattle.instance_link</code> table reference
     */
    public InstanceLinkTable(String alias) {
        this(DSL.name(alias), INSTANCE_LINK);
    }

    /**
     * Create an aliased <code>cattle.instance_link</code> table reference
     */
    public InstanceLinkTable(Name alias) {
        this(alias, INSTANCE_LINK);
    }

    /**
     * Create a <code>cattle.instance_link</code> table reference
     */
    public InstanceLinkTable() {
        this(DSL.name("instance_link"), null);
    }

    public <O extends Record> InstanceLinkTable(Table<O> path, ForeignKey<O, InstanceLinkRecord> childPath, InverseForeignKey<O, InstanceLinkRecord> parentPath) {
        super(path, childPath, parentPath, INSTANCE_LINK);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class InstanceLinkPath extends InstanceLinkTable implements Path<InstanceLinkRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> InstanceLinkPath(Table<O> path, ForeignKey<O, InstanceLinkRecord> childPath, InverseForeignKey<O, InstanceLinkRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private InstanceLinkPath(Name alias, Table<InstanceLinkRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public InstanceLinkPath as(String alias) {
            return new InstanceLinkPath(DSL.name(alias), this);
        }

        @Override
        public InstanceLinkPath as(Name alias) {
            return new InstanceLinkPath(alias, this);
        }

        @Override
        public InstanceLinkPath as(Table<?> alias) {
            return new InstanceLinkPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : CattleTable.CATTLE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.INSTANCE_LINK_IDX_LINK_NAME, Indexes.INSTANCE_LINK_IDX_LINK_REMOVE_TIME, Indexes.INSTANCE_LINK_IDX_LINK_REMOVED, Indexes.INSTANCE_LINK_IDX_LINK_STATE);
    }

    @Override
    public Identity<InstanceLinkRecord, Long> getIdentity() {
        return Internal.createIdentity(this, ID);
    }

    @Override
    public UniqueKey<InstanceLinkRecord> getPrimaryKey() {
        return Keys.KEY_INSTANCE_LINK_PRIMARY;
    }

    @Override
    public List<UniqueKey<InstanceLinkRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_INSTANCE_LINK_IDX_LINK_UUID);
    }

    @Override
    public List<ForeignKey<InstanceLinkRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_LINK__ACCOUNT_ID, Keys.FK_LINK__INSTANCE_ID, Keys.FK_LINK__SERVICE_CONSUME_MAP_ID, Keys.FK_LINK__TARGET_INSTANCE_ID);
    }

    private transient AccountPath _account;

    /**
     * Get the implicit join path to the <code>cattle.account</code> table.
     */
    public AccountPath account() {
        if (_account == null)
            _account = new AccountPath(this, Keys.FK_LINK__ACCOUNT_ID, null);

        return _account;
    }

    private transient InstancePath _fkLink_InstanceId;

    /**
     * Get the implicit join path to the <code>cattle.instance</code> table, via
     * the <code>fk_link__instance_id</code> key.
     */
    public InstancePath fkLink_InstanceId() {
        if (_fkLink_InstanceId == null)
            _fkLink_InstanceId = new InstancePath(this, Keys.FK_LINK__INSTANCE_ID, null);

        return _fkLink_InstanceId;
    }

    private transient ServiceConsumeMapPath _serviceConsumeMap;

    /**
     * Get the implicit join path to the <code>cattle.service_consume_map</code>
     * table.
     */
    public ServiceConsumeMapPath serviceConsumeMap() {
        if (_serviceConsumeMap == null)
            _serviceConsumeMap = new ServiceConsumeMapPath(this, Keys.FK_LINK__SERVICE_CONSUME_MAP_ID, null);

        return _serviceConsumeMap;
    }

    private transient InstancePath _fkLink_TargetInstanceId;

    /**
     * Get the implicit join path to the <code>cattle.instance</code> table, via
     * the <code>fk_link__target_instance_id</code> key.
     */
    public InstancePath fkLink_TargetInstanceId() {
        if (_fkLink_TargetInstanceId == null)
            _fkLink_TargetInstanceId = new InstancePath(this, Keys.FK_LINK__TARGET_INSTANCE_ID, null);

        return _fkLink_TargetInstanceId;
    }

    @Override
    public InstanceLinkTable as(String alias) {
        return new InstanceLinkTable(DSL.name(alias), this);
    }

    @Override
    public InstanceLinkTable as(Name alias) {
        return new InstanceLinkTable(alias, this);
    }

    @Override
    public InstanceLinkTable as(Table<?> alias) {
        return new InstanceLinkTable(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public InstanceLinkTable rename(String name) {
        return new InstanceLinkTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public InstanceLinkTable rename(Name name) {
        return new InstanceLinkTable(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public InstanceLinkTable rename(Table<?> name) {
        return new InstanceLinkTable(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InstanceLinkTable where(Condition condition) {
        return new InstanceLinkTable(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InstanceLinkTable where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InstanceLinkTable where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InstanceLinkTable where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InstanceLinkTable where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InstanceLinkTable where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InstanceLinkTable where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InstanceLinkTable where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InstanceLinkTable whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InstanceLinkTable whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
