/*
 * This file is generated by jOOQ.
 */
package io.cattle.platform.core.model.tables;


import io.cattle.platform.core.model.CattleTable;
import io.cattle.platform.core.model.Indexes;
import io.cattle.platform.core.model.Keys;
import io.cattle.platform.core.model.tables.AccountTable.AccountPath;
import io.cattle.platform.core.model.tables.HostLabelMapTable.HostLabelMapPath;
import io.cattle.platform.core.model.tables.InstanceLabelMapTable.InstanceLabelMapPath;
import io.cattle.platform.core.model.tables.records.LabelRecord;
import io.cattle.platform.db.jooq.converter.DataConverter;
import io.cattle.platform.db.jooq.converter.DateConverter;

import java.util.Arrays;
import java.util.Collection;
import java.util.Date;
import java.util.List;
import java.util.Map;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
public class LabelTable extends TableImpl<LabelRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>cattle.label</code>
     */
    public static final LabelTable LABEL = new LabelTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LabelRecord> getRecordType() {
        return LabelRecord.class;
    }

    /**
     * The column <code>cattle.label.id</code>.
     */
    public final TableField<LabelRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>cattle.label.name</code>.
     */
    public final TableField<LabelRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.label.account_id</code>.
     */
    public final TableField<LabelRecord, Long> ACCOUNT_ID = createField(DSL.name("account_id"), SQLDataType.BIGINT.defaultValue(DSL.inline("NULL", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>cattle.label.kind</code>.
     */
    public final TableField<LabelRecord, String> KIND = createField(DSL.name("kind"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>cattle.label.uuid</code>.
     */
    public final TableField<LabelRecord, String> UUID = createField(DSL.name("uuid"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>cattle.label.description</code>.
     */
    public final TableField<LabelRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(1024).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.label.state</code>.
     */
    public final TableField<LabelRecord, String> STATE = createField(DSL.name("state"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>cattle.label.created</code>.
     */
    public final TableField<LabelRecord, Date> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.label.removed</code>.
     */
    public final TableField<LabelRecord, Date> REMOVED = createField(DSL.name("removed"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.label.remove_time</code>.
     */
    public final TableField<LabelRecord, Date> REMOVE_TIME = createField(DSL.name("remove_time"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.label.data</code>.
     */
    public final TableField<LabelRecord, Map<String,Object>> DATA = createField(DSL.name("data"), SQLDataType.CLOB(16777215).defaultValue(DSL.inline("NULL", SQLDataType.CLOB)), this, "", new DataConverter());

    /**
     * The column <code>cattle.label.type</code>.
     */
    public final TableField<LabelRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.label.key</code>.
     */
    public final TableField<LabelRecord, String> KEY = createField(DSL.name("key"), SQLDataType.VARCHAR(1024).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.label.value</code>.
     */
    public final TableField<LabelRecord, String> VALUE = createField(DSL.name("value"), SQLDataType.VARCHAR(4096).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    private LabelTable(Name alias, Table<LabelRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private LabelTable(Name alias, Table<LabelRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>cattle.label</code> table reference
     */
    public LabelTable(String alias) {
        this(DSL.name(alias), LABEL);
    }

    /**
     * Create an aliased <code>cattle.label</code> table reference
     */
    public LabelTable(Name alias) {
        this(alias, LABEL);
    }

    /**
     * Create a <code>cattle.label</code> table reference
     */
    public LabelTable() {
        this(DSL.name("label"), null);
    }

    public <O extends Record> LabelTable(Table<O> path, ForeignKey<O, LabelRecord> childPath, InverseForeignKey<O, LabelRecord> parentPath) {
        super(path, childPath, parentPath, LABEL);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class LabelPath extends LabelTable implements Path<LabelRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> LabelPath(Table<O> path, ForeignKey<O, LabelRecord> childPath, InverseForeignKey<O, LabelRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private LabelPath(Name alias, Table<LabelRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public LabelPath as(String alias) {
            return new LabelPath(DSL.name(alias), this);
        }

        @Override
        public LabelPath as(Name alias) {
            return new LabelPath(alias, this);
        }

        @Override
        public LabelPath as(Table<?> alias) {
            return new LabelPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : CattleTable.CATTLE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.LABEL_IDX_LABEL_KEY_VALUE, Indexes.LABEL_IDX_LABEL_NAME, Indexes.LABEL_IDX_LABEL_REMOVE_TIME, Indexes.LABEL_IDX_LABEL_REMOVED, Indexes.LABEL_IDX_LABEL_STATE);
    }

    @Override
    public Identity<LabelRecord, Long> getIdentity() {
        return Internal.createIdentity(this, ID);
    }

    @Override
    public UniqueKey<LabelRecord> getPrimaryKey() {
        return Keys.KEY_LABEL_PRIMARY;
    }

    @Override
    public List<UniqueKey<LabelRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_LABEL_IDX_LABEL_UUID);
    }

    @Override
    public List<ForeignKey<LabelRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_LABEL__ACCOUNT_ID);
    }

    private transient AccountPath _account;

    /**
     * Get the implicit join path to the <code>cattle.account</code> table.
     */
    public AccountPath account() {
        if (_account == null)
            _account = new AccountPath(this, Keys.FK_LABEL__ACCOUNT_ID, null);

        return _account;
    }

    private transient HostLabelMapPath _hostLabelMap;

    /**
     * Get the implicit to-many join path to the
     * <code>cattle.host_label_map</code> table
     */
    public HostLabelMapPath hostLabelMap() {
        if (_hostLabelMap == null)
            _hostLabelMap = new HostLabelMapPath(this, null, Keys.FK_HOST_LABEL_MAP__LABEL_ID.getInverseKey());

        return _hostLabelMap;
    }

    private transient InstanceLabelMapPath _instanceLabelMap;

    /**
     * Get the implicit to-many join path to the
     * <code>cattle.instance_label_map</code> table
     */
    public InstanceLabelMapPath instanceLabelMap() {
        if (_instanceLabelMap == null)
            _instanceLabelMap = new InstanceLabelMapPath(this, null, Keys.FK_INSTANCE_LABEL_MAP__LABEL_ID.getInverseKey());

        return _instanceLabelMap;
    }

    @Override
    public LabelTable as(String alias) {
        return new LabelTable(DSL.name(alias), this);
    }

    @Override
    public LabelTable as(Name alias) {
        return new LabelTable(alias, this);
    }

    @Override
    public LabelTable as(Table<?> alias) {
        return new LabelTable(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public LabelTable rename(String name) {
        return new LabelTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public LabelTable rename(Name name) {
        return new LabelTable(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public LabelTable rename(Table<?> name) {
        return new LabelTable(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LabelTable where(Condition condition) {
        return new LabelTable(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LabelTable where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LabelTable where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LabelTable where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LabelTable where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LabelTable where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LabelTable where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LabelTable where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LabelTable whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LabelTable whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
