/*
 * This file is generated by jOOQ.
 */
package io.cattle.platform.core.model.tables;


import io.cattle.platform.core.model.CattleTable;
import io.cattle.platform.core.model.Indexes;
import io.cattle.platform.core.model.Keys;
import io.cattle.platform.core.model.tables.AccountTable.AccountPath;
import io.cattle.platform.core.model.tables.IpAddressTable.IpAddressPath;
import io.cattle.platform.core.model.tables.NetworkDriverTable.NetworkDriverPath;
import io.cattle.platform.core.model.tables.NicTable.NicPath;
import io.cattle.platform.core.model.tables.SubnetTable.SubnetPath;
import io.cattle.platform.core.model.tables.records.NetworkRecord;
import io.cattle.platform.db.jooq.converter.DataConverter;
import io.cattle.platform.db.jooq.converter.DateConverter;

import java.util.Arrays;
import java.util.Collection;
import java.util.Date;
import java.util.List;
import java.util.Map;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
public class NetworkTable extends TableImpl<NetworkRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>cattle.network</code>
     */
    public static final NetworkTable NETWORK = new NetworkTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<NetworkRecord> getRecordType() {
        return NetworkRecord.class;
    }

    /**
     * The column <code>cattle.network.id</code>.
     */
    public final TableField<NetworkRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>cattle.network.name</code>.
     */
    public final TableField<NetworkRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.network.account_id</code>.
     */
    public final TableField<NetworkRecord, Long> ACCOUNT_ID = createField(DSL.name("account_id"), SQLDataType.BIGINT.defaultValue(DSL.inline("NULL", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>cattle.network.kind</code>.
     */
    public final TableField<NetworkRecord, String> KIND = createField(DSL.name("kind"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>cattle.network.uuid</code>.
     */
    public final TableField<NetworkRecord, String> UUID = createField(DSL.name("uuid"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>cattle.network.description</code>.
     */
    public final TableField<NetworkRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(1024).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.network.state</code>.
     */
    public final TableField<NetworkRecord, String> STATE = createField(DSL.name("state"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>cattle.network.created</code>.
     */
    public final TableField<NetworkRecord, Date> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.network.removed</code>.
     */
    public final TableField<NetworkRecord, Date> REMOVED = createField(DSL.name("removed"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.network.remove_time</code>.
     */
    public final TableField<NetworkRecord, Date> REMOVE_TIME = createField(DSL.name("remove_time"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.network.data</code>.
     */
    public final TableField<NetworkRecord, Map<String,Object>> DATA = createField(DSL.name("data"), SQLDataType.CLOB(16777215).defaultValue(DSL.inline("NULL", SQLDataType.CLOB)), this, "", new DataConverter());

    /**
     * The column <code>cattle.network.is_public</code>.
     */
    public final TableField<NetworkRecord, Boolean> IS_PUBLIC = createField(DSL.name("is_public"), SQLDataType.BIT.nullable(false).defaultValue(DSL.inline("b'0'", SQLDataType.BIT)), this, "");

    /**
     * The column <code>cattle.network.domain</code>.
     */
    public final TableField<NetworkRecord, String> DOMAIN = createField(DSL.name("domain"), SQLDataType.VARCHAR(128).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.network.network_driver_id</code>.
     */
    public final TableField<NetworkRecord, Long> NETWORK_DRIVER_ID = createField(DSL.name("network_driver_id"), SQLDataType.BIGINT.defaultValue(DSL.inline("NULL", SQLDataType.BIGINT)), this, "");

    private NetworkTable(Name alias, Table<NetworkRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private NetworkTable(Name alias, Table<NetworkRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>cattle.network</code> table reference
     */
    public NetworkTable(String alias) {
        this(DSL.name(alias), NETWORK);
    }

    /**
     * Create an aliased <code>cattle.network</code> table reference
     */
    public NetworkTable(Name alias) {
        this(alias, NETWORK);
    }

    /**
     * Create a <code>cattle.network</code> table reference
     */
    public NetworkTable() {
        this(DSL.name("network"), null);
    }

    public <O extends Record> NetworkTable(Table<O> path, ForeignKey<O, NetworkRecord> childPath, InverseForeignKey<O, NetworkRecord> parentPath) {
        super(path, childPath, parentPath, NETWORK);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class NetworkPath extends NetworkTable implements Path<NetworkRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> NetworkPath(Table<O> path, ForeignKey<O, NetworkRecord> childPath, InverseForeignKey<O, NetworkRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private NetworkPath(Name alias, Table<NetworkRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public NetworkPath as(String alias) {
            return new NetworkPath(DSL.name(alias), this);
        }

        @Override
        public NetworkPath as(Name alias) {
            return new NetworkPath(alias, this);
        }

        @Override
        public NetworkPath as(Table<?> alias) {
            return new NetworkPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : CattleTable.CATTLE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.NETWORK_IDX_NETWORK_NAME, Indexes.NETWORK_IDX_NETWORK_REMOVE_TIME, Indexes.NETWORK_IDX_NETWORK_REMOVED, Indexes.NETWORK_IDX_NETWORK_STATE);
    }

    @Override
    public Identity<NetworkRecord, Long> getIdentity() {
        return Internal.createIdentity(this, ID);
    }

    @Override
    public UniqueKey<NetworkRecord> getPrimaryKey() {
        return Keys.KEY_NETWORK_PRIMARY;
    }

    @Override
    public List<UniqueKey<NetworkRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_NETWORK_IDX_NETWORK_UUID);
    }

    @Override
    public List<ForeignKey<NetworkRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_NETWORK__ACCOUNT_ID, Keys.FK_NETWORK__NETWORK_DRIVER_ID);
    }

    private transient AccountPath _account;

    /**
     * Get the implicit join path to the <code>cattle.account</code> table.
     */
    public AccountPath account() {
        if (_account == null)
            _account = new AccountPath(this, Keys.FK_NETWORK__ACCOUNT_ID, null);

        return _account;
    }

    private transient NetworkDriverPath _networkDriver;

    /**
     * Get the implicit join path to the <code>cattle.network_driver</code>
     * table.
     */
    public NetworkDriverPath networkDriver() {
        if (_networkDriver == null)
            _networkDriver = new NetworkDriverPath(this, Keys.FK_NETWORK__NETWORK_DRIVER_ID, null);

        return _networkDriver;
    }

    private transient IpAddressPath _ipAddress;

    /**
     * Get the implicit to-many join path to the <code>cattle.ip_address</code>
     * table
     */
    public IpAddressPath ipAddress() {
        if (_ipAddress == null)
            _ipAddress = new IpAddressPath(this, null, Keys.FK_IP_ADDRESS__NETWORK_ID.getInverseKey());

        return _ipAddress;
    }

    private transient NicPath _nic;

    /**
     * Get the implicit to-many join path to the <code>cattle.nic</code> table
     */
    public NicPath nic() {
        if (_nic == null)
            _nic = new NicPath(this, null, Keys.FK_NIC__NETWORK_ID.getInverseKey());

        return _nic;
    }

    private transient SubnetPath _subnet;

    /**
     * Get the implicit to-many join path to the <code>cattle.subnet</code>
     * table
     */
    public SubnetPath subnet() {
        if (_subnet == null)
            _subnet = new SubnetPath(this, null, Keys.FK_SUBNET__NETWORK_ID.getInverseKey());

        return _subnet;
    }

    @Override
    public NetworkTable as(String alias) {
        return new NetworkTable(DSL.name(alias), this);
    }

    @Override
    public NetworkTable as(Name alias) {
        return new NetworkTable(alias, this);
    }

    @Override
    public NetworkTable as(Table<?> alias) {
        return new NetworkTable(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public NetworkTable rename(String name) {
        return new NetworkTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public NetworkTable rename(Name name) {
        return new NetworkTable(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public NetworkTable rename(Table<?> name) {
        return new NetworkTable(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NetworkTable where(Condition condition) {
        return new NetworkTable(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NetworkTable where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NetworkTable where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NetworkTable where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public NetworkTable where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public NetworkTable where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public NetworkTable where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public NetworkTable where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NetworkTable whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NetworkTable whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
