/*
 * This file is generated by jOOQ.
 */
package io.cattle.platform.core.model.tables;


import io.cattle.platform.core.model.CattleTable;
import io.cattle.platform.core.model.Indexes;
import io.cattle.platform.core.model.Keys;
import io.cattle.platform.core.model.tables.AccountTable.AccountPath;
import io.cattle.platform.core.model.tables.records.ProjectTemplateRecord;
import io.cattle.platform.db.jooq.converter.DataConverter;
import io.cattle.platform.db.jooq.converter.DateConverter;

import java.util.Arrays;
import java.util.Collection;
import java.util.Date;
import java.util.List;
import java.util.Map;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
public class ProjectTemplateTable extends TableImpl<ProjectTemplateRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>cattle.project_template</code>
     */
    public static final ProjectTemplateTable PROJECT_TEMPLATE = new ProjectTemplateTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProjectTemplateRecord> getRecordType() {
        return ProjectTemplateRecord.class;
    }

    /**
     * The column <code>cattle.project_template.id</code>.
     */
    public final TableField<ProjectTemplateRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>cattle.project_template.name</code>.
     */
    public final TableField<ProjectTemplateRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.project_template.account_id</code>.
     */
    public final TableField<ProjectTemplateRecord, Long> ACCOUNT_ID = createField(DSL.name("account_id"), SQLDataType.BIGINT.defaultValue(DSL.inline("NULL", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>cattle.project_template.kind</code>.
     */
    public final TableField<ProjectTemplateRecord, String> KIND = createField(DSL.name("kind"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>cattle.project_template.uuid</code>.
     */
    public final TableField<ProjectTemplateRecord, String> UUID = createField(DSL.name("uuid"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>cattle.project_template.description</code>.
     */
    public final TableField<ProjectTemplateRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(1024).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.project_template.state</code>.
     */
    public final TableField<ProjectTemplateRecord, String> STATE = createField(DSL.name("state"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>cattle.project_template.created</code>.
     */
    public final TableField<ProjectTemplateRecord, Date> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.project_template.removed</code>.
     */
    public final TableField<ProjectTemplateRecord, Date> REMOVED = createField(DSL.name("removed"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.project_template.remove_time</code>.
     */
    public final TableField<ProjectTemplateRecord, Date> REMOVE_TIME = createField(DSL.name("remove_time"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.project_template.data</code>.
     */
    public final TableField<ProjectTemplateRecord, Map<String,Object>> DATA = createField(DSL.name("data"), SQLDataType.CLOB(16777215).defaultValue(DSL.inline("NULL", SQLDataType.CLOB)), this, "", new DataConverter());

    /**
     * The column <code>cattle.project_template.is_public</code>.
     */
    public final TableField<ProjectTemplateRecord, Boolean> IS_PUBLIC = createField(DSL.name("is_public"), SQLDataType.BIT.nullable(false).defaultValue(DSL.inline("b'0'", SQLDataType.BIT)), this, "");

    /**
     * The column <code>cattle.project_template.external_id</code>.
     */
    public final TableField<ProjectTemplateRecord, String> EXTERNAL_ID = createField(DSL.name("external_id"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    private ProjectTemplateTable(Name alias, Table<ProjectTemplateRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ProjectTemplateTable(Name alias, Table<ProjectTemplateRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>cattle.project_template</code> table reference
     */
    public ProjectTemplateTable(String alias) {
        this(DSL.name(alias), PROJECT_TEMPLATE);
    }

    /**
     * Create an aliased <code>cattle.project_template</code> table reference
     */
    public ProjectTemplateTable(Name alias) {
        this(alias, PROJECT_TEMPLATE);
    }

    /**
     * Create a <code>cattle.project_template</code> table reference
     */
    public ProjectTemplateTable() {
        this(DSL.name("project_template"), null);
    }

    public <O extends Record> ProjectTemplateTable(Table<O> path, ForeignKey<O, ProjectTemplateRecord> childPath, InverseForeignKey<O, ProjectTemplateRecord> parentPath) {
        super(path, childPath, parentPath, PROJECT_TEMPLATE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ProjectTemplatePath extends ProjectTemplateTable implements Path<ProjectTemplateRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ProjectTemplatePath(Table<O> path, ForeignKey<O, ProjectTemplateRecord> childPath, InverseForeignKey<O, ProjectTemplateRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ProjectTemplatePath(Name alias, Table<ProjectTemplateRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ProjectTemplatePath as(String alias) {
            return new ProjectTemplatePath(DSL.name(alias), this);
        }

        @Override
        public ProjectTemplatePath as(Name alias) {
            return new ProjectTemplatePath(alias, this);
        }

        @Override
        public ProjectTemplatePath as(Table<?> alias) {
            return new ProjectTemplatePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : CattleTable.CATTLE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.PROJECT_TEMPLATE_IDX_PROJECT_TEMPLATE_EXTERNAL_ID, Indexes.PROJECT_TEMPLATE_IDX_PROJECT_TEMPLATE_IS_PUBLIC, Indexes.PROJECT_TEMPLATE_IDX_PROJECT_TEMPLATE_NAME, Indexes.PROJECT_TEMPLATE_IDX_PROJECT_TEMPLATE_REMOVE_TIME, Indexes.PROJECT_TEMPLATE_IDX_PROJECT_TEMPLATE_REMOVED, Indexes.PROJECT_TEMPLATE_IDX_PROJECT_TEMPLATE_STATE);
    }

    @Override
    public Identity<ProjectTemplateRecord, Long> getIdentity() {
        return Internal.createIdentity(this, ID);
    }

    @Override
    public UniqueKey<ProjectTemplateRecord> getPrimaryKey() {
        return Keys.KEY_PROJECT_TEMPLATE_PRIMARY;
    }

    @Override
    public List<UniqueKey<ProjectTemplateRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_PROJECT_TEMPLATE_IDX_PROJECT_TEMPLATE_UUID);
    }

    @Override
    public List<ForeignKey<ProjectTemplateRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_PROJECT_TEMPLATE__ACCOUNT_ID);
    }

    private transient AccountPath _account;

    /**
     * Get the implicit join path to the <code>cattle.account</code> table.
     */
    public AccountPath account() {
        if (_account == null)
            _account = new AccountPath(this, Keys.FK_PROJECT_TEMPLATE__ACCOUNT_ID, null);

        return _account;
    }

    @Override
    public ProjectTemplateTable as(String alias) {
        return new ProjectTemplateTable(DSL.name(alias), this);
    }

    @Override
    public ProjectTemplateTable as(Name alias) {
        return new ProjectTemplateTable(alias, this);
    }

    @Override
    public ProjectTemplateTable as(Table<?> alias) {
        return new ProjectTemplateTable(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProjectTemplateTable rename(String name) {
        return new ProjectTemplateTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProjectTemplateTable rename(Name name) {
        return new ProjectTemplateTable(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProjectTemplateTable rename(Table<?> name) {
        return new ProjectTemplateTable(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProjectTemplateTable where(Condition condition) {
        return new ProjectTemplateTable(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProjectTemplateTable where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProjectTemplateTable where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProjectTemplateTable where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProjectTemplateTable where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProjectTemplateTable where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProjectTemplateTable where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProjectTemplateTable where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProjectTemplateTable whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProjectTemplateTable whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
