/*
 * This file is generated by jOOQ.
 */
package io.cattle.platform.core.model.tables;


import io.cattle.platform.core.model.CattleTable;
import io.cattle.platform.core.model.Indexes;
import io.cattle.platform.core.model.Keys;
import io.cattle.platform.core.model.tables.AccountTable.AccountPath;
import io.cattle.platform.core.model.tables.records.ProjectMemberRecord;
import io.cattle.platform.db.jooq.converter.DataConverter;
import io.cattle.platform.db.jooq.converter.DateConverter;

import java.util.Arrays;
import java.util.Collection;
import java.util.Date;
import java.util.List;
import java.util.Map;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
public class ProjectMemberTable extends TableImpl<ProjectMemberRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>cattle.project_member</code>
     */
    public static final ProjectMemberTable PROJECT_MEMBER = new ProjectMemberTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProjectMemberRecord> getRecordType() {
        return ProjectMemberRecord.class;
    }

    /**
     * The column <code>cattle.project_member.id</code>.
     */
    public final TableField<ProjectMemberRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>cattle.project_member.name</code>.
     */
    public final TableField<ProjectMemberRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.project_member.account_id</code>.
     */
    public final TableField<ProjectMemberRecord, Long> ACCOUNT_ID = createField(DSL.name("account_id"), SQLDataType.BIGINT.defaultValue(DSL.inline("NULL", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>cattle.project_member.kind</code>.
     */
    public final TableField<ProjectMemberRecord, String> KIND = createField(DSL.name("kind"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>cattle.project_member.uuid</code>.
     */
    public final TableField<ProjectMemberRecord, String> UUID = createField(DSL.name("uuid"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>cattle.project_member.description</code>.
     */
    public final TableField<ProjectMemberRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(1024).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.project_member.state</code>.
     */
    public final TableField<ProjectMemberRecord, String> STATE = createField(DSL.name("state"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>cattle.project_member.created</code>.
     */
    public final TableField<ProjectMemberRecord, Date> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.project_member.removed</code>.
     */
    public final TableField<ProjectMemberRecord, Date> REMOVED = createField(DSL.name("removed"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.project_member.remove_time</code>.
     */
    public final TableField<ProjectMemberRecord, Date> REMOVE_TIME = createField(DSL.name("remove_time"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.project_member.data</code>.
     */
    public final TableField<ProjectMemberRecord, Map<String,Object>> DATA = createField(DSL.name("data"), SQLDataType.CLOB(16777215).defaultValue(DSL.inline("NULL", SQLDataType.CLOB)), this, "", new DataConverter());

    /**
     * The column <code>cattle.project_member.external_id</code>.
     */
    public final TableField<ProjectMemberRecord, String> EXTERNAL_ID = createField(DSL.name("external_id"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>cattle.project_member.project_id</code>.
     */
    public final TableField<ProjectMemberRecord, Long> PROJECT_ID = createField(DSL.name("project_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>cattle.project_member.external_id_type</code>.
     */
    public final TableField<ProjectMemberRecord, String> EXTERNAL_ID_TYPE = createField(DSL.name("external_id_type"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>cattle.project_member.role</code>.
     */
    public final TableField<ProjectMemberRecord, String> ROLE = createField(DSL.name("role"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private ProjectMemberTable(Name alias, Table<ProjectMemberRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ProjectMemberTable(Name alias, Table<ProjectMemberRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>cattle.project_member</code> table reference
     */
    public ProjectMemberTable(String alias) {
        this(DSL.name(alias), PROJECT_MEMBER);
    }

    /**
     * Create an aliased <code>cattle.project_member</code> table reference
     */
    public ProjectMemberTable(Name alias) {
        this(alias, PROJECT_MEMBER);
    }

    /**
     * Create a <code>cattle.project_member</code> table reference
     */
    public ProjectMemberTable() {
        this(DSL.name("project_member"), null);
    }

    public <O extends Record> ProjectMemberTable(Table<O> path, ForeignKey<O, ProjectMemberRecord> childPath, InverseForeignKey<O, ProjectMemberRecord> parentPath) {
        super(path, childPath, parentPath, PROJECT_MEMBER);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ProjectMemberPath extends ProjectMemberTable implements Path<ProjectMemberRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ProjectMemberPath(Table<O> path, ForeignKey<O, ProjectMemberRecord> childPath, InverseForeignKey<O, ProjectMemberRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ProjectMemberPath(Name alias, Table<ProjectMemberRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ProjectMemberPath as(String alias) {
            return new ProjectMemberPath(DSL.name(alias), this);
        }

        @Override
        public ProjectMemberPath as(Name alias) {
            return new ProjectMemberPath(alias, this);
        }

        @Override
        public ProjectMemberPath as(Table<?> alias) {
            return new ProjectMemberPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : CattleTable.CATTLE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.PROJECT_MEMBER_IDX_PROJECT_MEMBER_NAME, Indexes.PROJECT_MEMBER_IDX_PROJECT_MEMBER_REMOVE_TIME, Indexes.PROJECT_MEMBER_IDX_PROJECT_MEMBER_REMOVED, Indexes.PROJECT_MEMBER_IDX_PROJECT_MEMBER_STATE);
    }

    @Override
    public Identity<ProjectMemberRecord, Long> getIdentity() {
        return Internal.createIdentity(this, ID);
    }

    @Override
    public UniqueKey<ProjectMemberRecord> getPrimaryKey() {
        return Keys.KEY_PROJECT_MEMBER_PRIMARY;
    }

    @Override
    public List<UniqueKey<ProjectMemberRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_PROJECT_MEMBER_IDX_PROJECT_MEMBER_UUID);
    }

    @Override
    public List<ForeignKey<ProjectMemberRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_PROJECT_MEMBER__ACCOUNT_ID, Keys.FK_PROJECT_MEMBER__PROJECT_ID);
    }

    private transient AccountPath _fkProjectMember_AccountId;

    /**
     * Get the implicit join path to the <code>cattle.account</code> table, via
     * the <code>fk_project_member__account_id</code> key.
     */
    public AccountPath fkProjectMember_AccountId() {
        if (_fkProjectMember_AccountId == null)
            _fkProjectMember_AccountId = new AccountPath(this, Keys.FK_PROJECT_MEMBER__ACCOUNT_ID, null);

        return _fkProjectMember_AccountId;
    }

    private transient AccountPath _fkProjectMember_ProjectId;

    /**
     * Get the implicit join path to the <code>cattle.account</code> table, via
     * the <code>fk_project_member__project_id</code> key.
     */
    public AccountPath fkProjectMember_ProjectId() {
        if (_fkProjectMember_ProjectId == null)
            _fkProjectMember_ProjectId = new AccountPath(this, Keys.FK_PROJECT_MEMBER__PROJECT_ID, null);

        return _fkProjectMember_ProjectId;
    }

    @Override
    public ProjectMemberTable as(String alias) {
        return new ProjectMemberTable(DSL.name(alias), this);
    }

    @Override
    public ProjectMemberTable as(Name alias) {
        return new ProjectMemberTable(alias, this);
    }

    @Override
    public ProjectMemberTable as(Table<?> alias) {
        return new ProjectMemberTable(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProjectMemberTable rename(String name) {
        return new ProjectMemberTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProjectMemberTable rename(Name name) {
        return new ProjectMemberTable(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProjectMemberTable rename(Table<?> name) {
        return new ProjectMemberTable(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProjectMemberTable where(Condition condition) {
        return new ProjectMemberTable(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProjectMemberTable where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProjectMemberTable where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProjectMemberTable where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProjectMemberTable where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProjectMemberTable where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProjectMemberTable where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProjectMemberTable where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProjectMemberTable whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProjectMemberTable whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
