/*
 * This file is generated by jOOQ.
 */
package io.cattle.platform.core.model.tables;


import io.cattle.platform.core.model.CattleTable;
import io.cattle.platform.core.model.Indexes;
import io.cattle.platform.core.model.Keys;
import io.cattle.platform.core.model.tables.AccountTable.AccountPath;
import io.cattle.platform.core.model.tables.InstanceTable.InstancePath;
import io.cattle.platform.core.model.tables.ServiceTable.ServicePath;
import io.cattle.platform.core.model.tables.records.ServiceIndexRecord;
import io.cattle.platform.db.jooq.converter.DataConverter;
import io.cattle.platform.db.jooq.converter.DateConverter;

import java.util.Arrays;
import java.util.Collection;
import java.util.Date;
import java.util.List;
import java.util.Map;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
public class ServiceIndexTable extends TableImpl<ServiceIndexRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>cattle.service_index</code>
     */
    public static final ServiceIndexTable SERVICE_INDEX = new ServiceIndexTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ServiceIndexRecord> getRecordType() {
        return ServiceIndexRecord.class;
    }

    /**
     * The column <code>cattle.service_index.id</code>.
     */
    public final TableField<ServiceIndexRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>cattle.service_index.name</code>.
     */
    public final TableField<ServiceIndexRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.service_index.account_id</code>.
     */
    public final TableField<ServiceIndexRecord, Long> ACCOUNT_ID = createField(DSL.name("account_id"), SQLDataType.BIGINT.defaultValue(DSL.inline("NULL", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>cattle.service_index.kind</code>.
     */
    public final TableField<ServiceIndexRecord, String> KIND = createField(DSL.name("kind"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>cattle.service_index.uuid</code>.
     */
    public final TableField<ServiceIndexRecord, String> UUID = createField(DSL.name("uuid"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>cattle.service_index.description</code>.
     */
    public final TableField<ServiceIndexRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(1024).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.service_index.state</code>.
     */
    public final TableField<ServiceIndexRecord, String> STATE = createField(DSL.name("state"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>cattle.service_index.created</code>.
     */
    public final TableField<ServiceIndexRecord, Date> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.service_index.removed</code>.
     */
    public final TableField<ServiceIndexRecord, Date> REMOVED = createField(DSL.name("removed"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.service_index.remove_time</code>.
     */
    public final TableField<ServiceIndexRecord, Date> REMOVE_TIME = createField(DSL.name("remove_time"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.service_index.data</code>.
     */
    public final TableField<ServiceIndexRecord, Map<String,Object>> DATA = createField(DSL.name("data"), SQLDataType.CLOB(65535).defaultValue(DSL.inline("NULL", SQLDataType.CLOB)), this, "", new DataConverter());

    /**
     * The column <code>cattle.service_index.service_index</code>.
     */
    public final TableField<ServiceIndexRecord, String> SERVICE_INDEX_ = createField(DSL.name("service_index"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.service_index.launch_config_name</code>.
     */
    public final TableField<ServiceIndexRecord, String> LAUNCH_CONFIG_NAME = createField(DSL.name("launch_config_name"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.service_index.service_id</code>.
     */
    public final TableField<ServiceIndexRecord, Long> SERVICE_ID = createField(DSL.name("service_id"), SQLDataType.BIGINT.defaultValue(DSL.inline("NULL", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>cattle.service_index.address</code>.
     */
    public final TableField<ServiceIndexRecord, String> ADDRESS = createField(DSL.name("address"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    private ServiceIndexTable(Name alias, Table<ServiceIndexRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ServiceIndexTable(Name alias, Table<ServiceIndexRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>cattle.service_index</code> table reference
     */
    public ServiceIndexTable(String alias) {
        this(DSL.name(alias), SERVICE_INDEX);
    }

    /**
     * Create an aliased <code>cattle.service_index</code> table reference
     */
    public ServiceIndexTable(Name alias) {
        this(alias, SERVICE_INDEX);
    }

    /**
     * Create a <code>cattle.service_index</code> table reference
     */
    public ServiceIndexTable() {
        this(DSL.name("service_index"), null);
    }

    public <O extends Record> ServiceIndexTable(Table<O> path, ForeignKey<O, ServiceIndexRecord> childPath, InverseForeignKey<O, ServiceIndexRecord> parentPath) {
        super(path, childPath, parentPath, SERVICE_INDEX);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ServiceIndexPath extends ServiceIndexTable implements Path<ServiceIndexRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ServiceIndexPath(Table<O> path, ForeignKey<O, ServiceIndexRecord> childPath, InverseForeignKey<O, ServiceIndexRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ServiceIndexPath(Name alias, Table<ServiceIndexRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ServiceIndexPath as(String alias) {
            return new ServiceIndexPath(DSL.name(alias), this);
        }

        @Override
        public ServiceIndexPath as(Name alias) {
            return new ServiceIndexPath(alias, this);
        }

        @Override
        public ServiceIndexPath as(Table<?> alias) {
            return new ServiceIndexPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : CattleTable.CATTLE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.SERVICE_INDEX_IDX_SERVICE_SUFFIX_NAME, Indexes.SERVICE_INDEX_IDX_SERVICE_SUFFIX_REMOVE_TIME, Indexes.SERVICE_INDEX_IDX_SERVICE_SUFFIX_REMOVED, Indexes.SERVICE_INDEX_IDX_SERVICE_SUFFIX_STATE);
    }

    @Override
    public Identity<ServiceIndexRecord, Long> getIdentity() {
        return Internal.createIdentity(this, ID);
    }

    @Override
    public UniqueKey<ServiceIndexRecord> getPrimaryKey() {
        return Keys.KEY_SERVICE_INDEX_PRIMARY;
    }

    @Override
    public List<UniqueKey<ServiceIndexRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_SERVICE_INDEX_IDX_SERVICE_SUFFIX_UUID);
    }

    @Override
    public List<ForeignKey<ServiceIndexRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_SERVICE_SUFFIX__ACCOUNT_ID, Keys.FK_SERVICE_SUFFIX__SERVICE_ID);
    }

    private transient AccountPath _account;

    /**
     * Get the implicit join path to the <code>cattle.account</code> table.
     */
    public AccountPath account() {
        if (_account == null)
            _account = new AccountPath(this, Keys.FK_SERVICE_SUFFIX__ACCOUNT_ID, null);

        return _account;
    }

    private transient ServicePath _service;

    /**
     * Get the implicit join path to the <code>cattle.service</code> table.
     */
    public ServicePath service() {
        if (_service == null)
            _service = new ServicePath(this, Keys.FK_SERVICE_SUFFIX__SERVICE_ID, null);

        return _service;
    }

    private transient InstancePath _instance;

    /**
     * Get the implicit to-many join path to the <code>cattle.instance</code>
     * table
     */
    public InstancePath instance() {
        if (_instance == null)
            _instance = new InstancePath(this, null, Keys.FK_INSTANCE__SERVICE_INDEX_ID.getInverseKey());

        return _instance;
    }

    @Override
    public ServiceIndexTable as(String alias) {
        return new ServiceIndexTable(DSL.name(alias), this);
    }

    @Override
    public ServiceIndexTable as(Name alias) {
        return new ServiceIndexTable(alias, this);
    }

    @Override
    public ServiceIndexTable as(Table<?> alias) {
        return new ServiceIndexTable(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ServiceIndexTable rename(String name) {
        return new ServiceIndexTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ServiceIndexTable rename(Name name) {
        return new ServiceIndexTable(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ServiceIndexTable rename(Table<?> name) {
        return new ServiceIndexTable(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ServiceIndexTable where(Condition condition) {
        return new ServiceIndexTable(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ServiceIndexTable where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ServiceIndexTable where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ServiceIndexTable where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ServiceIndexTable where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ServiceIndexTable where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ServiceIndexTable where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ServiceIndexTable where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ServiceIndexTable whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ServiceIndexTable whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
