/*
 * This file is generated by jOOQ.
 */
package io.cattle.platform.core.model.tables;


import io.cattle.platform.core.model.CattleTable;
import io.cattle.platform.core.model.Indexes;
import io.cattle.platform.core.model.Keys;
import io.cattle.platform.core.model.tables.AccountTable.AccountPath;
import io.cattle.platform.core.model.tables.HealthcheckInstanceTable.HealthcheckInstancePath;
import io.cattle.platform.core.model.tables.HostTable.HostPath;
import io.cattle.platform.core.model.tables.InstanceTable.InstancePath;
import io.cattle.platform.core.model.tables.records.ServiceEventRecord;
import io.cattle.platform.db.jooq.converter.DataConverter;
import io.cattle.platform.db.jooq.converter.DateConverter;

import java.util.Arrays;
import java.util.Collection;
import java.util.Date;
import java.util.List;
import java.util.Map;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
public class ServiceEventTable extends TableImpl<ServiceEventRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>cattle.service_event</code>
     */
    public static final ServiceEventTable SERVICE_EVENT = new ServiceEventTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ServiceEventRecord> getRecordType() {
        return ServiceEventRecord.class;
    }

    /**
     * The column <code>cattle.service_event.id</code>.
     */
    public final TableField<ServiceEventRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>cattle.service_event.name</code>.
     */
    public final TableField<ServiceEventRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.service_event.account_id</code>.
     */
    public final TableField<ServiceEventRecord, Long> ACCOUNT_ID = createField(DSL.name("account_id"), SQLDataType.BIGINT.defaultValue(DSL.inline("NULL", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>cattle.service_event.kind</code>.
     */
    public final TableField<ServiceEventRecord, String> KIND = createField(DSL.name("kind"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>cattle.service_event.uuid</code>.
     */
    public final TableField<ServiceEventRecord, String> UUID = createField(DSL.name("uuid"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>cattle.service_event.description</code>.
     */
    public final TableField<ServiceEventRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(1024).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.service_event.state</code>.
     */
    public final TableField<ServiceEventRecord, String> STATE = createField(DSL.name("state"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>cattle.service_event.created</code>.
     */
    public final TableField<ServiceEventRecord, Date> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.service_event.removed</code>.
     */
    public final TableField<ServiceEventRecord, Date> REMOVED = createField(DSL.name("removed"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.service_event.remove_time</code>.
     */
    public final TableField<ServiceEventRecord, Date> REMOVE_TIME = createField(DSL.name("remove_time"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.service_event.data</code>.
     */
    public final TableField<ServiceEventRecord, Map<String,Object>> DATA = createField(DSL.name("data"), SQLDataType.CLOB(16777215).defaultValue(DSL.inline("NULL", SQLDataType.CLOB)), this, "", new DataConverter());

    /**
     * The column <code>cattle.service_event.host_id</code>.
     */
    public final TableField<ServiceEventRecord, Long> HOST_ID = createField(DSL.name("host_id"), SQLDataType.BIGINT.defaultValue(DSL.inline("NULL", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>cattle.service_event.healthcheck_uuid</code>.
     */
    public final TableField<ServiceEventRecord, String> HEALTHCHECK_UUID = createField(DSL.name("healthcheck_uuid"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.service_event.instance_id</code>.
     */
    public final TableField<ServiceEventRecord, Long> INSTANCE_ID = createField(DSL.name("instance_id"), SQLDataType.BIGINT.defaultValue(DSL.inline("NULL", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>cattle.service_event.healthcheck_instance_id</code>.
     */
    public final TableField<ServiceEventRecord, Long> HEALTHCHECK_INSTANCE_ID = createField(DSL.name("healthcheck_instance_id"), SQLDataType.BIGINT.defaultValue(DSL.inline("NULL", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>cattle.service_event.reported_health</code>.
     */
    public final TableField<ServiceEventRecord, String> REPORTED_HEALTH = createField(DSL.name("reported_health"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.service_event.external_timestamp</code>.
     */
    public final TableField<ServiceEventRecord, Integer> EXTERNAL_TIMESTAMP = createField(DSL.name("external_timestamp"), SQLDataType.INTEGER.defaultValue(DSL.inline("NULL", SQLDataType.INTEGER)), this, "");

    private ServiceEventTable(Name alias, Table<ServiceEventRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ServiceEventTable(Name alias, Table<ServiceEventRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>cattle.service_event</code> table reference
     */
    public ServiceEventTable(String alias) {
        this(DSL.name(alias), SERVICE_EVENT);
    }

    /**
     * Create an aliased <code>cattle.service_event</code> table reference
     */
    public ServiceEventTable(Name alias) {
        this(alias, SERVICE_EVENT);
    }

    /**
     * Create a <code>cattle.service_event</code> table reference
     */
    public ServiceEventTable() {
        this(DSL.name("service_event"), null);
    }

    public <O extends Record> ServiceEventTable(Table<O> path, ForeignKey<O, ServiceEventRecord> childPath, InverseForeignKey<O, ServiceEventRecord> parentPath) {
        super(path, childPath, parentPath, SERVICE_EVENT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ServiceEventPath extends ServiceEventTable implements Path<ServiceEventRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ServiceEventPath(Table<O> path, ForeignKey<O, ServiceEventRecord> childPath, InverseForeignKey<O, ServiceEventRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ServiceEventPath(Name alias, Table<ServiceEventRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ServiceEventPath as(String alias) {
            return new ServiceEventPath(DSL.name(alias), this);
        }

        @Override
        public ServiceEventPath as(Name alias) {
            return new ServiceEventPath(alias, this);
        }

        @Override
        public ServiceEventPath as(Table<?> alias) {
            return new ServiceEventPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : CattleTable.CATTLE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.SERVICE_EVENT_IDX_SERVICE_EVENT_NAME, Indexes.SERVICE_EVENT_IDX_SERVICE_EVENT_REMOVE_TIME, Indexes.SERVICE_EVENT_IDX_SERVICE_EVENT_REMOVED, Indexes.SERVICE_EVENT_IDX_SERVICE_EVENT_STATE);
    }

    @Override
    public Identity<ServiceEventRecord, Long> getIdentity() {
        return Internal.createIdentity(this, ID);
    }

    @Override
    public UniqueKey<ServiceEventRecord> getPrimaryKey() {
        return Keys.KEY_SERVICE_EVENT_PRIMARY;
    }

    @Override
    public List<UniqueKey<ServiceEventRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_SERVICE_EVENT_IDX_SERVICE_EVENT_UUID);
    }

    @Override
    public List<ForeignKey<ServiceEventRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_SERVICE_EVENT__ACCOUNT_ID, Keys.FK_SERVICE_EVENT__HEALTHCHECK_INSTANCE_ID, Keys.FK_SERVICE_EVENT__HOST_ID, Keys.FK_SERVICE_EVENT__INSTANCE_ID);
    }

    private transient AccountPath _account;

    /**
     * Get the implicit join path to the <code>cattle.account</code> table.
     */
    public AccountPath account() {
        if (_account == null)
            _account = new AccountPath(this, Keys.FK_SERVICE_EVENT__ACCOUNT_ID, null);

        return _account;
    }

    private transient HealthcheckInstancePath _healthcheckInstance;

    /**
     * Get the implicit join path to the
     * <code>cattle.healthcheck_instance</code> table.
     */
    public HealthcheckInstancePath healthcheckInstance() {
        if (_healthcheckInstance == null)
            _healthcheckInstance = new HealthcheckInstancePath(this, Keys.FK_SERVICE_EVENT__HEALTHCHECK_INSTANCE_ID, null);

        return _healthcheckInstance;
    }

    private transient HostPath _host;

    /**
     * Get the implicit join path to the <code>cattle.host</code> table.
     */
    public HostPath host() {
        if (_host == null)
            _host = new HostPath(this, Keys.FK_SERVICE_EVENT__HOST_ID, null);

        return _host;
    }

    private transient InstancePath _instance;

    /**
     * Get the implicit join path to the <code>cattle.instance</code> table.
     */
    public InstancePath instance() {
        if (_instance == null)
            _instance = new InstancePath(this, Keys.FK_SERVICE_EVENT__INSTANCE_ID, null);

        return _instance;
    }

    @Override
    public ServiceEventTable as(String alias) {
        return new ServiceEventTable(DSL.name(alias), this);
    }

    @Override
    public ServiceEventTable as(Name alias) {
        return new ServiceEventTable(alias, this);
    }

    @Override
    public ServiceEventTable as(Table<?> alias) {
        return new ServiceEventTable(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ServiceEventTable rename(String name) {
        return new ServiceEventTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ServiceEventTable rename(Name name) {
        return new ServiceEventTable(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ServiceEventTable rename(Table<?> name) {
        return new ServiceEventTable(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ServiceEventTable where(Condition condition) {
        return new ServiceEventTable(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ServiceEventTable where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ServiceEventTable where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ServiceEventTable where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ServiceEventTable where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ServiceEventTable where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ServiceEventTable where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ServiceEventTable where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ServiceEventTable whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ServiceEventTable whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
