/*
 * This file is generated by jOOQ.
 */
package io.cattle.platform.core.model.tables;


import io.cattle.platform.core.model.CattleTable;
import io.cattle.platform.core.model.Indexes;
import io.cattle.platform.core.model.Keys;
import io.cattle.platform.core.model.tables.records.SettingRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
public class SettingTable extends TableImpl<SettingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>cattle.setting</code>
     */
    public static final SettingTable SETTING = new SettingTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SettingRecord> getRecordType() {
        return SettingRecord.class;
    }

    /**
     * The column <code>cattle.setting.id</code>.
     */
    public final TableField<SettingRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>cattle.setting.name</code>.
     */
    public final TableField<SettingRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>cattle.setting.value</code>.
     */
    public final TableField<SettingRecord, String> VALUE = createField(DSL.name("value"), SQLDataType.CLOB(16777215).nullable(false), this, "");

    private SettingTable(Name alias, Table<SettingRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private SettingTable(Name alias, Table<SettingRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>cattle.setting</code> table reference
     */
    public SettingTable(String alias) {
        this(DSL.name(alias), SETTING);
    }

    /**
     * Create an aliased <code>cattle.setting</code> table reference
     */
    public SettingTable(Name alias) {
        this(alias, SETTING);
    }

    /**
     * Create a <code>cattle.setting</code> table reference
     */
    public SettingTable() {
        this(DSL.name("setting"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : CattleTable.CATTLE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.SETTING_IDX_SETTING_NAME);
    }

    @Override
    public Identity<SettingRecord, Long> getIdentity() {
        return Internal.createIdentity(this, ID);
    }

    @Override
    public UniqueKey<SettingRecord> getPrimaryKey() {
        return Keys.KEY_SETTING_PRIMARY;
    }

    @Override
    public SettingTable as(String alias) {
        return new SettingTable(DSL.name(alias), this);
    }

    @Override
    public SettingTable as(Name alias) {
        return new SettingTable(alias, this);
    }

    @Override
    public SettingTable as(Table<?> alias) {
        return new SettingTable(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SettingTable rename(String name) {
        return new SettingTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SettingTable rename(Name name) {
        return new SettingTable(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SettingTable rename(Table<?> name) {
        return new SettingTable(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SettingTable where(Condition condition) {
        return new SettingTable(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SettingTable where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SettingTable where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SettingTable where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SettingTable where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SettingTable where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SettingTable where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SettingTable where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SettingTable whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SettingTable whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
