/*
 * This file is generated by jOOQ.
 */
package io.cattle.platform.core.model.tables;


import io.cattle.platform.core.model.CattleTable;
import io.cattle.platform.core.model.Indexes;
import io.cattle.platform.core.model.Keys;
import io.cattle.platform.core.model.tables.AccountTable.AccountPath;
import io.cattle.platform.core.model.tables.BackupTable.BackupPath;
import io.cattle.platform.core.model.tables.VolumeTable.VolumePath;
import io.cattle.platform.core.model.tables.records.SnapshotRecord;
import io.cattle.platform.db.jooq.converter.DataConverter;
import io.cattle.platform.db.jooq.converter.DateConverter;

import java.util.Arrays;
import java.util.Collection;
import java.util.Date;
import java.util.List;
import java.util.Map;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
public class SnapshotTable extends TableImpl<SnapshotRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>cattle.snapshot</code>
     */
    public static final SnapshotTable SNAPSHOT = new SnapshotTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SnapshotRecord> getRecordType() {
        return SnapshotRecord.class;
    }

    /**
     * The column <code>cattle.snapshot.id</code>.
     */
    public final TableField<SnapshotRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>cattle.snapshot.name</code>.
     */
    public final TableField<SnapshotRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.snapshot.account_id</code>.
     */
    public final TableField<SnapshotRecord, Long> ACCOUNT_ID = createField(DSL.name("account_id"), SQLDataType.BIGINT.defaultValue(DSL.inline("NULL", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>cattle.snapshot.kind</code>.
     */
    public final TableField<SnapshotRecord, String> KIND = createField(DSL.name("kind"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>cattle.snapshot.uuid</code>.
     */
    public final TableField<SnapshotRecord, String> UUID = createField(DSL.name("uuid"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>cattle.snapshot.description</code>.
     */
    public final TableField<SnapshotRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(1024).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.snapshot.state</code>.
     */
    public final TableField<SnapshotRecord, String> STATE = createField(DSL.name("state"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>cattle.snapshot.created</code>.
     */
    public final TableField<SnapshotRecord, Date> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.snapshot.removed</code>.
     */
    public final TableField<SnapshotRecord, Date> REMOVED = createField(DSL.name("removed"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.snapshot.remove_time</code>.
     */
    public final TableField<SnapshotRecord, Date> REMOVE_TIME = createField(DSL.name("remove_time"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.snapshot.data</code>.
     */
    public final TableField<SnapshotRecord, Map<String,Object>> DATA = createField(DSL.name("data"), SQLDataType.CLOB(16777215).defaultValue(DSL.inline("NULL", SQLDataType.CLOB)), this, "", new DataConverter());

    /**
     * The column <code>cattle.snapshot.volume_id</code>.
     */
    public final TableField<SnapshotRecord, Long> VOLUME_ID = createField(DSL.name("volume_id"), SQLDataType.BIGINT.defaultValue(DSL.inline("NULL", SQLDataType.BIGINT)), this, "");

    private SnapshotTable(Name alias, Table<SnapshotRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private SnapshotTable(Name alias, Table<SnapshotRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>cattle.snapshot</code> table reference
     */
    public SnapshotTable(String alias) {
        this(DSL.name(alias), SNAPSHOT);
    }

    /**
     * Create an aliased <code>cattle.snapshot</code> table reference
     */
    public SnapshotTable(Name alias) {
        this(alias, SNAPSHOT);
    }

    /**
     * Create a <code>cattle.snapshot</code> table reference
     */
    public SnapshotTable() {
        this(DSL.name("snapshot"), null);
    }

    public <O extends Record> SnapshotTable(Table<O> path, ForeignKey<O, SnapshotRecord> childPath, InverseForeignKey<O, SnapshotRecord> parentPath) {
        super(path, childPath, parentPath, SNAPSHOT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SnapshotPath extends SnapshotTable implements Path<SnapshotRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SnapshotPath(Table<O> path, ForeignKey<O, SnapshotRecord> childPath, InverseForeignKey<O, SnapshotRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SnapshotPath(Name alias, Table<SnapshotRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SnapshotPath as(String alias) {
            return new SnapshotPath(DSL.name(alias), this);
        }

        @Override
        public SnapshotPath as(Name alias) {
            return new SnapshotPath(alias, this);
        }

        @Override
        public SnapshotPath as(Table<?> alias) {
            return new SnapshotPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : CattleTable.CATTLE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.SNAPSHOT_IDX_SNAPSHOT_NAME, Indexes.SNAPSHOT_IDX_SNAPSHOT_REMOVE_TIME, Indexes.SNAPSHOT_IDX_SNAPSHOT_REMOVED, Indexes.SNAPSHOT_IDX_SNAPSHOT_STATE);
    }

    @Override
    public Identity<SnapshotRecord, Long> getIdentity() {
        return Internal.createIdentity(this, ID);
    }

    @Override
    public UniqueKey<SnapshotRecord> getPrimaryKey() {
        return Keys.KEY_SNAPSHOT_PRIMARY;
    }

    @Override
    public List<UniqueKey<SnapshotRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_SNAPSHOT_IDX_SNAPSHOT_UUID);
    }

    @Override
    public List<ForeignKey<SnapshotRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_SNAPSHOT__ACCOUNT_ID, Keys.FK_SNAPSHOT__VOLUME_ID);
    }

    private transient AccountPath _account;

    /**
     * Get the implicit join path to the <code>cattle.account</code> table.
     */
    public AccountPath account() {
        if (_account == null)
            _account = new AccountPath(this, Keys.FK_SNAPSHOT__ACCOUNT_ID, null);

        return _account;
    }

    private transient VolumePath _volume;

    /**
     * Get the implicit join path to the <code>cattle.volume</code> table.
     */
    public VolumePath volume() {
        if (_volume == null)
            _volume = new VolumePath(this, Keys.FK_SNAPSHOT__VOLUME_ID, null);

        return _volume;
    }

    private transient BackupPath _backup;

    /**
     * Get the implicit to-many join path to the <code>cattle.backup</code>
     * table
     */
    public BackupPath backup() {
        if (_backup == null)
            _backup = new BackupPath(this, null, Keys.FK_BACKUP__SNAPSHOT_ID.getInverseKey());

        return _backup;
    }

    @Override
    public SnapshotTable as(String alias) {
        return new SnapshotTable(DSL.name(alias), this);
    }

    @Override
    public SnapshotTable as(Name alias) {
        return new SnapshotTable(alias, this);
    }

    @Override
    public SnapshotTable as(Table<?> alias) {
        return new SnapshotTable(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SnapshotTable rename(String name) {
        return new SnapshotTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SnapshotTable rename(Name name) {
        return new SnapshotTable(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SnapshotTable rename(Table<?> name) {
        return new SnapshotTable(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SnapshotTable where(Condition condition) {
        return new SnapshotTable(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SnapshotTable where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SnapshotTable where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SnapshotTable where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SnapshotTable where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SnapshotTable where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SnapshotTable where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SnapshotTable where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SnapshotTable whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SnapshotTable whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
