/*
 * This file is generated by jOOQ.
 */
package io.cattle.platform.core.model.tables;


import io.cattle.platform.core.model.CattleTable;
import io.cattle.platform.core.model.Keys;
import io.cattle.platform.core.model.tables.TaskInstanceTable.TaskInstancePath;
import io.cattle.platform.core.model.tables.records.TaskRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
public class TaskTable extends TableImpl<TaskRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>cattle.task</code>
     */
    public static final TaskTable TASK = new TaskTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TaskRecord> getRecordType() {
        return TaskRecord.class;
    }

    /**
     * The column <code>cattle.task.id</code>.
     */
    public final TableField<TaskRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>cattle.task.name</code>.
     */
    public final TableField<TaskRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    private TaskTable(Name alias, Table<TaskRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TaskTable(Name alias, Table<TaskRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>cattle.task</code> table reference
     */
    public TaskTable(String alias) {
        this(DSL.name(alias), TASK);
    }

    /**
     * Create an aliased <code>cattle.task</code> table reference
     */
    public TaskTable(Name alias) {
        this(alias, TASK);
    }

    /**
     * Create a <code>cattle.task</code> table reference
     */
    public TaskTable() {
        this(DSL.name("task"), null);
    }

    public <O extends Record> TaskTable(Table<O> path, ForeignKey<O, TaskRecord> childPath, InverseForeignKey<O, TaskRecord> parentPath) {
        super(path, childPath, parentPath, TASK);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TaskPath extends TaskTable implements Path<TaskRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TaskPath(Table<O> path, ForeignKey<O, TaskRecord> childPath, InverseForeignKey<O, TaskRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TaskPath(Name alias, Table<TaskRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TaskPath as(String alias) {
            return new TaskPath(DSL.name(alias), this);
        }

        @Override
        public TaskPath as(Name alias) {
            return new TaskPath(alias, this);
        }

        @Override
        public TaskPath as(Table<?> alias) {
            return new TaskPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : CattleTable.CATTLE;
    }

    @Override
    public Identity<TaskRecord, Long> getIdentity() {
        return Internal.createIdentity(this, ID);
    }

    @Override
    public UniqueKey<TaskRecord> getPrimaryKey() {
        return Keys.KEY_TASK_PRIMARY;
    }

    @Override
    public List<UniqueKey<TaskRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_TASK_IDX_TASK_NAME);
    }

    private transient TaskInstancePath _taskInstance;

    /**
     * Get the implicit to-many join path to the
     * <code>cattle.task_instance</code> table
     */
    public TaskInstancePath taskInstance() {
        if (_taskInstance == null)
            _taskInstance = new TaskInstancePath(this, null, Keys.FK_TASK_INSTANCE__TASK_ID.getInverseKey());

        return _taskInstance;
    }

    @Override
    public TaskTable as(String alias) {
        return new TaskTable(DSL.name(alias), this);
    }

    @Override
    public TaskTable as(Name alias) {
        return new TaskTable(alias, this);
    }

    @Override
    public TaskTable as(Table<?> alias) {
        return new TaskTable(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TaskTable rename(String name) {
        return new TaskTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TaskTable rename(Name name) {
        return new TaskTable(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TaskTable rename(Table<?> name) {
        return new TaskTable(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TaskTable where(Condition condition) {
        return new TaskTable(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TaskTable where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TaskTable where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TaskTable where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TaskTable where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TaskTable where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TaskTable where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TaskTable where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TaskTable whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TaskTable whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
