/*
 * This file is generated by jOOQ.
 */
package io.cattle.platform.core.model.tables;


import io.cattle.platform.core.model.CattleTable;
import io.cattle.platform.core.model.Indexes;
import io.cattle.platform.core.model.Keys;
import io.cattle.platform.core.model.tables.StoragePoolTable.StoragePoolPath;
import io.cattle.platform.core.model.tables.VolumeTable.VolumePath;
import io.cattle.platform.core.model.tables.records.VolumeStoragePoolMapRecord;
import io.cattle.platform.db.jooq.converter.DataConverter;
import io.cattle.platform.db.jooq.converter.DateConverter;

import java.util.Arrays;
import java.util.Collection;
import java.util.Date;
import java.util.List;
import java.util.Map;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
public class VolumeStoragePoolMapTable extends TableImpl<VolumeStoragePoolMapRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>cattle.volume_storage_pool_map</code>
     */
    public static final VolumeStoragePoolMapTable VOLUME_STORAGE_POOL_MAP = new VolumeStoragePoolMapTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VolumeStoragePoolMapRecord> getRecordType() {
        return VolumeStoragePoolMapRecord.class;
    }

    /**
     * The column <code>cattle.volume_storage_pool_map.id</code>.
     */
    public final TableField<VolumeStoragePoolMapRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>cattle.volume_storage_pool_map.name</code>.
     */
    public final TableField<VolumeStoragePoolMapRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.volume_storage_pool_map.kind</code>.
     */
    public final TableField<VolumeStoragePoolMapRecord, String> KIND = createField(DSL.name("kind"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>cattle.volume_storage_pool_map.uuid</code>.
     */
    public final TableField<VolumeStoragePoolMapRecord, String> UUID = createField(DSL.name("uuid"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>cattle.volume_storage_pool_map.description</code>.
     */
    public final TableField<VolumeStoragePoolMapRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(1024).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.volume_storage_pool_map.state</code>.
     */
    public final TableField<VolumeStoragePoolMapRecord, String> STATE = createField(DSL.name("state"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>cattle.volume_storage_pool_map.created</code>.
     */
    public final TableField<VolumeStoragePoolMapRecord, Date> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.volume_storage_pool_map.removed</code>.
     */
    public final TableField<VolumeStoragePoolMapRecord, Date> REMOVED = createField(DSL.name("removed"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.volume_storage_pool_map.remove_time</code>.
     */
    public final TableField<VolumeStoragePoolMapRecord, Date> REMOVE_TIME = createField(DSL.name("remove_time"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.volume_storage_pool_map.data</code>.
     */
    public final TableField<VolumeStoragePoolMapRecord, Map<String,Object>> DATA = createField(DSL.name("data"), SQLDataType.CLOB(16777215).defaultValue(DSL.inline("NULL", SQLDataType.CLOB)), this, "", new DataConverter());

    /**
     * The column <code>cattle.volume_storage_pool_map.volume_id</code>.
     */
    public final TableField<VolumeStoragePoolMapRecord, Long> VOLUME_ID = createField(DSL.name("volume_id"), SQLDataType.BIGINT.defaultValue(DSL.inline("NULL", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>cattle.volume_storage_pool_map.storage_pool_id</code>.
     */
    public final TableField<VolumeStoragePoolMapRecord, Long> STORAGE_POOL_ID = createField(DSL.name("storage_pool_id"), SQLDataType.BIGINT.defaultValue(DSL.inline("NULL", SQLDataType.BIGINT)), this, "");

    private VolumeStoragePoolMapTable(Name alias, Table<VolumeStoragePoolMapRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private VolumeStoragePoolMapTable(Name alias, Table<VolumeStoragePoolMapRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>cattle.volume_storage_pool_map</code> table
     * reference
     */
    public VolumeStoragePoolMapTable(String alias) {
        this(DSL.name(alias), VOLUME_STORAGE_POOL_MAP);
    }

    /**
     * Create an aliased <code>cattle.volume_storage_pool_map</code> table
     * reference
     */
    public VolumeStoragePoolMapTable(Name alias) {
        this(alias, VOLUME_STORAGE_POOL_MAP);
    }

    /**
     * Create a <code>cattle.volume_storage_pool_map</code> table reference
     */
    public VolumeStoragePoolMapTable() {
        this(DSL.name("volume_storage_pool_map"), null);
    }

    public <O extends Record> VolumeStoragePoolMapTable(Table<O> path, ForeignKey<O, VolumeStoragePoolMapRecord> childPath, InverseForeignKey<O, VolumeStoragePoolMapRecord> parentPath) {
        super(path, childPath, parentPath, VOLUME_STORAGE_POOL_MAP);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class VolumeStoragePoolMapPath extends VolumeStoragePoolMapTable implements Path<VolumeStoragePoolMapRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> VolumeStoragePoolMapPath(Table<O> path, ForeignKey<O, VolumeStoragePoolMapRecord> childPath, InverseForeignKey<O, VolumeStoragePoolMapRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private VolumeStoragePoolMapPath(Name alias, Table<VolumeStoragePoolMapRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public VolumeStoragePoolMapPath as(String alias) {
            return new VolumeStoragePoolMapPath(DSL.name(alias), this);
        }

        @Override
        public VolumeStoragePoolMapPath as(Name alias) {
            return new VolumeStoragePoolMapPath(alias, this);
        }

        @Override
        public VolumeStoragePoolMapPath as(Table<?> alias) {
            return new VolumeStoragePoolMapPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : CattleTable.CATTLE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.VOLUME_STORAGE_POOL_MAP_IDX_VOLUME_STORAGE_POOL_MAP_NAME, Indexes.VOLUME_STORAGE_POOL_MAP_IDX_VOLUME_STORAGE_POOL_MAP_REMOVE_TIME, Indexes.VOLUME_STORAGE_POOL_MAP_IDX_VOLUME_STORAGE_POOL_MAP_REMOVED, Indexes.VOLUME_STORAGE_POOL_MAP_IDX_VOLUME_STORAGE_POOL_MAP_STATE);
    }

    @Override
    public Identity<VolumeStoragePoolMapRecord, Long> getIdentity() {
        return Internal.createIdentity(this, ID);
    }

    @Override
    public UniqueKey<VolumeStoragePoolMapRecord> getPrimaryKey() {
        return Keys.KEY_VOLUME_STORAGE_POOL_MAP_PRIMARY;
    }

    @Override
    public List<UniqueKey<VolumeStoragePoolMapRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_VOLUME_STORAGE_POOL_MAP_IDX_VOLUME_STORAGE_POOL_MAP_UUID);
    }

    @Override
    public List<ForeignKey<VolumeStoragePoolMapRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_VOLUME_STORAGE_POOL_MAP__STORAGE_POOL_ID, Keys.FK_VOLUME_STORAGE_POOL_MAP__VOLUME_ID);
    }

    private transient StoragePoolPath _storagePool;

    /**
     * Get the implicit join path to the <code>cattle.storage_pool</code> table.
     */
    public StoragePoolPath storagePool() {
        if (_storagePool == null)
            _storagePool = new StoragePoolPath(this, Keys.FK_VOLUME_STORAGE_POOL_MAP__STORAGE_POOL_ID, null);

        return _storagePool;
    }

    private transient VolumePath _volume;

    /**
     * Get the implicit join path to the <code>cattle.volume</code> table.
     */
    public VolumePath volume() {
        if (_volume == null)
            _volume = new VolumePath(this, Keys.FK_VOLUME_STORAGE_POOL_MAP__VOLUME_ID, null);

        return _volume;
    }

    @Override
    public VolumeStoragePoolMapTable as(String alias) {
        return new VolumeStoragePoolMapTable(DSL.name(alias), this);
    }

    @Override
    public VolumeStoragePoolMapTable as(Name alias) {
        return new VolumeStoragePoolMapTable(alias, this);
    }

    @Override
    public VolumeStoragePoolMapTable as(Table<?> alias) {
        return new VolumeStoragePoolMapTable(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public VolumeStoragePoolMapTable rename(String name) {
        return new VolumeStoragePoolMapTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VolumeStoragePoolMapTable rename(Name name) {
        return new VolumeStoragePoolMapTable(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public VolumeStoragePoolMapTable rename(Table<?> name) {
        return new VolumeStoragePoolMapTable(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VolumeStoragePoolMapTable where(Condition condition) {
        return new VolumeStoragePoolMapTable(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VolumeStoragePoolMapTable where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VolumeStoragePoolMapTable where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VolumeStoragePoolMapTable where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VolumeStoragePoolMapTable where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VolumeStoragePoolMapTable where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VolumeStoragePoolMapTable where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VolumeStoragePoolMapTable where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VolumeStoragePoolMapTable whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VolumeStoragePoolMapTable whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
