/*
 * This file is generated by jOOQ.
 */
package io.cattle.platform.core.model.tables;


import io.cattle.platform.core.model.CattleTable;
import io.cattle.platform.core.model.Indexes;
import io.cattle.platform.core.model.Keys;
import io.cattle.platform.core.model.tables.AccountTable.AccountPath;
import io.cattle.platform.core.model.tables.StackTable.EnvironmentPath;
import io.cattle.platform.core.model.tables.VolumeTable.VolumePath;
import io.cattle.platform.core.model.tables.records.VolumeTemplateRecord;
import io.cattle.platform.db.jooq.converter.DataConverter;
import io.cattle.platform.db.jooq.converter.DateConverter;

import java.util.Arrays;
import java.util.Collection;
import java.util.Date;
import java.util.List;
import java.util.Map;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
public class VolumeTemplateTable extends TableImpl<VolumeTemplateRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>cattle.volume_template</code>
     */
    public static final VolumeTemplateTable VOLUME_TEMPLATE = new VolumeTemplateTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VolumeTemplateRecord> getRecordType() {
        return VolumeTemplateRecord.class;
    }

    /**
     * The column <code>cattle.volume_template.id</code>.
     */
    public final TableField<VolumeTemplateRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>cattle.volume_template.name</code>.
     */
    public final TableField<VolumeTemplateRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.volume_template.account_id</code>.
     */
    public final TableField<VolumeTemplateRecord, Long> ACCOUNT_ID = createField(DSL.name("account_id"), SQLDataType.BIGINT.defaultValue(DSL.inline("NULL", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>cattle.volume_template.kind</code>.
     */
    public final TableField<VolumeTemplateRecord, String> KIND = createField(DSL.name("kind"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>cattle.volume_template.uuid</code>.
     */
    public final TableField<VolumeTemplateRecord, String> UUID = createField(DSL.name("uuid"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>cattle.volume_template.description</code>.
     */
    public final TableField<VolumeTemplateRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(1024).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.volume_template.state</code>.
     */
    public final TableField<VolumeTemplateRecord, String> STATE = createField(DSL.name("state"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>cattle.volume_template.created</code>.
     */
    public final TableField<VolumeTemplateRecord, Date> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.volume_template.removed</code>.
     */
    public final TableField<VolumeTemplateRecord, Date> REMOVED = createField(DSL.name("removed"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.volume_template.remove_time</code>.
     */
    public final TableField<VolumeTemplateRecord, Date> REMOVE_TIME = createField(DSL.name("remove_time"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.volume_template.data</code>.
     */
    public final TableField<VolumeTemplateRecord, Map<String,Object>> DATA = createField(DSL.name("data"), SQLDataType.CLOB(65535).defaultValue(DSL.inline("NULL", SQLDataType.CLOB)), this, "", new DataConverter());

    /**
     * The column <code>cattle.volume_template.driver</code>.
     */
    public final TableField<VolumeTemplateRecord, String> DRIVER = createField(DSL.name("driver"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.volume_template.environment_id</code>.
     */
    public final TableField<VolumeTemplateRecord, Long> STACK_ID = createField(DSL.name("environment_id"), SQLDataType.BIGINT.defaultValue(DSL.inline("NULL", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>cattle.volume_template.external</code>.
     */
    public final TableField<VolumeTemplateRecord, Boolean> EXTERNAL = createField(DSL.name("external"), SQLDataType.BIT.nullable(false).defaultValue(DSL.inline("b'0'", SQLDataType.BIT)), this, "");

    /**
     * The column <code>cattle.volume_template.per_container</code>.
     */
    public final TableField<VolumeTemplateRecord, Boolean> PER_CONTAINER = createField(DSL.name("per_container"), SQLDataType.BIT.nullable(false).defaultValue(DSL.inline("b'0'", SQLDataType.BIT)), this, "");

    private VolumeTemplateTable(Name alias, Table<VolumeTemplateRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private VolumeTemplateTable(Name alias, Table<VolumeTemplateRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>cattle.volume_template</code> table reference
     */
    public VolumeTemplateTable(String alias) {
        this(DSL.name(alias), VOLUME_TEMPLATE);
    }

    /**
     * Create an aliased <code>cattle.volume_template</code> table reference
     */
    public VolumeTemplateTable(Name alias) {
        this(alias, VOLUME_TEMPLATE);
    }

    /**
     * Create a <code>cattle.volume_template</code> table reference
     */
    public VolumeTemplateTable() {
        this(DSL.name("volume_template"), null);
    }

    public <O extends Record> VolumeTemplateTable(Table<O> path, ForeignKey<O, VolumeTemplateRecord> childPath, InverseForeignKey<O, VolumeTemplateRecord> parentPath) {
        super(path, childPath, parentPath, VOLUME_TEMPLATE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class VolumeTemplatePath extends VolumeTemplateTable implements Path<VolumeTemplateRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> VolumeTemplatePath(Table<O> path, ForeignKey<O, VolumeTemplateRecord> childPath, InverseForeignKey<O, VolumeTemplateRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private VolumeTemplatePath(Name alias, Table<VolumeTemplateRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public VolumeTemplatePath as(String alias) {
            return new VolumeTemplatePath(DSL.name(alias), this);
        }

        @Override
        public VolumeTemplatePath as(Name alias) {
            return new VolumeTemplatePath(alias, this);
        }

        @Override
        public VolumeTemplatePath as(Table<?> alias) {
            return new VolumeTemplatePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : CattleTable.CATTLE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.VOLUME_TEMPLATE_IDX_VOLUME_TEMPLATE_NAME, Indexes.VOLUME_TEMPLATE_IDX_VOLUME_TEMPLATE_REMOVE_TIME, Indexes.VOLUME_TEMPLATE_IDX_VOLUME_TEMPLATE_REMOVED, Indexes.VOLUME_TEMPLATE_IDX_VOLUME_TEMPLATE_STATE);
    }

    @Override
    public Identity<VolumeTemplateRecord, Long> getIdentity() {
        return Internal.createIdentity(this, ID);
    }

    @Override
    public UniqueKey<VolumeTemplateRecord> getPrimaryKey() {
        return Keys.KEY_VOLUME_TEMPLATE_PRIMARY;
    }

    @Override
    public List<UniqueKey<VolumeTemplateRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_VOLUME_TEMPLATE_IDX_VOLUME_TEMPLATE_UUID);
    }

    @Override
    public List<ForeignKey<VolumeTemplateRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_VOLUME_TEMPLATE__ACCOUNT_ID, Keys.FK_VOLUME_TEMPLATE__ENVIRONMENT_ID);
    }

    private transient AccountPath _account;

    /**
     * Get the implicit join path to the <code>cattle.account</code> table.
     */
    public AccountPath account() {
        if (_account == null)
            _account = new AccountPath(this, Keys.FK_VOLUME_TEMPLATE__ACCOUNT_ID, null);

        return _account;
    }

    private transient EnvironmentPath _environment;

    /**
     * Get the implicit join path to the <code>cattle.environment</code> table.
     */
    public EnvironmentPath environment() {
        if (_environment == null)
            _environment = new EnvironmentPath(this, Keys.FK_VOLUME_TEMPLATE__ENVIRONMENT_ID, null);

        return _environment;
    }

    private transient VolumePath _volume;

    /**
     * Get the implicit to-many join path to the <code>cattle.volume</code>
     * table
     */
    public VolumePath volume() {
        if (_volume == null)
            _volume = new VolumePath(this, null, Keys.FK_VOLUME__VOLUME_TEMPLATE_ID.getInverseKey());

        return _volume;
    }

    @Override
    public VolumeTemplateTable as(String alias) {
        return new VolumeTemplateTable(DSL.name(alias), this);
    }

    @Override
    public VolumeTemplateTable as(Name alias) {
        return new VolumeTemplateTable(alias, this);
    }

    @Override
    public VolumeTemplateTable as(Table<?> alias) {
        return new VolumeTemplateTable(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public VolumeTemplateTable rename(String name) {
        return new VolumeTemplateTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VolumeTemplateTable rename(Name name) {
        return new VolumeTemplateTable(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public VolumeTemplateTable rename(Table<?> name) {
        return new VolumeTemplateTable(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VolumeTemplateTable where(Condition condition) {
        return new VolumeTemplateTable(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VolumeTemplateTable where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VolumeTemplateTable where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VolumeTemplateTable where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VolumeTemplateTable where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VolumeTemplateTable where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VolumeTemplateTable where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VolumeTemplateTable where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VolumeTemplateTable whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VolumeTemplateTable whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
