/*
 * This file is generated by jOOQ.
 */
package io.cattle.platform.core.model.tables;


import io.cattle.platform.core.model.CattleTable;
import io.cattle.platform.core.model.Indexes;
import io.cattle.platform.core.model.Keys;
import io.cattle.platform.core.model.tables.AccountTable.AccountPath;
import io.cattle.platform.core.model.tables.AgentTable.AgentPath;
import io.cattle.platform.core.model.tables.HostTable.HostPath;
import io.cattle.platform.core.model.tables.InstanceTable.InstancePath;
import io.cattle.platform.core.model.tables.StoragePoolTable.StoragePoolPath;
import io.cattle.platform.core.model.tables.VolumeTable.VolumePath;
import io.cattle.platform.core.model.tables.records.ZoneRecord;
import io.cattle.platform.db.jooq.converter.DataConverter;
import io.cattle.platform.db.jooq.converter.DateConverter;

import java.util.Arrays;
import java.util.Collection;
import java.util.Date;
import java.util.List;
import java.util.Map;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
public class ZoneTable extends TableImpl<ZoneRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>cattle.zone</code>
     */
    public static final ZoneTable ZONE = new ZoneTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ZoneRecord> getRecordType() {
        return ZoneRecord.class;
    }

    /**
     * The column <code>cattle.zone.id</code>.
     */
    public final TableField<ZoneRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>cattle.zone.name</code>.
     */
    public final TableField<ZoneRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.zone.account_id</code>.
     */
    public final TableField<ZoneRecord, Long> ACCOUNT_ID = createField(DSL.name("account_id"), SQLDataType.BIGINT.defaultValue(DSL.inline("NULL", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>cattle.zone.kind</code>.
     */
    public final TableField<ZoneRecord, String> KIND = createField(DSL.name("kind"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>cattle.zone.uuid</code>.
     */
    public final TableField<ZoneRecord, String> UUID = createField(DSL.name("uuid"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>cattle.zone.description</code>.
     */
    public final TableField<ZoneRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(1024).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cattle.zone.state</code>.
     */
    public final TableField<ZoneRecord, String> STATE = createField(DSL.name("state"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>cattle.zone.created</code>.
     */
    public final TableField<ZoneRecord, Date> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.zone.removed</code>.
     */
    public final TableField<ZoneRecord, Date> REMOVED = createField(DSL.name("removed"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.zone.remove_time</code>.
     */
    public final TableField<ZoneRecord, Date> REMOVE_TIME = createField(DSL.name("remove_time"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

    /**
     * The column <code>cattle.zone.data</code>.
     */
    public final TableField<ZoneRecord, Map<String,Object>> DATA = createField(DSL.name("data"), SQLDataType.CLOB(16777215).defaultValue(DSL.inline("NULL", SQLDataType.CLOB)), this, "", new DataConverter());

    private ZoneTable(Name alias, Table<ZoneRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ZoneTable(Name alias, Table<ZoneRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>cattle.zone</code> table reference
     */
    public ZoneTable(String alias) {
        this(DSL.name(alias), ZONE);
    }

    /**
     * Create an aliased <code>cattle.zone</code> table reference
     */
    public ZoneTable(Name alias) {
        this(alias, ZONE);
    }

    /**
     * Create a <code>cattle.zone</code> table reference
     */
    public ZoneTable() {
        this(DSL.name("zone"), null);
    }

    public <O extends Record> ZoneTable(Table<O> path, ForeignKey<O, ZoneRecord> childPath, InverseForeignKey<O, ZoneRecord> parentPath) {
        super(path, childPath, parentPath, ZONE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ZonePath extends ZoneTable implements Path<ZoneRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ZonePath(Table<O> path, ForeignKey<O, ZoneRecord> childPath, InverseForeignKey<O, ZoneRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ZonePath(Name alias, Table<ZoneRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ZonePath as(String alias) {
            return new ZonePath(DSL.name(alias), this);
        }

        @Override
        public ZonePath as(Name alias) {
            return new ZonePath(alias, this);
        }

        @Override
        public ZonePath as(Table<?> alias) {
            return new ZonePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : CattleTable.CATTLE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.ZONE_IDX_ZONE_NAME, Indexes.ZONE_IDX_ZONE_REMOVE_TIME, Indexes.ZONE_IDX_ZONE_REMOVED, Indexes.ZONE_IDX_ZONE_STATE);
    }

    @Override
    public Identity<ZoneRecord, Long> getIdentity() {
        return Internal.createIdentity(this, ID);
    }

    @Override
    public UniqueKey<ZoneRecord> getPrimaryKey() {
        return Keys.KEY_ZONE_PRIMARY;
    }

    @Override
    public List<UniqueKey<ZoneRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_ZONE_IDX_ZONE_UUID);
    }

    @Override
    public List<ForeignKey<ZoneRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_ZONE__ACCOUNT_ID);
    }

    private transient AccountPath _account;

    /**
     * Get the implicit join path to the <code>cattle.account</code> table.
     */
    public AccountPath account() {
        if (_account == null)
            _account = new AccountPath(this, Keys.FK_ZONE__ACCOUNT_ID, null);

        return _account;
    }

    private transient AgentPath _agent;

    /**
     * Get the implicit to-many join path to the <code>cattle.agent</code> table
     */
    public AgentPath agent() {
        if (_agent == null)
            _agent = new AgentPath(this, null, Keys.FK_AGENT__ZONE_ID.getInverseKey());

        return _agent;
    }

    private transient HostPath _host;

    /**
     * Get the implicit to-many join path to the <code>cattle.host</code> table
     */
    public HostPath host() {
        if (_host == null)
            _host = new HostPath(this, null, Keys.FK_HOST__ZONE_ID.getInverseKey());

        return _host;
    }

    private transient InstancePath _instance;

    /**
     * Get the implicit to-many join path to the <code>cattle.instance</code>
     * table
     */
    public InstancePath instance() {
        if (_instance == null)
            _instance = new InstancePath(this, null, Keys.FK_INSTANCE__ZONE_ID.getInverseKey());

        return _instance;
    }

    private transient StoragePoolPath _storagePool;

    /**
     * Get the implicit to-many join path to the
     * <code>cattle.storage_pool</code> table
     */
    public StoragePoolPath storagePool() {
        if (_storagePool == null)
            _storagePool = new StoragePoolPath(this, null, Keys.FK_STORAGE_POOL__ZONE_ID.getInverseKey());

        return _storagePool;
    }

    private transient VolumePath _volume;

    /**
     * Get the implicit to-many join path to the <code>cattle.volume</code>
     * table
     */
    public VolumePath volume() {
        if (_volume == null)
            _volume = new VolumePath(this, null, Keys.FK_VOLUME__ZONE_ID.getInverseKey());

        return _volume;
    }

    @Override
    public ZoneTable as(String alias) {
        return new ZoneTable(DSL.name(alias), this);
    }

    @Override
    public ZoneTable as(Name alias) {
        return new ZoneTable(alias, this);
    }

    @Override
    public ZoneTable as(Table<?> alias) {
        return new ZoneTable(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ZoneTable rename(String name) {
        return new ZoneTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ZoneTable rename(Name name) {
        return new ZoneTable(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ZoneTable rename(Table<?> name) {
        return new ZoneTable(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ZoneTable where(Condition condition) {
        return new ZoneTable(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ZoneTable where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ZoneTable where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ZoneTable where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ZoneTable where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ZoneTable where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ZoneTable where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ZoneTable where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ZoneTable whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ZoneTable whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
