/*
 * This file is generated by jOOQ.
 */
package io.cattle.platform.core.model;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import java.io.Serializable;
import java.util.Date;
import java.util.Map;


/**
 * This class is generated by jOOQ.
 */
@Entity
@Table(
    name = "account",
    schema = "cattle",
    uniqueConstraints = {
        @UniqueConstraint(name = "KEY_account_idx_account_uuid", columnNames = { "uuid" })
    },
    indexes = {
        @Index(name = "idx_account_name", columnList = "name ASC"),
        @Index(name = "idx_account_remove_time", columnList = "remove_time ASC"),
        @Index(name = "idx_account_removed", columnList = "removed ASC"),
        @Index(name = "idx_account_state", columnList = "state ASC"),
        @Index(name = "idx_external_ids", columnList = "external_id ASC, external_id_type ASC")
    }
)
public interface Account extends Serializable {

    /**
     * Setter for <code>cattle.account.id</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>cattle.account.id</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    public Long getId();

    /**
     * Setter for <code>cattle.account.name</code>.
     */
    public void setName(String value);

    /**
     * Getter for <code>cattle.account.name</code>.
     */
    @Column(name = "name", length = 255)
    public String getName();

    /**
     * Setter for <code>cattle.account.kind</code>.
     */
    public void setKind(String value);

    /**
     * Getter for <code>cattle.account.kind</code>.
     */
    @Column(name = "kind", nullable = false, length = 255)
    public String getKind();

    /**
     * Setter for <code>cattle.account.uuid</code>.
     */
    public void setUuid(String value);

    /**
     * Getter for <code>cattle.account.uuid</code>.
     */
    @Column(name = "uuid", nullable = false, length = 128)
    public String getUuid();

    /**
     * Setter for <code>cattle.account.description</code>.
     */
    public void setDescription(String value);

    /**
     * Getter for <code>cattle.account.description</code>.
     */
    @Column(name = "description", length = 1024)
    public String getDescription();

    /**
     * Setter for <code>cattle.account.state</code>.
     */
    public void setState(String value);

    /**
     * Getter for <code>cattle.account.state</code>.
     */
    @Column(name = "state", nullable = false, length = 128)
    public String getState();

    /**
     * Setter for <code>cattle.account.created</code>.
     */
    public void setCreated(Date value);

    /**
     * Getter for <code>cattle.account.created</code>.
     */
    @Column(name = "created")
    public Date getCreated();

    /**
     * Setter for <code>cattle.account.removed</code>.
     */
    public void setRemoved(Date value);

    /**
     * Getter for <code>cattle.account.removed</code>.
     */
    @Column(name = "removed")
    public Date getRemoved();

    /**
     * Setter for <code>cattle.account.remove_time</code>.
     */
    public void setRemoveTime(Date value);

    /**
     * Getter for <code>cattle.account.remove_time</code>.
     */
    @Column(name = "remove_time")
    public Date getRemoveTime();

    /**
     * Setter for <code>cattle.account.data</code>.
     */
    public void setData(Map<String,Object> value);

    /**
     * Getter for <code>cattle.account.data</code>.
     */
    @Column(name = "data", length = 16777215)
    public Map<String,Object> getData();

    /**
     * Setter for <code>cattle.account.external_id</code>.
     */
    public void setExternalId(String value);

    /**
     * Getter for <code>cattle.account.external_id</code>.
     */
    @Column(name = "external_id", length = 255)
    public String getExternalId();

    /**
     * Setter for <code>cattle.account.external_id_type</code>.
     */
    public void setExternalIdType(String value);

    /**
     * Getter for <code>cattle.account.external_id_type</code>.
     */
    @Column(name = "external_id_type", length = 128)
    public String getExternalIdType();

    /**
     * Setter for <code>cattle.account.health_state</code>.
     */
    public void setHealthState(String value);

    /**
     * Getter for <code>cattle.account.health_state</code>.
     */
    @Column(name = "health_state", length = 128)
    public String getHealthState();

    /**
     * Setter for <code>cattle.account.project_template_id</code>.
     */
    public void setProjectTemplateId(Long value);

    /**
     * Getter for <code>cattle.account.project_template_id</code>.
     */
    @Column(name = "project_template_id")
    public Long getProjectTemplateId();

    /**
     * Setter for <code>cattle.account.default_network_id</code>.
     */
    public void setDefaultNetworkId(Long value);

    /**
     * Getter for <code>cattle.account.default_network_id</code>.
     */
    @Column(name = "default_network_id")
    public Long getDefaultNetworkId();

    /**
     * Setter for <code>cattle.account.version</code>.
     */
    public void setVersion(String value);

    /**
     * Getter for <code>cattle.account.version</code>.
     */
    @Column(name = "version", length = 128)
    public String getVersion();

    /**
     * Setter for <code>cattle.account.revision</code>.
     */
    public void setRevision(Long value);

    /**
     * Getter for <code>cattle.account.revision</code>.
     */
    @Column(name = "revision", nullable = false)
    public Long getRevision();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface Account
     */
    public void from(Account from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface Account
     */
    public <E extends Account> E into(E into);
}
