/*
 * This file is generated by jOOQ.
 */
package io.cattle.platform.core.model;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import java.io.Serializable;
import java.util.Date;
import java.util.Map;


/**
 * This class is generated by jOOQ.
 */
@Entity
@Table(
    name = "backup_target",
    schema = "cattle",
    uniqueConstraints = {
        @UniqueConstraint(name = "KEY_backup_target_idx_backup_target_uuid", columnNames = { "uuid" })
    },
    indexes = {
        @Index(name = "idx_backup_target_name", columnList = "name ASC"),
        @Index(name = "idx_backup_target_remove_time", columnList = "remove_time ASC"),
        @Index(name = "idx_backup_target_removed", columnList = "removed ASC"),
        @Index(name = "idx_backup_target_state", columnList = "state ASC")
    }
)
public interface BackupTarget extends Serializable {

    /**
     * Setter for <code>cattle.backup_target.id</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>cattle.backup_target.id</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    public Long getId();

    /**
     * Setter for <code>cattle.backup_target.name</code>.
     */
    public void setName(String value);

    /**
     * Getter for <code>cattle.backup_target.name</code>.
     */
    @Column(name = "name", length = 255)
    public String getName();

    /**
     * Setter for <code>cattle.backup_target.account_id</code>.
     */
    public void setAccountId(Long value);

    /**
     * Getter for <code>cattle.backup_target.account_id</code>.
     */
    @Column(name = "account_id")
    public Long getAccountId();

    /**
     * Setter for <code>cattle.backup_target.kind</code>.
     */
    public void setKind(String value);

    /**
     * Getter for <code>cattle.backup_target.kind</code>.
     */
    @Column(name = "kind", nullable = false, length = 255)
    public String getKind();

    /**
     * Setter for <code>cattle.backup_target.uuid</code>.
     */
    public void setUuid(String value);

    /**
     * Getter for <code>cattle.backup_target.uuid</code>.
     */
    @Column(name = "uuid", nullable = false, length = 128)
    public String getUuid();

    /**
     * Setter for <code>cattle.backup_target.description</code>.
     */
    public void setDescription(String value);

    /**
     * Getter for <code>cattle.backup_target.description</code>.
     */
    @Column(name = "description", length = 1024)
    public String getDescription();

    /**
     * Setter for <code>cattle.backup_target.state</code>.
     */
    public void setState(String value);

    /**
     * Getter for <code>cattle.backup_target.state</code>.
     */
    @Column(name = "state", nullable = false, length = 128)
    public String getState();

    /**
     * Setter for <code>cattle.backup_target.created</code>.
     */
    public void setCreated(Date value);

    /**
     * Getter for <code>cattle.backup_target.created</code>.
     */
    @Column(name = "created")
    public Date getCreated();

    /**
     * Setter for <code>cattle.backup_target.removed</code>.
     */
    public void setRemoved(Date value);

    /**
     * Getter for <code>cattle.backup_target.removed</code>.
     */
    @Column(name = "removed")
    public Date getRemoved();

    /**
     * Setter for <code>cattle.backup_target.remove_time</code>.
     */
    public void setRemoveTime(Date value);

    /**
     * Getter for <code>cattle.backup_target.remove_time</code>.
     */
    @Column(name = "remove_time")
    public Date getRemoveTime();

    /**
     * Setter for <code>cattle.backup_target.data</code>.
     */
    public void setData(Map<String,Object> value);

    /**
     * Getter for <code>cattle.backup_target.data</code>.
     */
    @Column(name = "data", length = 65535)
    public Map<String,Object> getData();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface BackupTarget
     */
    public void from(BackupTarget from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface BackupTarget
     */
    public <E extends BackupTarget> E into(E into);
}
