/*
 * This file is generated by jOOQ.
 */
package io.cattle.platform.core.model;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;

import java.io.Serializable;
import java.util.Date;
import java.util.Map;


/**
 * This class is generated by jOOQ.
 */
@Entity
@Table(
    name = "container_event",
    schema = "cattle",
    indexes = {
        @Index(name = "idx_container_event_created", columnList = "created ASC"),
        @Index(name = "idx_container_event_external_timestamp", columnList = "external_timestamp ASC"),
        @Index(name = "idx_container_event_host_id_state", columnList = "host_id ASC, state ASC"),
        @Index(name = "idx_container_event_state", columnList = "state ASC")
    }
)
public interface ContainerEvent extends Serializable {

    /**
     * Setter for <code>cattle.container_event.id</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>cattle.container_event.id</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    public Long getId();

    /**
     * Setter for <code>cattle.container_event.account_id</code>.
     */
    public void setAccountId(Long value);

    /**
     * Getter for <code>cattle.container_event.account_id</code>.
     */
    @Column(name = "account_id")
    public Long getAccountId();

    /**
     * Setter for <code>cattle.container_event.kind</code>.
     */
    public void setKind(String value);

    /**
     * Getter for <code>cattle.container_event.kind</code>.
     */
    @Column(name = "kind", nullable = false, length = 255)
    public String getKind();

    /**
     * Setter for <code>cattle.container_event.state</code>.
     */
    public void setState(String value);

    /**
     * Getter for <code>cattle.container_event.state</code>.
     */
    @Column(name = "state", nullable = false, length = 128)
    public String getState();

    /**
     * Setter for <code>cattle.container_event.created</code>.
     */
    public void setCreated(Date value);

    /**
     * Getter for <code>cattle.container_event.created</code>.
     */
    @Column(name = "created")
    public Date getCreated();

    /**
     * Setter for <code>cattle.container_event.data</code>.
     */
    public void setData(Map<String,Object> value);

    /**
     * Getter for <code>cattle.container_event.data</code>.
     */
    @Column(name = "data", length = 16777215)
    public Map<String,Object> getData();

    /**
     * Setter for <code>cattle.container_event.external_id</code>.
     */
    public void setExternalId(String value);

    /**
     * Getter for <code>cattle.container_event.external_id</code>.
     */
    @Column(name = "external_id", length = 255)
    public String getExternalId();

    /**
     * Setter for <code>cattle.container_event.external_status</code>.
     */
    public void setExternalStatus(String value);

    /**
     * Getter for <code>cattle.container_event.external_status</code>.
     */
    @Column(name = "external_status", length = 255)
    public String getExternalStatus();

    /**
     * Setter for <code>cattle.container_event.external_from</code>.
     */
    public void setExternalFrom(String value);

    /**
     * Getter for <code>cattle.container_event.external_from</code>.
     */
    @Column(name = "external_from", length = 255)
    public String getExternalFrom();

    /**
     * Setter for <code>cattle.container_event.external_timestamp</code>.
     */
    public void setExternalTimestamp(Long value);

    /**
     * Getter for <code>cattle.container_event.external_timestamp</code>.
     */
    @Column(name = "external_timestamp")
    public Long getExternalTimestamp();

    /**
     * Setter for <code>cattle.container_event.reported_host_uuid</code>.
     */
    public void setReportedHostUuid(String value);

    /**
     * Getter for <code>cattle.container_event.reported_host_uuid</code>.
     */
    @Column(name = "reported_host_uuid", length = 255)
    public String getReportedHostUuid();

    /**
     * Setter for <code>cattle.container_event.host_id</code>.
     */
    public void setHostId(Long value);

    /**
     * Getter for <code>cattle.container_event.host_id</code>.
     */
    @Column(name = "host_id")
    public Long getHostId();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface ContainerEvent
     */
    public void from(ContainerEvent from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface ContainerEvent
     */
    public <E extends ContainerEvent> E into(E into);
}
