/*
 * This file is generated by jOOQ.
 */
package io.cattle.platform.core.model;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import java.io.Serializable;
import java.util.Date;
import java.util.Map;


/**
 * This class is generated by jOOQ.
 */
@Entity
@Table(
    name = "host_template",
    schema = "cattle",
    uniqueConstraints = {
        @UniqueConstraint(name = "KEY_host_template_idx_host_template_uuid", columnNames = { "uuid" })
    },
    indexes = {
        @Index(name = "idx_host_template_name", columnList = "name ASC"),
        @Index(name = "idx_host_template_remove_time", columnList = "remove_time ASC"),
        @Index(name = "idx_host_template_removed", columnList = "removed ASC"),
        @Index(name = "idx_host_template_state", columnList = "state ASC")
    }
)
public interface HostTemplate extends Serializable {

    /**
     * Setter for <code>cattle.host_template.id</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>cattle.host_template.id</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    public Long getId();

    /**
     * Setter for <code>cattle.host_template.name</code>.
     */
    public void setName(String value);

    /**
     * Getter for <code>cattle.host_template.name</code>.
     */
    @Column(name = "name", length = 255)
    public String getName();

    /**
     * Setter for <code>cattle.host_template.account_id</code>.
     */
    public void setAccountId(Long value);

    /**
     * Getter for <code>cattle.host_template.account_id</code>.
     */
    @Column(name = "account_id")
    public Long getAccountId();

    /**
     * Setter for <code>cattle.host_template.kind</code>.
     */
    public void setKind(String value);

    /**
     * Getter for <code>cattle.host_template.kind</code>.
     */
    @Column(name = "kind", nullable = false, length = 255)
    public String getKind();

    /**
     * Setter for <code>cattle.host_template.uuid</code>.
     */
    public void setUuid(String value);

    /**
     * Getter for <code>cattle.host_template.uuid</code>.
     */
    @Column(name = "uuid", nullable = false, length = 128)
    public String getUuid();

    /**
     * Setter for <code>cattle.host_template.description</code>.
     */
    public void setDescription(String value);

    /**
     * Getter for <code>cattle.host_template.description</code>.
     */
    @Column(name = "description", length = 1024)
    public String getDescription();

    /**
     * Setter for <code>cattle.host_template.state</code>.
     */
    public void setState(String value);

    /**
     * Getter for <code>cattle.host_template.state</code>.
     */
    @Column(name = "state", nullable = false, length = 128)
    public String getState();

    /**
     * Setter for <code>cattle.host_template.created</code>.
     */
    public void setCreated(Date value);

    /**
     * Getter for <code>cattle.host_template.created</code>.
     */
    @Column(name = "created")
    public Date getCreated();

    /**
     * Setter for <code>cattle.host_template.removed</code>.
     */
    public void setRemoved(Date value);

    /**
     * Getter for <code>cattle.host_template.removed</code>.
     */
    @Column(name = "removed")
    public Date getRemoved();

    /**
     * Setter for <code>cattle.host_template.remove_time</code>.
     */
    public void setRemoveTime(Date value);

    /**
     * Getter for <code>cattle.host_template.remove_time</code>.
     */
    @Column(name = "remove_time")
    public Date getRemoveTime();

    /**
     * Setter for <code>cattle.host_template.data</code>.
     */
    public void setData(Map<String,Object> value);

    /**
     * Getter for <code>cattle.host_template.data</code>.
     */
    @Column(name = "data", length = 16777215)
    public Map<String,Object> getData();

    /**
     * Setter for <code>cattle.host_template.driver</code>.
     */
    public void setDriver(String value);

    /**
     * Getter for <code>cattle.host_template.driver</code>.
     */
    @Column(name = "driver", length = 255)
    public String getDriver();

    /**
     * Setter for <code>cattle.host_template.flavor_prefix</code>.
     */
    public void setFlavorPrefix(String value);

    /**
     * Getter for <code>cattle.host_template.flavor_prefix</code>.
     */
    @Column(name = "flavor_prefix", length = 255)
    public String getFlavorPrefix();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface HostTemplate
     */
    public void from(HostTemplate from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface HostTemplate
     */
    public <E extends HostTemplate> E into(E into);
}
