/*
 * This file is generated by jOOQ.
 */
package io.cattle.platform.core.model;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import java.io.Serializable;
import java.util.Date;
import java.util.Map;


/**
 * This class is generated by jOOQ.
 */
@Entity
@Table(
    name = "ip_address",
    schema = "cattle",
    uniqueConstraints = {
        @UniqueConstraint(name = "KEY_ip_address_idx_ip_address_uuid", columnNames = { "uuid" })
    },
    indexes = {
        @Index(name = "idx_ip_address_is_public", columnList = "is_public ASC"),
        @Index(name = "idx_ip_address_name", columnList = "name ASC"),
        @Index(name = "idx_ip_address_remove_time", columnList = "remove_time ASC"),
        @Index(name = "idx_ip_address_removed", columnList = "removed ASC"),
        @Index(name = "idx_ip_address_state", columnList = "state ASC")
    }
)
public interface IpAddress extends Serializable {

    /**
     * Setter for <code>cattle.ip_address.id</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>cattle.ip_address.id</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    public Long getId();

    /**
     * Setter for <code>cattle.ip_address.name</code>.
     */
    public void setName(String value);

    /**
     * Getter for <code>cattle.ip_address.name</code>.
     */
    @Column(name = "name", length = 255)
    public String getName();

    /**
     * Setter for <code>cattle.ip_address.account_id</code>.
     */
    public void setAccountId(Long value);

    /**
     * Getter for <code>cattle.ip_address.account_id</code>.
     */
    @Column(name = "account_id")
    public Long getAccountId();

    /**
     * Setter for <code>cattle.ip_address.kind</code>.
     */
    public void setKind(String value);

    /**
     * Getter for <code>cattle.ip_address.kind</code>.
     */
    @Column(name = "kind", nullable = false, length = 255)
    public String getKind();

    /**
     * Setter for <code>cattle.ip_address.uuid</code>.
     */
    public void setUuid(String value);

    /**
     * Getter for <code>cattle.ip_address.uuid</code>.
     */
    @Column(name = "uuid", nullable = false, length = 128)
    public String getUuid();

    /**
     * Setter for <code>cattle.ip_address.description</code>.
     */
    public void setDescription(String value);

    /**
     * Getter for <code>cattle.ip_address.description</code>.
     */
    @Column(name = "description", length = 1024)
    public String getDescription();

    /**
     * Setter for <code>cattle.ip_address.state</code>.
     */
    public void setState(String value);

    /**
     * Getter for <code>cattle.ip_address.state</code>.
     */
    @Column(name = "state", nullable = false, length = 128)
    public String getState();

    /**
     * Setter for <code>cattle.ip_address.created</code>.
     */
    public void setCreated(Date value);

    /**
     * Getter for <code>cattle.ip_address.created</code>.
     */
    @Column(name = "created")
    public Date getCreated();

    /**
     * Setter for <code>cattle.ip_address.removed</code>.
     */
    public void setRemoved(Date value);

    /**
     * Getter for <code>cattle.ip_address.removed</code>.
     */
    @Column(name = "removed")
    public Date getRemoved();

    /**
     * Setter for <code>cattle.ip_address.remove_time</code>.
     */
    public void setRemoveTime(Date value);

    /**
     * Getter for <code>cattle.ip_address.remove_time</code>.
     */
    @Column(name = "remove_time")
    public Date getRemoveTime();

    /**
     * Setter for <code>cattle.ip_address.data</code>.
     */
    public void setData(Map<String,Object> value);

    /**
     * Getter for <code>cattle.ip_address.data</code>.
     */
    @Column(name = "data", length = 16777215)
    public Map<String,Object> getData();

    /**
     * Setter for <code>cattle.ip_address.address</code>.
     */
    public void setAddress(String value);

    /**
     * Getter for <code>cattle.ip_address.address</code>.
     */
    @Column(name = "address", length = 255)
    public String getAddress();

    /**
     * Setter for <code>cattle.ip_address.subnet_id</code>.
     */
    public void setSubnetId(Long value);

    /**
     * Getter for <code>cattle.ip_address.subnet_id</code>.
     */
    @Column(name = "subnet_id")
    public Long getSubnetId();

    /**
     * Setter for <code>cattle.ip_address.network_id</code>.
     */
    public void setNetworkId(Long value);

    /**
     * Getter for <code>cattle.ip_address.network_id</code>.
     */
    @Column(name = "network_id")
    public Long getNetworkId();

    /**
     * Setter for <code>cattle.ip_address.is_public</code>.
     */
    public void setIsPublic(Boolean value);

    /**
     * Getter for <code>cattle.ip_address.is_public</code>.
     */
    @Column(name = "is_public", nullable = false)
    public Boolean getIsPublic();

    /**
     * Setter for <code>cattle.ip_address.role</code>.
     */
    public void setRole(String value);

    /**
     * Getter for <code>cattle.ip_address.role</code>.
     */
    @Column(name = "role", length = 128)
    public String getRole();

    /**
     * Setter for <code>cattle.ip_address.hostname</code>.
     */
    public void setHostname(String value);

    /**
     * Getter for <code>cattle.ip_address.hostname</code>.
     */
    @Column(name = "hostname", length = 255)
    public String getHostname();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IpAddress
     */
    public void from(IpAddress from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IpAddress
     */
    public <E extends IpAddress> E into(E into);
}
