/*
 * This file is generated by jOOQ.
 */
package io.cattle.platform.core.model;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import java.io.Serializable;
import java.util.Date;
import java.util.Map;


/**
 * This class is generated by jOOQ.
 */
@Entity
@Table(
    name = "process_execution",
    schema = "cattle",
    uniqueConstraints = {
        @UniqueConstraint(name = "KEY_process_execution_idx_process_execution__uuid", columnNames = { "uuid" })
    },
    indexes = {
        @Index(name = "idx_processs_execution_created_time", columnList = "created ASC")
    }
)
public interface ProcessExecution extends Serializable {

    /**
     * Setter for <code>cattle.process_execution.id</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>cattle.process_execution.id</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    public Long getId();

    /**
     * Setter for <code>cattle.process_execution.process_instance_id</code>.
     */
    public void setProcessInstanceId(Long value);

    /**
     * Getter for <code>cattle.process_execution.process_instance_id</code>.
     */
    @Column(name = "process_instance_id", nullable = false)
    public Long getProcessInstanceId();

    /**
     * Setter for <code>cattle.process_execution.uuid</code>.
     */
    public void setUuid(String value);

    /**
     * Getter for <code>cattle.process_execution.uuid</code>.
     */
    @Column(name = "uuid", nullable = false, length = 128)
    public String getUuid();

    /**
     * Setter for <code>cattle.process_execution.log</code>.
     */
    public void setLog(Map<String,Object> value);

    /**
     * Getter for <code>cattle.process_execution.log</code>.
     */
    @Column(name = "log", length = 16777215)
    public Map<String,Object> getLog();

    /**
     * Setter for <code>cattle.process_execution.created</code>.
     */
    public void setCreated(Date value);

    /**
     * Getter for <code>cattle.process_execution.created</code>.
     */
    @Column(name = "created")
    public Date getCreated();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface ProcessExecution
     */
    public void from(ProcessExecution from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface ProcessExecution
     */
    public <E extends ProcessExecution> E into(E into);
}
