/*
 * This file is generated by jOOQ.
 */
package io.cattle.platform.core.model;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import java.io.Serializable;
import java.util.Date;
import java.util.Map;


/**
 * This class is generated by jOOQ.
 */
@Entity
@Table(
    name = "region",
    schema = "cattle",
    uniqueConstraints = {
        @UniqueConstraint(name = "KEY_region_idx_region_uuid", columnNames = { "uuid" })
    },
    indexes = {
        @Index(name = "idx_region_name", columnList = "name ASC"),
        @Index(name = "idx_region_remove_time", columnList = "remove_time ASC"),
        @Index(name = "idx_region_removed", columnList = "removed ASC"),
        @Index(name = "idx_region_state", columnList = "state ASC")
    }
)
public interface Region extends Serializable {

    /**
     * Setter for <code>cattle.region.id</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>cattle.region.id</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    public Long getId();

    /**
     * Setter for <code>cattle.region.name</code>.
     */
    public void setName(String value);

    /**
     * Getter for <code>cattle.region.name</code>.
     */
    @Column(name = "name", length = 255)
    public String getName();

    /**
     * Setter for <code>cattle.region.account_id</code>.
     */
    public void setAccountId(Long value);

    /**
     * Getter for <code>cattle.region.account_id</code>.
     */
    @Column(name = "account_id")
    public Long getAccountId();

    /**
     * Setter for <code>cattle.region.kind</code>.
     */
    public void setKind(String value);

    /**
     * Getter for <code>cattle.region.kind</code>.
     */
    @Column(name = "kind", nullable = false, length = 255)
    public String getKind();

    /**
     * Setter for <code>cattle.region.uuid</code>.
     */
    public void setUuid(String value);

    /**
     * Getter for <code>cattle.region.uuid</code>.
     */
    @Column(name = "uuid", nullable = false, length = 128)
    public String getUuid();

    /**
     * Setter for <code>cattle.region.description</code>.
     */
    public void setDescription(String value);

    /**
     * Getter for <code>cattle.region.description</code>.
     */
    @Column(name = "description", length = 1024)
    public String getDescription();

    /**
     * Setter for <code>cattle.region.state</code>.
     */
    public void setState(String value);

    /**
     * Getter for <code>cattle.region.state</code>.
     */
    @Column(name = "state", nullable = false, length = 128)
    public String getState();

    /**
     * Setter for <code>cattle.region.created</code>.
     */
    public void setCreated(Date value);

    /**
     * Getter for <code>cattle.region.created</code>.
     */
    @Column(name = "created")
    public Date getCreated();

    /**
     * Setter for <code>cattle.region.removed</code>.
     */
    public void setRemoved(Date value);

    /**
     * Getter for <code>cattle.region.removed</code>.
     */
    @Column(name = "removed")
    public Date getRemoved();

    /**
     * Setter for <code>cattle.region.remove_time</code>.
     */
    public void setRemoveTime(Date value);

    /**
     * Getter for <code>cattle.region.remove_time</code>.
     */
    @Column(name = "remove_time")
    public Date getRemoveTime();

    /**
     * Setter for <code>cattle.region.data</code>.
     */
    public void setData(Map<String,Object> value);

    /**
     * Getter for <code>cattle.region.data</code>.
     */
    @Column(name = "data", length = 65535)
    public Map<String,Object> getData();

    /**
     * Setter for <code>cattle.region.url</code>.
     */
    public void setUrl(String value);

    /**
     * Getter for <code>cattle.region.url</code>.
     */
    @Column(name = "url", length = 255)
    public String getUrl();

    /**
     * Setter for <code>cattle.region.public_value</code>.
     */
    public void setPublicValue(String value);

    /**
     * Getter for <code>cattle.region.public_value</code>.
     */
    @Column(name = "public_value", length = 255)
    public String getPublicValue();

    /**
     * Setter for <code>cattle.region.secret_value</code>.
     */
    public void setSecretValue(String value);

    /**
     * Getter for <code>cattle.region.secret_value</code>.
     */
    @Column(name = "secret_value", length = 255)
    public String getSecretValue();

    /**
     * Setter for <code>cattle.region.local</code>.
     */
    public void setLocal(Boolean value);

    /**
     * Getter for <code>cattle.region.local</code>.
     */
    @Column(name = "local", nullable = false)
    public Boolean getLocal();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface Region
     */
    public void from(Region from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface Region
     */
    public <E extends Region> E into(E into);
}
