/*
 * This file is generated by jOOQ.
 */
package io.cattle.platform.core.model;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import java.io.Serializable;
import java.util.Date;
import java.util.Map;


/**
 * This class is generated by jOOQ.
 */
@Entity
@Table(
    name = "resource_pool",
    schema = "cattle",
    uniqueConstraints = {
        @UniqueConstraint(name = "KEY_resource_pool_idx_pool_item2", columnNames = { "pool_type", "pool_id", "qualifier", "item" }),
        @UniqueConstraint(name = "KEY_resource_pool_idx_resource_pool_uuid", columnNames = { "uuid" })
    },
    indexes = {
        @Index(name = "idx_pool_owner2", columnList = "pool_type ASC, pool_id ASC, qualifier ASC, owner_type ASC, owner_id ASC"),
        @Index(name = "idx_resource_pool_name", columnList = "name ASC"),
        @Index(name = "idx_resource_pool_remove_time", columnList = "remove_time ASC"),
        @Index(name = "idx_resource_pool_removed", columnList = "removed ASC"),
        @Index(name = "idx_resource_pool_state", columnList = "state ASC")
    }
)
public interface ResourcePool extends Serializable {

    /**
     * Setter for <code>cattle.resource_pool.id</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>cattle.resource_pool.id</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    public Long getId();

    /**
     * Setter for <code>cattle.resource_pool.name</code>.
     */
    public void setName(String value);

    /**
     * Getter for <code>cattle.resource_pool.name</code>.
     */
    @Column(name = "name", length = 255)
    public String getName();

    /**
     * Setter for <code>cattle.resource_pool.account_id</code>.
     */
    public void setAccountId(Long value);

    /**
     * Getter for <code>cattle.resource_pool.account_id</code>.
     */
    @Column(name = "account_id")
    public Long getAccountId();

    /**
     * Setter for <code>cattle.resource_pool.kind</code>.
     */
    public void setKind(String value);

    /**
     * Getter for <code>cattle.resource_pool.kind</code>.
     */
    @Column(name = "kind", nullable = false, length = 255)
    public String getKind();

    /**
     * Setter for <code>cattle.resource_pool.uuid</code>.
     */
    public void setUuid(String value);

    /**
     * Getter for <code>cattle.resource_pool.uuid</code>.
     */
    @Column(name = "uuid", nullable = false, length = 128)
    public String getUuid();

    /**
     * Setter for <code>cattle.resource_pool.description</code>.
     */
    public void setDescription(String value);

    /**
     * Getter for <code>cattle.resource_pool.description</code>.
     */
    @Column(name = "description", length = 1024)
    public String getDescription();

    /**
     * Setter for <code>cattle.resource_pool.state</code>.
     */
    public void setState(String value);

    /**
     * Getter for <code>cattle.resource_pool.state</code>.
     */
    @Column(name = "state", nullable = false, length = 128)
    public String getState();

    /**
     * Setter for <code>cattle.resource_pool.created</code>.
     */
    public void setCreated(Date value);

    /**
     * Getter for <code>cattle.resource_pool.created</code>.
     */
    @Column(name = "created")
    public Date getCreated();

    /**
     * Setter for <code>cattle.resource_pool.removed</code>.
     */
    public void setRemoved(Date value);

    /**
     * Getter for <code>cattle.resource_pool.removed</code>.
     */
    @Column(name = "removed")
    public Date getRemoved();

    /**
     * Setter for <code>cattle.resource_pool.remove_time</code>.
     */
    public void setRemoveTime(Date value);

    /**
     * Getter for <code>cattle.resource_pool.remove_time</code>.
     */
    @Column(name = "remove_time")
    public Date getRemoveTime();

    /**
     * Setter for <code>cattle.resource_pool.data</code>.
     */
    public void setData(Map<String,Object> value);

    /**
     * Getter for <code>cattle.resource_pool.data</code>.
     */
    @Column(name = "data", length = 16777215)
    public Map<String,Object> getData();

    /**
     * Setter for <code>cattle.resource_pool.pool_type</code>.
     */
    public void setPoolType(String value);

    /**
     * Getter for <code>cattle.resource_pool.pool_type</code>.
     */
    @Column(name = "pool_type", length = 255)
    public String getPoolType();

    /**
     * Setter for <code>cattle.resource_pool.pool_id</code>.
     */
    public void setPoolId(Long value);

    /**
     * Getter for <code>cattle.resource_pool.pool_id</code>.
     */
    @Column(name = "pool_id")
    public Long getPoolId();

    /**
     * Setter for <code>cattle.resource_pool.item</code>.
     */
    public void setItem(String value);

    /**
     * Getter for <code>cattle.resource_pool.item</code>.
     */
    @Column(name = "item", length = 255)
    public String getItem();

    /**
     * Setter for <code>cattle.resource_pool.owner_type</code>.
     */
    public void setOwnerType(String value);

    /**
     * Getter for <code>cattle.resource_pool.owner_type</code>.
     */
    @Column(name = "owner_type", length = 255)
    public String getOwnerType();

    /**
     * Setter for <code>cattle.resource_pool.owner_id</code>.
     */
    public void setOwnerId(Long value);

    /**
     * Getter for <code>cattle.resource_pool.owner_id</code>.
     */
    @Column(name = "owner_id")
    public Long getOwnerId();

    /**
     * Setter for <code>cattle.resource_pool.qualifier</code>.
     */
    public void setResourcePoolQualifier(String value);

    /**
     * Getter for <code>cattle.resource_pool.qualifier</code>.
     */
    @Column(name = "qualifier", nullable = false, length = 128)
    public String getResourcePoolQualifier();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface ResourcePool
     */
    public void from(ResourcePool from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface ResourcePool
     */
    public <E extends ResourcePool> E into(E into);
}
