/*
 * This file is generated by jOOQ.
 */
package io.cattle.platform.core.model;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.io.Serializable;
import java.util.Date;
import java.util.Map;


/**
 * This class is generated by jOOQ.
 */
@Entity
@Table(
    name = "service_log",
    schema = "cattle"
)
public interface ServiceLog extends Serializable {

    /**
     * Setter for <code>cattle.service_log.id</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>cattle.service_log.id</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    public Long getId();

    /**
     * Setter for <code>cattle.service_log.account_id</code>.
     */
    public void setAccountId(Long value);

    /**
     * Getter for <code>cattle.service_log.account_id</code>.
     */
    @Column(name = "account_id")
    public Long getAccountId();

    /**
     * Setter for <code>cattle.service_log.kind</code>.
     */
    public void setKind(String value);

    /**
     * Getter for <code>cattle.service_log.kind</code>.
     */
    @Column(name = "kind", nullable = false, length = 255)
    public String getKind();

    /**
     * Setter for <code>cattle.service_log.description</code>.
     */
    public void setDescription(String value);

    /**
     * Getter for <code>cattle.service_log.description</code>.
     */
    @Column(name = "description", length = 1024)
    public String getDescription();

    /**
     * Setter for <code>cattle.service_log.created</code>.
     */
    public void setCreated(Date value);

    /**
     * Getter for <code>cattle.service_log.created</code>.
     */
    @Column(name = "created")
    public Date getCreated();

    /**
     * Setter for <code>cattle.service_log.data</code>.
     */
    public void setData(Map<String,Object> value);

    /**
     * Getter for <code>cattle.service_log.data</code>.
     */
    @Column(name = "data", length = 65535)
    public Map<String,Object> getData();

    /**
     * Setter for <code>cattle.service_log.end_time</code>.
     */
    public void setEndTime(Date value);

    /**
     * Getter for <code>cattle.service_log.end_time</code>.
     */
    @Column(name = "end_time")
    public Date getEndTime();

    /**
     * Setter for <code>cattle.service_log.event_type</code>.
     */
    public void setEventType(String value);

    /**
     * Getter for <code>cattle.service_log.event_type</code>.
     */
    @Column(name = "event_type", length = 255)
    public String getEventType();

    /**
     * Setter for <code>cattle.service_log.service_id</code>.
     */
    public void setServiceId(Long value);

    /**
     * Getter for <code>cattle.service_log.service_id</code>.
     */
    @Column(name = "service_id")
    public Long getServiceId();

    /**
     * Setter for <code>cattle.service_log.instance_id</code>.
     */
    public void setInstanceId(Long value);

    /**
     * Getter for <code>cattle.service_log.instance_id</code>.
     */
    @Column(name = "instance_id")
    public Long getInstanceId();

    /**
     * Setter for <code>cattle.service_log.transaction_id</code>.
     */
    public void setTransactionId(String value);

    /**
     * Getter for <code>cattle.service_log.transaction_id</code>.
     */
    @Column(name = "transaction_id", length = 255)
    public String getTransactionId();

    /**
     * Setter for <code>cattle.service_log.sub_log</code>.
     */
    public void setSubLog(Boolean value);

    /**
     * Getter for <code>cattle.service_log.sub_log</code>.
     */
    @Column(name = "sub_log", nullable = false)
    public Boolean getSubLog();

    /**
     * Setter for <code>cattle.service_log.level</code>.
     */
    public void setLevel(String value);

    /**
     * Getter for <code>cattle.service_log.level</code>.
     */
    @Column(name = "level", length = 255)
    public String getLevel();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface ServiceLog
     */
    public void from(ServiceLog from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface ServiceLog
     */
    public <E extends ServiceLog> E into(E into);
}
