/*
 * This file is generated by jOOQ.
 */
package io.cattle.platform.core.model;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import java.io.Serializable;
import java.util.Date;
import java.util.Map;


/**
 * This class is generated by jOOQ.
 */
@Entity
@Table(
    name = "service_event",
    schema = "cattle",
    uniqueConstraints = {
        @UniqueConstraint(name = "KEY_service_event_idx_service_event_uuid", columnNames = { "uuid" })
    },
    indexes = {
        @Index(name = "idx_service_event_name", columnList = "name ASC"),
        @Index(name = "idx_service_event_remove_time", columnList = "remove_time ASC"),
        @Index(name = "idx_service_event_removed", columnList = "removed ASC"),
        @Index(name = "idx_service_event_state", columnList = "state ASC")
    }
)
public interface ServiceEvent extends Serializable {

    /**
     * Setter for <code>cattle.service_event.id</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>cattle.service_event.id</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    public Long getId();

    /**
     * Setter for <code>cattle.service_event.name</code>.
     */
    public void setName(String value);

    /**
     * Getter for <code>cattle.service_event.name</code>.
     */
    @Column(name = "name", length = 255)
    public String getName();

    /**
     * Setter for <code>cattle.service_event.account_id</code>.
     */
    public void setAccountId(Long value);

    /**
     * Getter for <code>cattle.service_event.account_id</code>.
     */
    @Column(name = "account_id")
    public Long getAccountId();

    /**
     * Setter for <code>cattle.service_event.kind</code>.
     */
    public void setKind(String value);

    /**
     * Getter for <code>cattle.service_event.kind</code>.
     */
    @Column(name = "kind", nullable = false, length = 255)
    public String getKind();

    /**
     * Setter for <code>cattle.service_event.uuid</code>.
     */
    public void setUuid(String value);

    /**
     * Getter for <code>cattle.service_event.uuid</code>.
     */
    @Column(name = "uuid", nullable = false, length = 128)
    public String getUuid();

    /**
     * Setter for <code>cattle.service_event.description</code>.
     */
    public void setDescription(String value);

    /**
     * Getter for <code>cattle.service_event.description</code>.
     */
    @Column(name = "description", length = 1024)
    public String getDescription();

    /**
     * Setter for <code>cattle.service_event.state</code>.
     */
    public void setState(String value);

    /**
     * Getter for <code>cattle.service_event.state</code>.
     */
    @Column(name = "state", nullable = false, length = 128)
    public String getState();

    /**
     * Setter for <code>cattle.service_event.created</code>.
     */
    public void setCreated(Date value);

    /**
     * Getter for <code>cattle.service_event.created</code>.
     */
    @Column(name = "created")
    public Date getCreated();

    /**
     * Setter for <code>cattle.service_event.removed</code>.
     */
    public void setRemoved(Date value);

    /**
     * Getter for <code>cattle.service_event.removed</code>.
     */
    @Column(name = "removed")
    public Date getRemoved();

    /**
     * Setter for <code>cattle.service_event.remove_time</code>.
     */
    public void setRemoveTime(Date value);

    /**
     * Getter for <code>cattle.service_event.remove_time</code>.
     */
    @Column(name = "remove_time")
    public Date getRemoveTime();

    /**
     * Setter for <code>cattle.service_event.data</code>.
     */
    public void setData(Map<String,Object> value);

    /**
     * Getter for <code>cattle.service_event.data</code>.
     */
    @Column(name = "data", length = 16777215)
    public Map<String,Object> getData();

    /**
     * Setter for <code>cattle.service_event.host_id</code>.
     */
    public void setHostId(Long value);

    /**
     * Getter for <code>cattle.service_event.host_id</code>.
     */
    @Column(name = "host_id")
    public Long getHostId();

    /**
     * Setter for <code>cattle.service_event.healthcheck_uuid</code>.
     */
    public void setHealthcheckUuid(String value);

    /**
     * Getter for <code>cattle.service_event.healthcheck_uuid</code>.
     */
    @Column(name = "healthcheck_uuid", length = 255)
    public String getHealthcheckUuid();

    /**
     * Setter for <code>cattle.service_event.instance_id</code>.
     */
    public void setInstanceId(Long value);

    /**
     * Getter for <code>cattle.service_event.instance_id</code>.
     */
    @Column(name = "instance_id")
    public Long getInstanceId();

    /**
     * Setter for <code>cattle.service_event.healthcheck_instance_id</code>.
     */
    public void setHealthcheckInstanceId(Long value);

    /**
     * Getter for <code>cattle.service_event.healthcheck_instance_id</code>.
     */
    @Column(name = "healthcheck_instance_id")
    public Long getHealthcheckInstanceId();

    /**
     * Setter for <code>cattle.service_event.reported_health</code>.
     */
    public void setReportedHealth(String value);

    /**
     * Getter for <code>cattle.service_event.reported_health</code>.
     */
    @Column(name = "reported_health", length = 255)
    public String getReportedHealth();

    /**
     * Setter for <code>cattle.service_event.external_timestamp</code>.
     */
    public void setExternalTimestamp(Integer value);

    /**
     * Getter for <code>cattle.service_event.external_timestamp</code>.
     */
    @Column(name = "external_timestamp")
    public Integer getExternalTimestamp();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface ServiceEvent
     */
    public void from(ServiceEvent from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface ServiceEvent
     */
    public <E extends ServiceEvent> E into(E into);
}
