/*
 * This file is generated by jOOQ.
 */
package io.cattle.platform.core.model;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import java.io.Serializable;
import java.util.Date;
import java.util.Map;


/**
 * This class is generated by jOOQ.
 */
@Entity
@Table(
    name = "service_expose_map",
    schema = "cattle",
    uniqueConstraints = {
        @UniqueConstraint(name = "KEY_service_expose_map_idx_service_instance_map_uuid", columnNames = { "uuid" })
    },
    indexes = {
        @Index(name = "idx_service_instance_map_name", columnList = "name ASC"),
        @Index(name = "idx_service_instance_map_remove_time", columnList = "remove_time ASC"),
        @Index(name = "idx_service_instance_map_removed", columnList = "removed ASC"),
        @Index(name = "idx_service_instance_map_state", columnList = "state ASC")
    }
)
public interface ServiceExposeMap extends Serializable {

    /**
     * Setter for <code>cattle.service_expose_map.id</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>cattle.service_expose_map.id</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    public Long getId();

    /**
     * Setter for <code>cattle.service_expose_map.name</code>.
     */
    public void setName(String value);

    /**
     * Getter for <code>cattle.service_expose_map.name</code>.
     */
    @Column(name = "name", length = 255)
    public String getName();

    /**
     * Setter for <code>cattle.service_expose_map.kind</code>.
     */
    public void setKind(String value);

    /**
     * Getter for <code>cattle.service_expose_map.kind</code>.
     */
    @Column(name = "kind", nullable = false, length = 255)
    public String getKind();

    /**
     * Setter for <code>cattle.service_expose_map.uuid</code>.
     */
    public void setUuid(String value);

    /**
     * Getter for <code>cattle.service_expose_map.uuid</code>.
     */
    @Column(name = "uuid", nullable = false, length = 128)
    public String getUuid();

    /**
     * Setter for <code>cattle.service_expose_map.description</code>.
     */
    public void setDescription(String value);

    /**
     * Getter for <code>cattle.service_expose_map.description</code>.
     */
    @Column(name = "description", length = 1024)
    public String getDescription();

    /**
     * Setter for <code>cattle.service_expose_map.state</code>.
     */
    public void setState(String value);

    /**
     * Getter for <code>cattle.service_expose_map.state</code>.
     */
    @Column(name = "state", nullable = false, length = 128)
    public String getState();

    /**
     * Setter for <code>cattle.service_expose_map.created</code>.
     */
    public void setCreated(Date value);

    /**
     * Getter for <code>cattle.service_expose_map.created</code>.
     */
    @Column(name = "created")
    public Date getCreated();

    /**
     * Setter for <code>cattle.service_expose_map.removed</code>.
     */
    public void setRemoved(Date value);

    /**
     * Getter for <code>cattle.service_expose_map.removed</code>.
     */
    @Column(name = "removed")
    public Date getRemoved();

    /**
     * Setter for <code>cattle.service_expose_map.remove_time</code>.
     */
    public void setRemoveTime(Date value);

    /**
     * Getter for <code>cattle.service_expose_map.remove_time</code>.
     */
    @Column(name = "remove_time")
    public Date getRemoveTime();

    /**
     * Setter for <code>cattle.service_expose_map.data</code>.
     */
    public void setData(Map<String,Object> value);

    /**
     * Getter for <code>cattle.service_expose_map.data</code>.
     */
    @Column(name = "data", length = 16777215)
    public Map<String,Object> getData();

    /**
     * Setter for <code>cattle.service_expose_map.service_id</code>.
     */
    public void setServiceId(Long value);

    /**
     * Getter for <code>cattle.service_expose_map.service_id</code>.
     */
    @Column(name = "service_id")
    public Long getServiceId();

    /**
     * Setter for <code>cattle.service_expose_map.instance_id</code>.
     */
    public void setInstanceId(Long value);

    /**
     * Getter for <code>cattle.service_expose_map.instance_id</code>.
     */
    @Column(name = "instance_id")
    public Long getInstanceId();

    /**
     * Setter for <code>cattle.service_expose_map.account_id</code>.
     */
    public void setAccountId(Long value);

    /**
     * Getter for <code>cattle.service_expose_map.account_id</code>.
     */
    @Column(name = "account_id")
    public Long getAccountId();

    /**
     * Setter for <code>cattle.service_expose_map.ip_address</code>.
     */
    public void setIpAddress(String value);

    /**
     * Getter for <code>cattle.service_expose_map.ip_address</code>.
     */
    @Column(name = "ip_address", length = 255)
    public String getIpAddress();

    /**
     * Setter for <code>cattle.service_expose_map.dns_prefix</code>.
     */
    public void setDnsPrefix(String value);

    /**
     * Getter for <code>cattle.service_expose_map.dns_prefix</code>.
     */
    @Column(name = "dns_prefix", length = 128)
    public String getDnsPrefix();

    /**
     * Setter for <code>cattle.service_expose_map.host_name</code>.
     */
    public void setHostName(String value);

    /**
     * Getter for <code>cattle.service_expose_map.host_name</code>.
     */
    @Column(name = "host_name", length = 255)
    public String getHostName();

    /**
     * Setter for <code>cattle.service_expose_map.managed</code>.
     */
    public void setManaged(Boolean value);

    /**
     * Getter for <code>cattle.service_expose_map.managed</code>.
     */
    @Column(name = "managed", nullable = false)
    public Boolean getManaged();

    /**
     * Setter for <code>cattle.service_expose_map.upgrade</code>.
     */
    public void setUpgrade(Boolean value);

    /**
     * Getter for <code>cattle.service_expose_map.upgrade</code>.
     */
    @Column(name = "upgrade", nullable = false)
    public Boolean getUpgrade();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface ServiceExposeMap
     */
    public void from(ServiceExposeMap from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface ServiceExposeMap
     */
    public <E extends ServiceExposeMap> E into(E into);
}
