/*
 * This file is generated by jOOQ.
 */
package io.cattle.platform.core.model;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import java.io.Serializable;
import java.util.Date;
import java.util.Map;


/**
 * This class is generated by jOOQ.
 */
@Entity
@Table(
    name = "service",
    schema = "cattle",
    uniqueConstraints = {
        @UniqueConstraint(name = "KEY_service_idx_service_uuid", columnNames = { "uuid" })
    },
    indexes = {
        @Index(name = "idx_service_external_id", columnList = "external_id ASC"),
        @Index(name = "idx_service_name", columnList = "name ASC"),
        @Index(name = "idx_service_remove_time", columnList = "remove_time ASC"),
        @Index(name = "idx_service_removed", columnList = "removed ASC"),
        @Index(name = "idx_service_state", columnList = "state ASC")
    }
)
public interface Service extends Serializable {

    /**
     * Setter for <code>cattle.service.id</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>cattle.service.id</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    public Long getId();

    /**
     * Setter for <code>cattle.service.name</code>.
     */
    public void setName(String value);

    /**
     * Getter for <code>cattle.service.name</code>.
     */
    @Column(name = "name", length = 255)
    public String getName();

    /**
     * Setter for <code>cattle.service.account_id</code>.
     */
    public void setAccountId(Long value);

    /**
     * Getter for <code>cattle.service.account_id</code>.
     */
    @Column(name = "account_id")
    public Long getAccountId();

    /**
     * Setter for <code>cattle.service.kind</code>.
     */
    public void setKind(String value);

    /**
     * Getter for <code>cattle.service.kind</code>.
     */
    @Column(name = "kind", nullable = false, length = 255)
    public String getKind();

    /**
     * Setter for <code>cattle.service.uuid</code>.
     */
    public void setUuid(String value);

    /**
     * Getter for <code>cattle.service.uuid</code>.
     */
    @Column(name = "uuid", nullable = false, length = 128)
    public String getUuid();

    /**
     * Setter for <code>cattle.service.description</code>.
     */
    public void setDescription(String value);

    /**
     * Getter for <code>cattle.service.description</code>.
     */
    @Column(name = "description", length = 1024)
    public String getDescription();

    /**
     * Setter for <code>cattle.service.state</code>.
     */
    public void setState(String value);

    /**
     * Getter for <code>cattle.service.state</code>.
     */
    @Column(name = "state", nullable = false, length = 128)
    public String getState();

    /**
     * Setter for <code>cattle.service.created</code>.
     */
    public void setCreated(Date value);

    /**
     * Getter for <code>cattle.service.created</code>.
     */
    @Column(name = "created")
    public Date getCreated();

    /**
     * Setter for <code>cattle.service.removed</code>.
     */
    public void setRemoved(Date value);

    /**
     * Getter for <code>cattle.service.removed</code>.
     */
    @Column(name = "removed")
    public Date getRemoved();

    /**
     * Setter for <code>cattle.service.remove_time</code>.
     */
    public void setRemoveTime(Date value);

    /**
     * Getter for <code>cattle.service.remove_time</code>.
     */
    @Column(name = "remove_time")
    public Date getRemoveTime();

    /**
     * Setter for <code>cattle.service.data</code>.
     */
    public void setData(Map<String,Object> value);

    /**
     * Getter for <code>cattle.service.data</code>.
     */
    @Column(name = "data", length = 16777215)
    public Map<String,Object> getData();

    /**
     * Setter for <code>cattle.service.environment_id</code>.
     */
    public void setStackId(Long value);

    /**
     * Getter for <code>cattle.service.environment_id</code>.
     */
    @Column(name = "environment_id")
    public Long getStackId();

    /**
     * Setter for <code>cattle.service.vip</code>.
     */
    public void setVip(String value);

    /**
     * Getter for <code>cattle.service.vip</code>.
     */
    @Column(name = "vip", length = 255)
    public String getVip();

    /**
     * Setter for <code>cattle.service.create_index</code>.
     */
    public void setCreateIndex(Long value);

    /**
     * Getter for <code>cattle.service.create_index</code>.
     */
    @Column(name = "create_index")
    public Long getCreateIndex();

    /**
     * Setter for <code>cattle.service.selector_link</code>.
     */
    public void setSelectorLink(String value);

    /**
     * Getter for <code>cattle.service.selector_link</code>.
     */
    @Column(name = "selector_link", length = 4096)
    public String getSelectorLink();

    /**
     * Setter for <code>cattle.service.selector_container</code>.
     */
    public void setSelectorContainer(String value);

    /**
     * Getter for <code>cattle.service.selector_container</code>.
     */
    @Column(name = "selector_container", length = 4096)
    public String getSelectorContainer();

    /**
     * Setter for <code>cattle.service.external_id</code>.
     */
    public void setExternalId(String value);

    /**
     * Getter for <code>cattle.service.external_id</code>.
     */
    @Column(name = "external_id", length = 255)
    public String getExternalId();

    /**
     * Setter for <code>cattle.service.health_state</code>.
     */
    public void setHealthState(String value);

    /**
     * Getter for <code>cattle.service.health_state</code>.
     */
    @Column(name = "health_state", length = 128)
    public String getHealthState();

    /**
     * Setter for <code>cattle.service.system</code>.
     */
    public void setSystem(Boolean value);

    /**
     * Getter for <code>cattle.service.system</code>.
     */
    @Column(name = "system", nullable = false)
    public Boolean getSystem();

    /**
     * Setter for <code>cattle.service.skip</code>.
     */
    public void setSkip(Boolean value);

    /**
     * Getter for <code>cattle.service.skip</code>.
     */
    @Column(name = "skip", nullable = false)
    public Boolean getSkip();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface Service
     */
    public void from(Service from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface Service
     */
    public <E extends Service> E into(E into);
}
