/*
 * This file is generated by jOOQ.
 */
package io.cattle.platform.core.model;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@Entity
@Table(
    name = "task",
    schema = "cattle",
    uniqueConstraints = {
        @UniqueConstraint(name = "KEY_task_idx_task_name", columnNames = { "name" })
    }
)
public interface Task extends Serializable {

    /**
     * Setter for <code>cattle.task.id</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>cattle.task.id</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    public Long getId();

    /**
     * Setter for <code>cattle.task.name</code>.
     */
    public void setName(String value);

    /**
     * Getter for <code>cattle.task.name</code>.
     */
    @Column(name = "name", nullable = false, length = 128)
    public String getName();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface Task
     */
    public void from(Task from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface Task
     */
    public <E extends Task> E into(E into);
}
