/*
 * This file is generated by jOOQ.
 */
package io.cattle.platform.core.model;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import java.io.Serializable;
import java.util.Date;
import java.util.Map;


/**
 * This class is generated by jOOQ.
 */
@Entity
@Table(
    name = "volume",
    schema = "cattle",
    uniqueConstraints = {
        @UniqueConstraint(name = "KEY_volume_idx_volume_uuid", columnNames = { "uuid" })
    },
    indexes = {
        @Index(name = "idx_volume_external_id", columnList = "external_id ASC"),
        @Index(name = "idx_volume_name", columnList = "name ASC"),
        @Index(name = "idx_volume_remove_time", columnList = "remove_time ASC"),
        @Index(name = "idx_volume_removed", columnList = "removed ASC"),
        @Index(name = "idx_volume_state", columnList = "state ASC"),
        @Index(name = "idx_volume_uri", columnList = "uri ASC")
    }
)
public interface Volume extends Serializable {

    /**
     * Setter for <code>cattle.volume.id</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>cattle.volume.id</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    public Long getId();

    /**
     * Setter for <code>cattle.volume.name</code>.
     */
    public void setName(String value);

    /**
     * Getter for <code>cattle.volume.name</code>.
     */
    @Column(name = "name", length = 255)
    public String getName();

    /**
     * Setter for <code>cattle.volume.account_id</code>.
     */
    public void setAccountId(Long value);

    /**
     * Getter for <code>cattle.volume.account_id</code>.
     */
    @Column(name = "account_id")
    public Long getAccountId();

    /**
     * Setter for <code>cattle.volume.kind</code>.
     */
    public void setKind(String value);

    /**
     * Getter for <code>cattle.volume.kind</code>.
     */
    @Column(name = "kind", nullable = false, length = 255)
    public String getKind();

    /**
     * Setter for <code>cattle.volume.uuid</code>.
     */
    public void setUuid(String value);

    /**
     * Getter for <code>cattle.volume.uuid</code>.
     */
    @Column(name = "uuid", nullable = false, length = 128)
    public String getUuid();

    /**
     * Setter for <code>cattle.volume.description</code>.
     */
    public void setDescription(String value);

    /**
     * Getter for <code>cattle.volume.description</code>.
     */
    @Column(name = "description", length = 1024)
    public String getDescription();

    /**
     * Setter for <code>cattle.volume.state</code>.
     */
    public void setState(String value);

    /**
     * Getter for <code>cattle.volume.state</code>.
     */
    @Column(name = "state", nullable = false, length = 128)
    public String getState();

    /**
     * Setter for <code>cattle.volume.created</code>.
     */
    public void setCreated(Date value);

    /**
     * Getter for <code>cattle.volume.created</code>.
     */
    @Column(name = "created")
    public Date getCreated();

    /**
     * Setter for <code>cattle.volume.removed</code>.
     */
    public void setRemoved(Date value);

    /**
     * Getter for <code>cattle.volume.removed</code>.
     */
    @Column(name = "removed")
    public Date getRemoved();

    /**
     * Setter for <code>cattle.volume.remove_time</code>.
     */
    public void setRemoveTime(Date value);

    /**
     * Getter for <code>cattle.volume.remove_time</code>.
     */
    @Column(name = "remove_time")
    public Date getRemoveTime();

    /**
     * Setter for <code>cattle.volume.data</code>.
     */
    public void setData(Map<String,Object> value);

    /**
     * Getter for <code>cattle.volume.data</code>.
     */
    @Column(name = "data", length = 16777215)
    public Map<String,Object> getData();

    /**
     * Setter for <code>cattle.volume.physical_size_mb</code>.
     */
    public void setPhysicalSizeMb(Long value);

    /**
     * Getter for <code>cattle.volume.physical_size_mb</code>.
     */
    @Column(name = "physical_size_mb")
    public Long getPhysicalSizeMb();

    /**
     * Setter for <code>cattle.volume.virtual_size_mb</code>.
     */
    public void setVirtualSizeMb(Long value);

    /**
     * Getter for <code>cattle.volume.virtual_size_mb</code>.
     */
    @Column(name = "virtual_size_mb")
    public Long getVirtualSizeMb();

    /**
     * Setter for <code>cattle.volume.device_number</code>.
     */
    public void setDeviceNumber(Integer value);

    /**
     * Getter for <code>cattle.volume.device_number</code>.
     */
    @Column(name = "device_number")
    public Integer getDeviceNumber();

    /**
     * Setter for <code>cattle.volume.format</code>.
     */
    public void setFormat(String value);

    /**
     * Getter for <code>cattle.volume.format</code>.
     */
    @Column(name = "format", length = 255)
        public String getFormat();

    /**
     * Setter for <code>cattle.volume.allocation_state</code>.
     */
    public void setAllocationState(String value);

    /**
     * Getter for <code>cattle.volume.allocation_state</code>.
     */
    @Column(name = "allocation_state", length = 255)
    public String getAllocationState();

    /**
     * Setter for <code>cattle.volume.attached_state</code>.
     */
    public void setAttachedState(String value);

    /**
     * Getter for <code>cattle.volume.attached_state</code>.
     */
    @Column(name = "attached_state", length = 255)
    public String getAttachedState();

    /**
     * Setter for <code>cattle.volume.instance_id</code>.
     */
    public void setInstanceId(Long value);

    /**
     * Getter for <code>cattle.volume.instance_id</code>.
     */
    @Column(name = "instance_id")
    public Long getInstanceId();

    /**
     * Setter for <code>cattle.volume.image_id</code>.
     */
    public void setImageId(Long value);

    /**
     * Getter for <code>cattle.volume.image_id</code>.
     */
    @Column(name = "image_id")
    public Long getImageId();

    /**
     * Setter for <code>cattle.volume.zone_id</code>.
     */
    public void setZoneId(Long value);

    /**
     * Getter for <code>cattle.volume.zone_id</code>.
     */
    @Column(name = "zone_id")
    public Long getZoneId();

    /**
     * Setter for <code>cattle.volume.uri</code>.
     */
    public void setUri(String value);

    /**
     * Getter for <code>cattle.volume.uri</code>.
     */
    @Column(name = "uri", length = 255)
    public String getUri();

    /**
     * Setter for <code>cattle.volume.external_id</code>.
     */
    public void setExternalId(String value);

    /**
     * Getter for <code>cattle.volume.external_id</code>.
     */
    @Column(name = "external_id", length = 128)
    public String getExternalId();

    /**
     * Setter for <code>cattle.volume.access_mode</code>.
     */
    public void setAccessMode(String value);

    /**
     * Getter for <code>cattle.volume.access_mode</code>.
     */
    @Column(name = "access_mode", length = 255)
    public String getAccessMode();

    /**
     * Setter for <code>cattle.volume.host_id</code>.
     */
    public void setHostId(Long value);

    /**
     * Getter for <code>cattle.volume.host_id</code>.
     */
    @Column(name = "host_id")
    public Long getHostId();

    /**
     * Setter for <code>cattle.volume.deployment_unit_id</code>.
     */
    public void setDeploymentUnitId(Long value);

    /**
     * Getter for <code>cattle.volume.deployment_unit_id</code>.
     */
    @Column(name = "deployment_unit_id")
    public Long getDeploymentUnitId();

    /**
     * Setter for <code>cattle.volume.environment_id</code>.
     */
    public void setStackId(Long value);

    /**
     * Getter for <code>cattle.volume.environment_id</code>.
     */
    @Column(name = "environment_id")
    public Long getStackId();

    /**
     * Setter for <code>cattle.volume.volume_template_id</code>.
     */
    public void setVolumeTemplateId(Long value);

    /**
     * Getter for <code>cattle.volume.volume_template_id</code>.
     */
    @Column(name = "volume_template_id")
    public Long getVolumeTemplateId();

    /**
     * Setter for <code>cattle.volume.storage_driver_id</code>.
     */
    public void setStorageDriverId(Long value);

    /**
     * Getter for <code>cattle.volume.storage_driver_id</code>.
     */
    @Column(name = "storage_driver_id")
    public Long getStorageDriverId();

    /**
     * Setter for <code>cattle.volume.size_mb</code>.
     */
    public void setSizeMb(Long value);

    /**
     * Getter for <code>cattle.volume.size_mb</code>.
     */
    @Column(name = "size_mb")
    public Long getSizeMb();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface Volume
     */
    public void from(Volume from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface Volume
     */
    public <E extends Volume> E into(E into);
}
