#!/bin/bash

cd $(dirname $0)/..

maven_cmd=${MAVEN_CMD:-mvn}
if ! command -v "$maven_cmd" >/dev/null 2>&1; then
    maven_cmd=./mvnw
fi

if ! "$maven_cmd" checkstyle:checkstyle-aggregate; then
    grep -C 1 error target/checkstyle-result.xml
    echo Checkstyle Errors 1>&2
    exit 1
fi
