#!/bin/bash
set -e

cd $(dirname $0)

pull()
{
    # Don't pull if we have the image locally
    if docker inspect $1 >/dev/null 2>&1; then
        return 0
    fi

    docker pull $1
}

pull "${BUSYBOX_IMAGE:-busybox:1@sha256:dc2d74b28e4cf8984fa52af1f39bc7c3d9c73760b41a74d629f5d11b1ab28616}"
for i in bootstrap.required.image; do
    pull $(grep $i ../resources/content/cattle-global.properties | cut -f2 -d=)
done
